project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Finans Matematiği"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Faiz Hesapları"
      chapters:
        - faiz/basit-faiz.qmd
        - faiz/paranin-zaman-degeri.qmd
        - faiz/taksitli-odemeler.qmd
        - faiz/basit-iskonto.qmd
        - faiz/senetler-ve-bonolar.qmd
        - faiz/bilesik-faiz.qmd
        - faiz/esdeger-oranlar.qmd
        - faiz/oran-zaman-ve-bilesik-iskonto.qmd

    - part: "Anüiteler"
      chapters:
        - anuiteler/normal-anuite.qmd
        - anuiteler/pesin-ve-ertelenmis-anuiteler.qmd
        - anuiteler/anuitenin-donemi.qmd
        - anuiteler/anuitenin-faiz-orani.qmd
        - anuiteler/genel-anuiteler-ve-daimi-gelir.qmd

    - part: "Amortisman"
      chapters:
        - amortisman/amortisman-hesaplari.qmd
        - amortisman/kalan-borc.qmd

    - part: "Tahviller"
      chapters:
        - tahviller/tahviller.qmd
        - tahviller/tahvilin-getirisi.qmd

    - part: "Hayat Anüiteleri ve Sigortalar"
      chapters:
        - hayat/hayat-tablolari.qmd
        - hayat/hayat-anuiteleri.qmd
        - hayat/hayat-sigortalari.qmd

    - part: "Hisse Senetleri ve Portföy"
      chapters:
        - hisse/hisse-senetleri.qmd
        - hisse/hisse-riski.qmd
        - hisse/portfoy-olusturma.qmd
        - hisse/cok-hisseli-portfoy.qmd
