project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Analiz 2: Türev ve İntegral"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Türev"
      chapters:
        - monoton-fonksiyonlar-ve-ters-fonksiyon.qmd
        - turev-kavrami.qmd
        - turev-kurallari.qmd
        - zincir-kurali-ve-ters-fonksiyonun-turevi.qmd
        - temel-fonksiyonlarin-turevleri.qmd
        - yuksek-mertebeden-turevler.qmd

    - part: "Türevin Temel Teoremleri"
      chapters:
        - ekstremum-ve-fermat-teoremi.qmd
        - rolle-ve-ortalama-deger-teoremi.qmd
        - ortalama-deger-teoreminin-uygulamalari.qmd
        - darboux-teoremi.qmd
        - lhospital-kurali.qmd

    - part: "Taylor Formülü ve Fonksiyon İncelemesi"
      chapters:
        - taylor-formulu.qmd
        - taylor-formulunun-uygulamalari.qmd
        - monotonluk-ve-ekstremum-testleri.qmd
        - konveks-fonksiyonlar.qmd
        - donum-noktalari.qmd
        - asimptotlar-ve-grafik-cizimi.qmd

    - part: "Belirsiz İntegral"
      chapters:
        - ilkel-fonksiyon-ve-belirsiz-integral.qmd
        - integral-alma-yontemleri.qmd
        - rasyonel-fonksiyonlarin-integrali.qmd
        - irrasyonel-fonksiyonlarin-integrali.qmd
        - trigonometrik-fonksiyonlarin-integrali.qmd
        - trigonometrik-donusumler.qmd

    - part: "Belirli İntegral"
      chapters:
        - bolunusler-ve-darboux-toplamlari.qmd
        - riemann-integrallenebilirlik-olcutu.qmd
        - riemann-toplamlari.qmd
        - integralin-cebirsel-ozellikleri.qmd
        - integralde-siralama-ve-esitsizlikler.qmd
        - analizin-temel-teoremleri.qmd
        - belirli-integralde-yontemler.qmd
        - integral-icin-ortalama-deger-teoremleri.qmd
        - integral-esitsizlikleri.qmd
        - belirli-integralin-uygulamalari.qmd

    - part: "Sayı Serileri"
      chapters:
        - serilere-giris.qmd
        - pozitif-terimli-seriler.qmd
        - yogunlastirma-ve-p-serileri.qmd
        - kok-ve-oran-testleri.qmd
        - kummer-ve-raabe-testleri.qmd
        - mutlak-ve-sartli-yakinsaklik.qmd
        - abel-dirichlet-ve-leibniz-testleri.qmd
        - yeniden-duzenleme-ve-gruplama.qmd

    - part: "Kuvvet Serileri"
      chapters:
        - kuvvet-serileri.qmd
        - kuvvet-serilerinin-ozellikleri.qmd
        - taylor-ve-maclaurin-serileri.qmd

