project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Analitik Geometri"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd
    - part: "Düzlemde Koordinatlar"
      chapters:
        - dik-koordinatlar-ve-uzaklik.qmd
        - bolme-orani-egim-ve-aci.qmd
        - duzlemde-dogru-denklemleri.qmd
        - cember.qmd
        - paralel-ve-kutupsal-koordinatlar.qmd
    - part: "Uzay ve Vektörler"
      chapters:
        - uzayda-dik-koordinat-sistemi.qmd
        - vektorler.qmd
        - ic-carpim.qmd
        - vektorel-ve-karma-carpim.qmd
    - part: "Uzayda Doğru ve Düzlem"
      chapters:
        - uzayda-dogru-denklemleri.qmd
        - uzayda-iki-dogru.qmd
        - uzayda-duzlem-denklemleri.qmd
        - iki-duzlem-ve-duzlemin-irdelenmesi.qmd
        - dogru-ile-duzlem-ve-uzakliklar.qmd
        - uzayda-simetri.qmd
    - part: "Koordinat Dönüşümleri"
      chapters:
        - oteleme.qmd
        - dondurme-ve-paralel-eksenler.qmd
    - part: "Konikler"
      chapters:
        - elips.qmd
        - hiperbol.qmd
        - parabol.qmd
        - koniklerin-siniflandirilmasi.qmd
    - part: "Uzayda Koordinat Sistemleri ve Yüzeyler"
      chapters:
        - silindirik-ve-kuresel-koordinatlar.qmd
        - ozel-yuzeyler.qmd
