project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Analiz 3: Fonksiyon Dizileri ve Seriler"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Fonksiyon Dizileri"
      chapters:
        - fonksiyon-dizilerinde-noktasal-yakinsaklik.qmd
        - duzgun-yakinsaklik.qmd
        - duzgun-yakinsaklik-olcutleri.qmd
        - duzgun-yakinsaklik-sinirlilik-ve-sureklilik.qmd
        - duzgun-yakinsaklik-ve-integral.qmd
        - duzgun-yakinsaklik-ve-turev.qmd

    - part: "Fonksiyon Serileri"
      chapters:
        - fonksiyon-serileri.qmd
        - fonksiyon-serilerinin-ozellikleri.qmd
        - kuvvet-serilerinde-duzgun-yakinsaklik.qmd

    - part: "Fourier Serileri"
      chapters:
        - trigonometrik-seriler-ve-fourier-katsayilari.qmd
        - en-iyi-yaklasim-ve-bessel-esitsizligi.qmd
        - fourier-serilerinin-noktasal-yakinsakligi.qmd
        - fourier-serilerinin-duzgun-yakinsakligi-ve-parseval.qmd
        - fourier-sinus-ve-kosinus-serileri.qmd

    - part: "Genelleştirilmiş İntegraller"
      chapters:
        - genellestirilmis-integraller.qmd
        - birinci-tip-yakinsaklik-testleri.qmd
        - ikinci-tip-genellestirilmis-integraller.qmd
        - euler-integralleri.qmd

    - part: "Parametreye Bağlı İntegraller"
      chapters:
        - parametreye-bagli-integraller.qmd
        - parametreye-bagli-genellestirilmis-integraller.qmd

    - uygulamali-ozet.qmd
