---
title: "Fonksiyon Dizilerinde Noktasal Yakınsaklık"
pagetitle: "Fonksiyon Dizilerinde Noktasal Yakınsaklık"
description: "Fonksiyon dizisi kavramı, noktasal yakınsaklığın epsilon–N tanımı, noktasal limit hesabı örnekleri, yakınsamamanın sembolik ifadesi, noktasal limitin cebirsel özellikleri ve noktasal limitin sürekliliği, türevlenebilirliği ve integrallenebilirliği korumadığını gösteren örnekler."
---

Analiz 1'de terimleri reel sayı olan dizileri, Analiz 2'nin sonunda da terimleri sayı olan serileri inceledik. Şimdi bir adım yukarı çıkıyoruz: dizinin terimleri artık sayı değil, **fonksiyon** olacak. Örneğin $x, x^2, x^3, \dots$ fonksiyonları bir dizi oluşturur ve doğal soru şudur: $n$ büyüdükçe bu fonksiyonlar bir fonksiyona "yaklaşır" mı?

Bu sorunun en yalın yanıtı, her noktaya ayrı ayrı bakmaktır. $x$ sabitlenince $x, x^2, x^3, \dots$ sıradan bir sayı dizisi olur ve limitini Analiz 1'in araçlarıyla buluruz. Bu bakış **noktasal yakınsaklık** adını alır. Hesabı kolaydır, ama bir kusuru vardır: sürekli fonksiyonların noktasal limiti sürekli çıkmayabilir, integrallenebilir fonksiyonların noktasal limiti integrallenemeyebilir. Bu kusur, sonraki bölümün konusu olan düzgün yakınsaklığa duyulan ihtiyacı doğurur.

Bu bölümde fonksiyon dizisini ve noktasal yakınsaklığı tanımlıyor, noktasal limitin nasıl hesaplandığını örneklerle görüyor ve noktasal limitin hangi özellikleri koruyup hangilerini korumadığını inceliyoruz.

## Fonksiyon Dizisi

Bir sayı dizisi, her doğal sayıya bir reel sayı karşılık getiren bir kuraldır. Fonksiyon dizisinde her doğal sayıya bir fonksiyon karşılık gelir.

::: {#def-nok-fonksiyon-dizisi name="Fonksiyon Dizisi"}
$E \subseteq \mathbb{R}$ boş olmayan bir küme olsun. Her $n \in \mathbb{N}$ için bir $f_n : E \to \mathbb{R}$ fonksiyonu verilmişse $n \mapsto f_n$ eşlemesine $E$ üzerinde tanımlı bir **fonksiyon dizisi** denir ve $(f_n)_{n \in \mathbb{N}}$ ya da kısaca $(f_n)$ ile gösterilir.
:::

Yani bir fonksiyon dizisi, hepsi aynı $E$ kümesinde tanımlı $f_1, f_2, f_3, \dots$ fonksiyonlarının sıralı bir listesidir. Önemli gözlem şudur: bir $x \in E$ noktası sabitlenince

$$\big(f_n(x)\big)_{n \in \mathbb{N}} = \big(f_1(x),\ f_2(x),\ f_3(x),\ \dots\big)$$

bir **reel sayı dizisi** olur. Böylece bir fonksiyon dizisi, $E$'nin her noktası için bir tane olmak üzere, sayı dizilerinden oluşan bir aile gibi düşünülebilir. Sayı dizileri için bildiğimiz her kavram (yakınsaklık, sınırlılık, monotonluk) bu dizilere uygulanabilir.

Bölüm boyunca bize eşlik edecek temel örnek şudur: $E = [0, 1]$ ve her $n \in \mathbb{N}$ için $f_n(x) = x^n$. Dizinin ilk terimleri $f_1(x) = x$, $f_2(x) = x^2$, $f_3(x) = x^3$ fonksiyonlarıdır. $x = \dfrac{1}{2}$ noktası sabitlenirse

$$\left(f_n\left(\tfrac{1}{2}\right)\right) = \left(\frac{1}{2},\ \frac{1}{2^2},\ \frac{1}{2^3},\ \dots\right)$$

sayı dizisi elde edilir; bu dizi $0$'a yakınsar. $x = 1$ sabitlenirse $(1, 1, 1, \dots)$ sabit dizisi çıkar; bu dizi $1$'e yakınsar.

```{=html}
<figure class="ders-grafik ders-grafik-dar">
<svg viewBox="8.0 -11.5 343.0 285.5" role="img" aria-label="Powers of x on the unit interval collapsing to zero except at the right endpoint">
  <g stroke="var(--academic-text)" stroke-width="1.1" opacity="0.45">
  <line x1="44.0" y1="242.0" x2="322.0" y2="242.0"/>
  <line x1="44.0" y1="14.0" x2="44.0" y2="242.0"/>
  </g>
  <g fill="var(--academic-text)" font-size="11" opacity="0.7">
  <text x="171.4" y="258.0" text-anchor="middle">0,5</text>
  <text x="298.7" y="258.0" text-anchor="middle">1</text>
  <text x="37.0" y="146.0" text-anchor="end">0,5</text>
  <text x="37.0" y="46.0" text-anchor="end">1</text>
  <text x="328.0" y="246.0" font-style="italic">x</text>
  <text x="40.0" y="8.0" text-anchor="middle" font-style="italic">y</text>
  </g>
  <path d="M44.0,242.0 L44.8,241.3 L45.7,240.7 L46.5,240.0 L47.4,239.3 L48.2,238.7 L49.1,238.0 L49.9,237.3 L50.8,236.7 L51.6,236.0 L52.5,235.3 L53.3,234.7 L54.2,234.0 L55.0,233.3 L55.9,232.7 L56.7,232.0 L57.6,231.3 L58.4,230.7 L59.3,230.0 L60.1,229.3 L61.0,228.7 L61.8,228.0 L62.7,227.3 L63.5,226.7 L64.4,226.0 L65.2,225.3 L66.1,224.7 L66.9,224.0 L67.8,223.3 L68.6,222.7 L69.5,222.0 L70.3,221.3 L71.2,220.7 L72.0,220.0 L72.9,219.3 L73.7,218.7 L74.6,218.0 L75.4,217.3 L76.3,216.7 L77.1,216.0 L78.0,215.3 L78.8,214.7 L79.7,214.0 L80.5,213.3 L81.4,212.7 L82.2,212.0 L83.1,211.3 L83.9,210.7 L84.8,210.0 L85.6,209.3 L86.5,208.7 L87.3,208.0 L88.2,207.3 L89.0,206.7 L89.8,206.0 L90.7,205.3 L91.5,204.7 L92.4,204.0 L93.2,203.3 L94.1,202.7 L94.9,202.0 L95.8,201.3 L96.6,200.7 L97.5,200.0 L98.3,199.3 L99.2,198.7 L100.0,198.0 L100.9,197.3 L101.7,196.7 L102.6,196.0 L103.4,195.3 L104.3,194.7 L105.1,194.0 L106.0,193.3 L106.8,192.7 L107.7,192.0 L108.5,191.3 L109.4,190.7 L110.2,190.0 L111.1,189.3 L111.9,188.7 L112.8,188.0 L113.6,187.3 L114.5,186.7 L115.3,186.0 L116.2,185.3 L117.0,184.7 L117.9,184.0 L118.7,183.3 L119.6,182.7 L120.4,182.0 L121.3,181.3 L122.1,180.7 L123.0,180.0 L123.8,179.3 L124.7,178.7 L125.5,178.0 L126.4,177.3 L127.2,176.7 L128.1,176.0 L128.9,175.3 L129.8,174.7 L130.6,174.0 L131.5,173.3 L132.3,172.7 L133.2,172.0 L134.0,171.3 L134.8,170.7 L135.7,170.0 L136.5,169.3 L137.4,168.7 L138.2,168.0 L139.1,167.3 L139.9,166.7 L140.8,166.0 L141.6,165.3 L142.5,164.7 L143.3,164.0 L144.2,163.3 L145.0,162.7 L145.9,162.0 L146.7,161.3 L147.6,160.7 L148.4,160.0 L149.3,159.3 L150.1,158.7 L151.0,158.0 L151.8,157.3 L152.7,156.7 L153.5,156.0 L154.4,155.3 L155.2,154.7 L156.1,154.0 L156.9,153.3 L157.8,152.7 L158.6,152.0 L159.5,151.3 L160.3,150.7 L161.2,150.0 L162.0,149.3 L162.9,148.7 L163.7,148.0 L164.6,147.3 L165.4,146.7 L166.3,146.0 L167.1,145.3 L168.0,144.7 L168.8,144.0 L169.7,143.3 L170.5,142.7 L171.4,142.0 L172.2,141.3 L173.1,140.7 L173.9,140.0 L174.8,139.3 L175.6,138.7 L176.5,138.0 L177.3,137.3 L178.2,136.7 L179.0,136.0 L179.8,135.3 L180.7,134.7 L181.5,134.0 L182.4,133.3 L183.2,132.7 L184.1,132.0 L184.9,131.3 L185.8,130.7 L186.6,130.0 L187.5,129.3 L188.3,128.7 L189.2,128.0 L190.0,127.3 L190.9,126.7 L191.7,126.0 L192.6,125.3 L193.4,124.7 L194.3,124.0 L195.1,123.3 L196.0,122.7 L196.8,122.0 L197.7,121.3 L198.5,120.7 L199.4,120.0 L200.2,119.3 L201.1,118.7 L201.9,118.0 L202.8,117.3 L203.6,116.7 L204.5,116.0 L205.3,115.3 L206.2,114.7 L207.0,114.0 L207.9,113.3 L208.7,112.7 L209.6,112.0 L210.4,111.3 L211.3,110.7 L212.1,110.0 L213.0,109.3 L213.8,108.7 L214.7,108.0 L215.5,107.3 L216.4,106.7 L217.2,106.0 L218.1,105.3 L218.9,104.7 L219.8,104.0 L220.6,103.3 L221.5,102.7 L222.3,102.0 L223.2,101.3 L224.0,100.7 L224.8,100.0 L225.7,99.3 L226.5,98.7 L227.4,98.0 L228.2,97.3 L229.1,96.7 L229.9,96.0 L230.8,95.3 L231.6,94.7 L232.5,94.0 L233.3,93.3 L234.2,92.7 L235.0,92.0 L235.9,91.3 L236.7,90.7 L237.6,90.0 L238.4,89.3 L239.3,88.7 L240.1,88.0 L241.0,87.3 L241.8,86.7 L242.7,86.0 L243.5,85.3 L244.4,84.7 L245.2,84.0 L246.1,83.3 L246.9,82.7 L247.8,82.0 L248.6,81.3 L249.5,80.7 L250.3,80.0 L251.2,79.3 L252.0,78.7 L252.9,78.0 L253.7,77.3 L254.6,76.7 L255.4,76.0 L256.3,75.3 L257.1,74.7 L258.0,74.0 L258.8,73.3 L259.7,72.7 L260.5,72.0 L261.4,71.3 L262.2,70.7 L263.1,70.0 L263.9,69.3 L264.8,68.7 L265.6,68.0 L266.5,67.3 L267.3,66.7 L268.2,66.0 L269.0,65.3 L269.8,64.7 L270.7,64.0 L271.5,63.3 L272.4,62.7 L273.2,62.0 L274.1,61.3 L274.9,60.7 L275.8,60.0 L276.6,59.3 L277.5,58.7 L278.3,58.0 L279.2,57.3 L280.0,56.7 L280.9,56.0 L281.7,55.3 L282.6,54.7 L283.4,54.0 L284.3,53.3 L285.1,52.7 L286.0,52.0 L286.8,51.3 L287.7,50.7 L288.5,50.0 L289.4,49.3 L290.2,48.7 L291.1,48.0 L291.9,47.3 L292.8,46.7 L293.6,46.0 L294.5,45.3 L295.3,44.7 L296.2,44.0 L297.0,43.3 L297.9,42.7 L298.7,42.0" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,242.0 L44.8,242.0 L45.7,242.0 L46.5,242.0 L47.4,242.0 L48.2,241.9 L49.1,241.9 L49.9,241.9 L50.8,241.9 L51.6,241.8 L52.5,241.8 L53.3,241.7 L54.2,241.7 L55.0,241.6 L55.9,241.6 L56.7,241.5 L57.6,241.4 L58.4,241.4 L59.3,241.3 L60.1,241.2 L61.0,241.1 L61.8,241.0 L62.7,240.9 L63.5,240.8 L64.4,240.7 L65.2,240.6 L66.1,240.5 L66.9,240.4 L67.8,240.3 L68.6,240.1 L69.5,240.0 L70.3,239.9 L71.2,239.7 L72.0,239.6 L72.9,239.4 L73.7,239.3 L74.6,239.1 L75.4,239.0 L76.3,238.8 L77.1,238.6 L78.0,238.4 L78.8,238.3 L79.7,238.1 L80.5,237.9 L81.4,237.7 L82.2,237.5 L83.1,237.3 L83.9,237.1 L84.8,236.9 L85.6,236.7 L86.5,236.4 L87.3,236.2 L88.2,236.0 L89.0,235.8 L89.8,235.5 L90.7,235.3 L91.5,235.0 L92.4,234.8 L93.2,234.5 L94.1,234.3 L94.9,234.0 L95.8,233.7 L96.6,233.5 L97.5,233.2 L98.3,232.9 L99.2,232.6 L100.0,232.3 L100.9,232.0 L101.7,231.7 L102.6,231.4 L103.4,231.1 L104.3,230.8 L105.1,230.5 L106.0,230.2 L106.8,229.8 L107.7,229.5 L108.5,229.2 L109.4,228.8 L110.2,228.5 L111.1,228.1 L111.9,227.8 L112.8,227.4 L113.6,227.1 L114.5,226.7 L115.3,226.3 L116.2,225.9 L117.0,225.6 L117.9,225.2 L118.7,224.8 L119.6,224.4 L120.4,224.0 L121.3,223.6 L122.1,223.2 L123.0,222.8 L123.8,222.4 L124.7,221.9 L125.5,221.5 L126.4,221.1 L127.2,220.7 L128.1,220.2 L128.9,219.8 L129.8,219.3 L130.6,218.9 L131.5,218.4 L132.3,218.0 L133.2,217.5 L134.0,217.0 L134.8,216.6 L135.7,216.1 L136.5,215.6 L137.4,215.1 L138.2,214.6 L139.1,214.1 L139.9,213.6 L140.8,213.1 L141.6,212.6 L142.5,212.1 L143.3,211.6 L144.2,211.1 L145.0,210.5 L145.9,210.0 L146.7,209.5 L147.6,208.9 L148.4,208.4 L149.3,207.8 L150.1,207.3 L151.0,206.7 L151.8,206.2 L152.7,205.6 L153.5,205.0 L154.4,204.4 L155.2,203.9 L156.1,203.3 L156.9,202.7 L157.8,202.1 L158.6,201.5 L159.5,200.9 L160.3,200.3 L161.2,199.7 L162.0,199.1 L162.9,198.4 L163.7,197.8 L164.6,197.2 L165.4,196.6 L166.3,195.9 L167.1,195.3 L168.0,194.6 L168.8,194.0 L169.7,193.3 L170.5,192.7 L171.4,192.0 L172.2,191.3 L173.1,190.7 L173.9,190.0 L174.8,189.3 L175.6,188.6 L176.5,187.9 L177.3,187.2 L178.2,186.5 L179.0,185.8 L179.8,185.1 L180.7,184.4 L181.5,183.7 L182.4,183.0 L183.2,182.2 L184.1,181.5 L184.9,180.8 L185.8,180.0 L186.6,179.3 L187.5,178.5 L188.3,177.8 L189.2,177.0 L190.0,176.3 L190.9,175.5 L191.7,174.7 L192.6,173.9 L193.4,173.2 L194.3,172.4 L195.1,171.6 L196.0,170.8 L196.8,170.0 L197.7,169.2 L198.5,168.4 L199.4,167.6 L200.2,166.8 L201.1,165.9 L201.9,165.1 L202.8,164.3 L203.6,163.5 L204.5,162.6 L205.3,161.8 L206.2,160.9 L207.0,160.1 L207.9,159.2 L208.7,158.4 L209.6,157.5 L210.4,156.6 L211.3,155.8 L212.1,154.9 L213.0,154.0 L213.8,153.1 L214.7,152.2 L215.5,151.3 L216.4,150.4 L217.2,149.5 L218.1,148.6 L218.9,147.7 L219.8,146.8 L220.6,145.9 L221.5,144.9 L222.3,144.0 L223.2,143.1 L224.0,142.1 L224.8,141.2 L225.7,140.2 L226.5,139.3 L227.4,138.3 L228.2,137.4 L229.1,136.4 L229.9,135.4 L230.8,134.4 L231.6,133.5 L232.5,132.5 L233.3,131.5 L234.2,130.5 L235.0,129.5 L235.9,128.5 L236.7,127.5 L237.6,126.5 L238.4,125.5 L239.3,124.4 L240.1,123.4 L241.0,122.4 L241.8,121.4 L242.7,120.3 L243.5,119.3 L244.4,118.2 L245.2,117.2 L246.1,116.1 L246.9,115.1 L247.8,114.0 L248.6,112.9 L249.5,111.9 L250.3,110.8 L251.2,109.7 L252.0,108.6 L252.9,107.5 L253.7,106.4 L254.6,105.3 L255.4,104.2 L256.3,103.1 L257.1,102.0 L258.0,100.9 L258.8,99.8 L259.7,98.6 L260.5,97.5 L261.4,96.4 L262.2,95.2 L263.1,94.1 L263.9,92.9 L264.8,91.8 L265.6,90.6 L266.5,89.5 L267.3,88.3 L268.2,87.1 L269.0,85.9 L269.8,84.8 L270.7,83.6 L271.5,82.4 L272.4,81.2 L273.2,80.0 L274.1,78.8 L274.9,77.6 L275.8,76.4 L276.6,75.2 L277.5,73.9 L278.3,72.7 L279.2,71.5 L280.0,70.3 L280.9,69.0 L281.7,67.8 L282.6,66.5 L283.4,65.3 L284.3,64.0 L285.1,62.8 L286.0,61.5 L286.8,60.2 L287.7,59.0 L288.5,57.7 L289.4,56.4 L290.2,55.1 L291.1,53.8 L291.9,52.5 L292.8,51.2 L293.6,49.9 L294.5,48.6 L295.3,47.3 L296.2,46.0 L297.0,44.7 L297.9,43.3 L298.7,42.0" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.85" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,242.0 L44.8,242.0 L45.7,242.0 L46.5,242.0 L47.4,242.0 L48.2,242.0 L49.1,242.0 L49.9,242.0 L50.8,242.0 L51.6,242.0 L52.5,242.0 L53.3,242.0 L54.2,242.0 L55.0,242.0 L55.9,242.0 L56.7,242.0 L57.6,242.0 L58.4,242.0 L59.3,242.0 L60.1,241.9 L61.0,241.9 L61.8,241.9 L62.7,241.9 L63.5,241.9 L64.4,241.9 L65.2,241.9 L66.1,241.9 L66.9,241.9 L67.8,241.8 L68.6,241.8 L69.5,241.8 L70.3,241.8 L71.2,241.8 L72.0,241.7 L72.9,241.7 L73.7,241.7 L74.6,241.7 L75.4,241.6 L76.3,241.6 L77.1,241.6 L78.0,241.5 L78.8,241.5 L79.7,241.5 L80.5,241.4 L81.4,241.4 L82.2,241.3 L83.1,241.3 L83.9,241.2 L84.8,241.2 L85.6,241.1 L86.5,241.1 L87.3,241.0 L88.2,241.0 L89.0,240.9 L89.8,240.8 L90.7,240.8 L91.5,240.7 L92.4,240.6 L93.2,240.6 L94.1,240.5 L94.9,240.4 L95.8,240.3 L96.6,240.2 L97.5,240.1 L98.3,240.1 L99.2,240.0 L100.0,239.9 L100.9,239.8 L101.7,239.7 L102.6,239.6 L103.4,239.5 L104.3,239.3 L105.1,239.2 L106.0,239.1 L106.8,239.0 L107.7,238.9 L108.5,238.7 L109.4,238.6 L110.2,238.5 L111.1,238.3 L111.9,238.2 L112.8,238.1 L113.6,237.9 L114.5,237.8 L115.3,237.6 L116.2,237.5 L117.0,237.3 L117.9,237.1 L118.7,237.0 L119.6,236.8 L120.4,236.6 L121.3,236.4 L122.1,236.2 L123.0,236.0 L123.8,235.8 L124.7,235.6 L125.5,235.4 L126.4,235.2 L127.2,235.0 L128.1,234.8 L128.9,234.6 L129.8,234.4 L130.6,234.1 L131.5,233.9 L132.3,233.7 L133.2,233.4 L134.0,233.2 L134.8,232.9 L135.7,232.7 L136.5,232.4 L137.4,232.1 L138.2,231.9 L139.1,231.6 L139.9,231.3 L140.8,231.0 L141.6,230.7 L142.5,230.4 L143.3,230.1 L144.2,229.8 L145.0,229.5 L145.9,229.2 L146.7,228.9 L147.6,228.5 L148.4,228.2 L149.3,227.9 L150.1,227.5 L151.0,227.2 L151.8,226.8 L152.7,226.5 L153.5,226.1 L154.4,225.7 L155.2,225.3 L156.1,225.0 L156.9,224.6 L157.8,224.2 L158.6,223.8 L159.5,223.4 L160.3,223.0 L161.2,222.5 L162.0,222.1 L162.9,221.7 L163.7,221.2 L164.6,220.8 L165.4,220.3 L166.3,219.9 L167.1,219.4 L168.0,218.9 L168.8,218.5 L169.7,218.0 L170.5,217.5 L171.4,217.0 L172.2,216.5 L173.1,216.0 L173.9,215.5 L174.8,214.9 L175.6,214.4 L176.5,213.9 L177.3,213.3 L178.2,212.8 L179.0,212.2 L179.8,211.7 L180.7,211.1 L181.5,210.5 L182.4,209.9 L183.2,209.3 L184.1,208.7 L184.9,208.1 L185.8,207.5 L186.6,206.9 L187.5,206.2 L188.3,205.6 L189.2,205.0 L190.0,204.3 L190.9,203.6 L191.7,203.0 L192.6,202.3 L193.4,201.6 L194.3,200.9 L195.1,200.2 L196.0,199.5 L196.8,198.8 L197.7,198.1 L198.5,197.3 L199.4,196.6 L200.2,195.9 L201.1,195.1 L201.9,194.3 L202.8,193.6 L203.6,192.8 L204.5,192.0 L205.3,191.2 L206.2,190.4 L207.0,189.6 L207.9,188.7 L208.7,187.9 L209.6,187.1 L210.4,186.2 L211.3,185.4 L212.1,184.5 L213.0,183.6 L213.8,182.7 L214.7,181.8 L215.5,180.9 L216.4,180.0 L217.2,179.1 L218.1,178.2 L218.9,177.2 L219.8,176.3 L220.6,175.3 L221.5,174.4 L222.3,173.4 L223.2,172.4 L224.0,171.4 L224.8,170.4 L225.7,169.4 L226.5,168.4 L227.4,167.4 L228.2,166.3 L229.1,165.3 L229.9,164.2 L230.8,163.1 L231.6,162.0 L232.5,161.0 L233.3,159.9 L234.2,158.7 L235.0,157.6 L235.9,156.5 L236.7,155.4 L237.6,154.2 L238.4,153.0 L239.3,151.9 L240.1,150.7 L241.0,149.5 L241.8,148.3 L242.7,147.1 L243.5,145.9 L244.4,144.6 L245.2,143.4 L246.1,142.1 L246.9,140.9 L247.8,139.6 L248.6,138.3 L249.5,137.0 L250.3,135.7 L251.2,134.4 L252.0,133.1 L252.9,131.7 L253.7,130.4 L254.6,129.0 L255.4,127.6 L256.3,126.3 L257.1,124.9 L258.0,123.5 L258.8,122.0 L259.7,120.6 L260.5,119.2 L261.4,117.7 L262.2,116.3 L263.1,114.8 L263.9,113.3 L264.8,111.8 L265.6,110.3 L266.5,108.8 L267.3,107.2 L268.2,105.7 L269.0,104.2 L269.8,102.6 L270.7,101.0 L271.5,99.4 L272.4,97.8 L273.2,96.2 L274.1,94.6 L274.9,92.9 L275.8,91.3 L276.6,89.6 L277.5,87.9 L278.3,86.3 L279.2,84.6 L280.0,82.9 L280.9,81.1 L281.7,79.4 L282.6,77.6 L283.4,75.9 L284.3,74.1 L285.1,72.3 L286.0,70.5 L286.8,68.7 L287.7,66.9 L288.5,65.1 L289.4,63.2 L290.2,61.3 L291.1,59.5 L291.9,57.6 L292.8,55.7 L293.6,53.8 L294.5,51.8 L295.3,49.9 L296.2,47.9 L297.0,46.0 L297.9,44.0 L298.7,42.0" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.72" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,242.0 L44.8,242.0 L45.7,242.0 L46.5,242.0 L47.4,242.0 L48.2,242.0 L49.1,242.0 L49.9,242.0 L50.8,242.0 L51.6,242.0 L52.5,242.0 L53.3,242.0 L54.2,242.0 L55.0,242.0 L55.9,242.0 L56.7,242.0 L57.6,242.0 L58.4,242.0 L59.3,242.0 L60.1,242.0 L61.0,242.0 L61.8,242.0 L62.7,242.0 L63.5,242.0 L64.4,242.0 L65.2,242.0 L66.1,242.0 L66.9,242.0 L67.8,242.0 L68.6,242.0 L69.5,242.0 L70.3,242.0 L71.2,242.0 L72.0,242.0 L72.9,242.0 L73.7,242.0 L74.6,242.0 L75.4,242.0 L76.3,242.0 L77.1,242.0 L78.0,242.0 L78.8,242.0 L79.7,242.0 L80.5,242.0 L81.4,242.0 L82.2,242.0 L83.1,242.0 L83.9,242.0 L84.8,242.0 L85.6,242.0 L86.5,242.0 L87.3,242.0 L88.2,242.0 L89.0,242.0 L89.8,242.0 L90.7,242.0 L91.5,242.0 L92.4,242.0 L93.2,241.9 L94.1,241.9 L94.9,241.9 L95.8,241.9 L96.6,241.9 L97.5,241.9 L98.3,241.9 L99.2,241.9 L100.0,241.9 L100.9,241.9 L101.7,241.9 L102.6,241.9 L103.4,241.9 L104.3,241.9 L105.1,241.8 L106.0,241.8 L106.8,241.8 L107.7,241.8 L108.5,241.8 L109.4,241.8 L110.2,241.8 L111.1,241.7 L111.9,241.7 L112.8,241.7 L113.6,241.7 L114.5,241.7 L115.3,241.7 L116.2,241.6 L117.0,241.6 L117.9,241.6 L118.7,241.6 L119.6,241.5 L120.4,241.5 L121.3,241.5 L122.1,241.5 L123.0,241.4 L123.8,241.4 L124.7,241.4 L125.5,241.3 L126.4,241.3 L127.2,241.3 L128.1,241.2 L128.9,241.2 L129.8,241.1 L130.6,241.1 L131.5,241.0 L132.3,241.0 L133.2,240.9 L134.0,240.9 L134.8,240.8 L135.7,240.8 L136.5,240.7 L137.4,240.7 L138.2,240.6 L139.1,240.5 L139.9,240.5 L140.8,240.4 L141.6,240.3 L142.5,240.3 L143.3,240.2 L144.2,240.1 L145.0,240.0 L145.9,240.0 L146.7,239.9 L147.6,239.8 L148.4,239.7 L149.3,239.6 L150.1,239.5 L151.0,239.4 L151.8,239.3 L152.7,239.2 L153.5,239.1 L154.4,238.9 L155.2,238.8 L156.1,238.7 L156.9,238.6 L157.8,238.4 L158.6,238.3 L159.5,238.2 L160.3,238.0 L161.2,237.9 L162.0,237.7 L162.9,237.6 L163.7,237.4 L164.6,237.2 L165.4,237.1 L166.3,236.9 L167.1,236.7 L168.0,236.5 L168.8,236.4 L169.7,236.2 L170.5,236.0 L171.4,235.8 L172.2,235.5 L173.1,235.3 L173.9,235.1 L174.8,234.9 L175.6,234.6 L176.5,234.4 L177.3,234.1 L178.2,233.9 L179.0,233.6 L179.8,233.4 L180.7,233.1 L181.5,232.8 L182.4,232.5 L183.2,232.2 L184.1,231.9 L184.9,231.6 L185.8,231.3 L186.6,231.0 L187.5,230.7 L188.3,230.3 L189.2,230.0 L190.0,229.6 L190.9,229.2 L191.7,228.9 L192.6,228.5 L193.4,228.1 L194.3,227.7 L195.1,227.3 L196.0,226.9 L196.8,226.4 L197.7,226.0 L198.5,225.6 L199.4,225.1 L200.2,224.6 L201.1,224.2 L201.9,223.7 L202.8,223.2 L203.6,222.7 L204.5,222.2 L205.3,221.6 L206.2,221.1 L207.0,220.5 L207.9,220.0 L208.7,219.4 L209.6,218.8 L210.4,218.2 L211.3,217.6 L212.1,217.0 L213.0,216.3 L213.8,215.7 L214.7,215.0 L215.5,214.3 L216.4,213.6 L217.2,212.9 L218.1,212.2 L218.9,211.5 L219.8,210.7 L220.6,210.0 L221.5,209.2 L222.3,208.4 L223.2,207.6 L224.0,206.8 L224.8,205.9 L225.7,205.1 L226.5,204.2 L227.4,203.3 L228.2,202.4 L229.1,201.5 L229.9,200.5 L230.8,199.6 L231.6,198.6 L232.5,197.6 L233.3,196.6 L234.2,195.6 L235.0,194.5 L235.9,193.5 L236.7,192.4 L237.6,191.3 L238.4,190.2 L239.3,189.0 L240.1,187.9 L241.0,186.7 L241.8,185.5 L242.7,184.3 L243.5,183.0 L244.4,181.7 L245.2,180.5 L246.1,179.1 L246.9,177.8 L247.8,176.5 L248.6,175.1 L249.5,173.7 L250.3,172.3 L251.2,170.8 L252.0,169.3 L252.9,167.9 L253.7,166.3 L254.6,164.8 L255.4,163.2 L256.3,161.6 L257.1,160.0 L258.0,158.4 L258.8,156.7 L259.7,155.0 L260.5,153.3 L261.4,151.5 L262.2,149.7 L263.1,147.9 L263.9,146.1 L264.8,144.2 L265.6,142.3 L266.5,140.4 L267.3,138.4 L268.2,136.5 L269.0,134.4 L269.8,132.4 L270.7,130.3 L271.5,128.2 L272.4,126.1 L273.2,123.9 L274.1,121.7 L274.9,119.5 L275.8,117.2 L276.6,114.9 L277.5,112.6 L278.3,110.2 L279.2,107.8 L280.0,105.3 L280.9,102.9 L281.7,100.4 L282.6,97.8 L283.4,95.2 L284.3,92.6 L285.1,89.9 L286.0,87.2 L286.8,84.5 L287.7,81.7 L288.5,78.9 L289.4,76.1 L290.2,73.2 L291.1,70.3 L291.9,67.3 L292.8,64.3 L293.6,61.2 L294.5,58.1 L295.3,55.0 L296.2,51.8 L297.0,48.6 L297.9,45.3 L298.7,42.0" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.6" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,242.0 L44.8,242.0 L45.7,242.0 L46.5,242.0 L47.4,242.0 L48.2,242.0 L49.1,242.0 L49.9,242.0 L50.8,242.0 L51.6,242.0 L52.5,242.0 L53.3,242.0 L54.2,242.0 L55.0,242.0 L55.9,242.0 L56.7,242.0 L57.6,242.0 L58.4,242.0 L59.3,242.0 L60.1,242.0 L61.0,242.0 L61.8,242.0 L62.7,242.0 L63.5,242.0 L64.4,242.0 L65.2,242.0 L66.1,242.0 L66.9,242.0 L67.8,242.0 L68.6,242.0 L69.5,242.0 L70.3,242.0 L71.2,242.0 L72.0,242.0 L72.9,242.0 L73.7,242.0 L74.6,242.0 L75.4,242.0 L76.3,242.0 L77.1,242.0 L78.0,242.0 L78.8,242.0 L79.7,242.0 L80.5,242.0 L81.4,242.0 L82.2,242.0 L83.1,242.0 L83.9,242.0 L84.8,242.0 L85.6,242.0 L86.5,242.0 L87.3,242.0 L88.2,242.0 L89.0,242.0 L89.8,242.0 L90.7,242.0 L91.5,242.0 L92.4,242.0 L93.2,242.0 L94.1,242.0 L94.9,242.0 L95.8,242.0 L96.6,242.0 L97.5,242.0 L98.3,242.0 L99.2,242.0 L100.0,242.0 L100.9,242.0 L101.7,242.0 L102.6,242.0 L103.4,242.0 L104.3,242.0 L105.1,242.0 L106.0,242.0 L106.8,242.0 L107.7,242.0 L108.5,242.0 L109.4,242.0 L110.2,242.0 L111.1,242.0 L111.9,242.0 L112.8,242.0 L113.6,242.0 L114.5,242.0 L115.3,242.0 L116.2,242.0 L117.0,242.0 L117.9,242.0 L118.7,242.0 L119.6,242.0 L120.4,242.0 L121.3,242.0 L122.1,242.0 L123.0,242.0 L123.8,242.0 L124.7,242.0 L125.5,242.0 L126.4,242.0 L127.2,242.0 L128.1,242.0 L128.9,242.0 L129.8,242.0 L130.6,242.0 L131.5,242.0 L132.3,242.0 L133.2,242.0 L134.0,242.0 L134.8,242.0 L135.7,242.0 L136.5,242.0 L137.4,242.0 L138.2,242.0 L139.1,242.0 L139.9,242.0 L140.8,242.0 L141.6,242.0 L142.5,242.0 L143.3,242.0 L144.2,242.0 L145.0,242.0 L145.9,242.0 L146.7,242.0 L147.6,242.0 L148.4,242.0 L149.3,242.0 L150.1,242.0 L151.0,242.0 L151.8,242.0 L152.7,242.0 L153.5,242.0 L154.4,242.0 L155.2,241.9 L156.1,241.9 L156.9,241.9 L157.8,241.9 L158.6,241.9 L159.5,241.9 L160.3,241.9 L161.2,241.9 L162.0,241.9 L162.9,241.9 L163.7,241.9 L164.6,241.9 L165.4,241.9 L166.3,241.9 L167.1,241.9 L168.0,241.9 L168.8,241.8 L169.7,241.8 L170.5,241.8 L171.4,241.8 L172.2,241.8 L173.1,241.8 L173.9,241.8 L174.8,241.7 L175.6,241.7 L176.5,241.7 L177.3,241.7 L178.2,241.7 L179.0,241.7 L179.8,241.6 L180.7,241.6 L181.5,241.6 L182.4,241.6 L183.2,241.5 L184.1,241.5 L184.9,241.5 L185.8,241.4 L186.6,241.4 L187.5,241.4 L188.3,241.3 L189.2,241.3 L190.0,241.2 L190.9,241.2 L191.7,241.1 L192.6,241.1 L193.4,241.0 L194.3,241.0 L195.1,240.9 L196.0,240.9 L196.8,240.8 L197.7,240.7 L198.5,240.6 L199.4,240.6 L200.2,240.5 L201.1,240.4 L201.9,240.3 L202.8,240.2 L203.6,240.1 L204.5,240.0 L205.3,239.9 L206.2,239.8 L207.0,239.7 L207.9,239.6 L208.7,239.4 L209.6,239.3 L210.4,239.2 L211.3,239.0 L212.1,238.9 L213.0,238.7 L213.8,238.5 L214.7,238.4 L215.5,238.2 L216.4,238.0 L217.2,237.8 L218.1,237.6 L218.9,237.3 L219.8,237.1 L220.6,236.9 L221.5,236.6 L222.3,236.4 L223.2,236.1 L224.0,235.8 L224.8,235.5 L225.7,235.2 L226.5,234.9 L227.4,234.5 L228.2,234.2 L229.1,233.8 L229.9,233.4 L230.8,233.0 L231.6,232.6 L232.5,232.2 L233.3,231.7 L234.2,231.2 L235.0,230.7 L235.9,230.2 L236.7,229.7 L237.6,229.1 L238.4,228.6 L239.3,228.0 L240.1,227.3 L241.0,226.7 L241.8,226.0 L242.7,225.3 L243.5,224.6 L244.4,223.8 L245.2,223.1 L246.1,222.2 L246.9,221.4 L247.8,220.5 L248.6,219.6 L249.5,218.7 L250.3,217.7 L251.2,216.7 L252.0,215.6 L252.9,214.5 L253.7,213.4 L254.6,212.2 L255.4,211.0 L256.3,209.7 L257.1,208.4 L258.0,207.0 L258.8,205.6 L259.7,204.1 L260.5,202.6 L261.4,201.1 L262.2,199.4 L263.1,197.7 L263.9,196.0 L264.8,194.2 L265.6,192.3 L266.5,190.4 L267.3,188.4 L268.2,186.3 L269.0,184.2 L269.8,181.9 L270.7,179.6 L271.5,177.3 L272.4,174.8 L273.2,172.3 L274.1,169.6 L274.9,166.9 L275.8,164.1 L276.6,161.2 L277.5,158.2 L278.3,155.1 L279.2,151.9 L280.0,148.6 L280.9,145.2 L281.7,141.7 L282.6,138.0 L283.4,134.3 L284.3,130.4 L285.1,126.4 L286.0,122.3 L286.8,118.0 L287.7,113.6 L288.5,109.0 L289.4,104.3 L290.2,99.5 L291.1,94.5 L291.9,89.4 L292.8,84.1 L293.6,78.6 L294.5,72.9 L295.3,67.1 L296.2,61.1 L297.0,54.9 L297.9,48.6 L298.7,42.0" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.5" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,242.0 L44.8,242.0 L45.7,242.0 L46.5,242.0 L47.4,242.0 L48.2,242.0 L49.1,242.0 L49.9,242.0 L50.8,242.0 L51.6,242.0 L52.5,242.0 L53.3,242.0 L54.2,242.0 L55.0,242.0 L55.9,242.0 L56.7,242.0 L57.6,242.0 L58.4,242.0 L59.3,242.0 L60.1,242.0 L61.0,242.0 L61.8,242.0 L62.7,242.0 L63.5,242.0 L64.4,242.0 L65.2,242.0 L66.1,242.0 L66.9,242.0 L67.8,242.0 L68.6,242.0 L69.5,242.0 L70.3,242.0 L71.2,242.0 L72.0,242.0 L72.9,242.0 L73.7,242.0 L74.6,242.0 L75.4,242.0 L76.3,242.0 L77.1,242.0 L78.0,242.0 L78.8,242.0 L79.7,242.0 L80.5,242.0 L81.4,242.0 L82.2,242.0 L83.1,242.0 L83.9,242.0 L84.8,242.0 L85.6,242.0 L86.5,242.0 L87.3,242.0 L88.2,242.0 L89.0,242.0 L89.8,242.0 L90.7,242.0 L91.5,242.0 L92.4,242.0 L93.2,242.0 L94.1,242.0 L94.9,242.0 L95.8,242.0 L96.6,242.0 L97.5,242.0 L98.3,242.0 L99.2,242.0 L100.0,242.0 L100.9,242.0 L101.7,242.0 L102.6,242.0 L103.4,242.0 L104.3,242.0 L105.1,242.0 L106.0,242.0 L106.8,242.0 L107.7,242.0 L108.5,242.0 L109.4,242.0 L110.2,242.0 L111.1,242.0 L111.9,242.0 L112.8,242.0 L113.6,242.0 L114.5,242.0 L115.3,242.0 L116.2,242.0 L117.0,242.0 L117.9,242.0 L118.7,242.0 L119.6,242.0 L120.4,242.0 L121.3,242.0 L122.1,242.0 L123.0,242.0 L123.8,242.0 L124.7,242.0 L125.5,242.0 L126.4,242.0 L127.2,242.0 L128.1,242.0 L128.9,242.0 L129.8,242.0 L130.6,242.0 L131.5,242.0 L132.3,242.0 L133.2,242.0 L134.0,242.0 L134.8,242.0 L135.7,242.0 L136.5,242.0 L137.4,242.0 L138.2,242.0 L139.1,242.0 L139.9,242.0 L140.8,242.0 L141.6,242.0 L142.5,242.0 L143.3,242.0 L144.2,242.0 L145.0,242.0 L145.9,242.0 L146.7,242.0 L147.6,242.0 L148.4,242.0 L149.3,242.0 L150.1,242.0 L151.0,242.0 L151.8,242.0 L152.7,242.0 L153.5,242.0 L154.4,242.0 L155.2,242.0 L156.1,242.0 L156.9,242.0 L157.8,242.0 L158.6,242.0 L159.5,242.0 L160.3,242.0 L161.2,242.0 L162.0,242.0 L162.9,242.0 L163.7,242.0 L164.6,242.0 L165.4,242.0 L166.3,242.0 L167.1,242.0 L168.0,242.0 L168.8,242.0 L169.7,242.0 L170.5,242.0 L171.4,242.0 L172.2,242.0 L173.1,242.0 L173.9,242.0 L174.8,242.0 L175.6,242.0 L176.5,242.0 L177.3,242.0 L178.2,242.0 L179.0,242.0 L179.8,242.0 L180.7,242.0 L181.5,242.0 L182.4,242.0 L183.2,242.0 L184.1,242.0 L184.9,242.0 L185.8,242.0 L186.6,242.0 L187.5,242.0 L188.3,242.0 L189.2,242.0 L190.0,242.0 L190.9,242.0 L191.7,242.0 L192.6,242.0 L193.4,242.0 L194.3,242.0 L195.1,242.0 L196.0,242.0 L196.8,242.0 L197.7,242.0 L198.5,242.0 L199.4,242.0 L200.2,242.0 L201.1,242.0 L201.9,242.0 L202.8,242.0 L203.6,242.0 L204.5,242.0 L205.3,242.0 L206.2,242.0 L207.0,242.0 L207.9,242.0 L208.7,242.0 L209.6,242.0 L210.4,242.0 L211.3,242.0 L212.1,242.0 L213.0,242.0 L213.8,242.0 L214.7,242.0 L215.5,242.0 L216.4,242.0 L217.2,242.0 L218.1,242.0 L218.9,242.0 L219.8,242.0 L220.6,242.0 L221.5,242.0 L222.3,242.0 L223.2,242.0 L224.0,242.0 L224.8,242.0 L225.7,242.0 L226.5,242.0 L227.4,242.0 L228.2,242.0 L229.1,242.0 L229.9,242.0 L230.8,242.0 L231.6,242.0 L232.5,242.0 L233.3,242.0 L234.2,242.0 L235.0,242.0 L235.9,242.0 L236.7,242.0 L237.6,241.9 L238.4,241.9 L239.3,241.9 L240.1,241.9 L241.0,241.9 L241.8,241.9 L242.7,241.9 L243.5,241.9 L244.4,241.9 L245.2,241.8 L246.1,241.8 L246.9,241.8 L247.8,241.8 L248.6,241.7 L249.5,241.7 L250.3,241.6 L251.2,241.6 L252.0,241.5 L252.9,241.5 L253.7,241.4 L254.6,241.3 L255.4,241.3 L256.3,241.2 L257.1,241.1 L258.0,240.9 L258.8,240.8 L259.7,240.6 L260.5,240.5 L261.4,240.3 L262.2,240.1 L263.1,239.8 L263.9,239.6 L264.8,239.3 L265.6,238.9 L266.5,238.6 L267.3,238.1 L268.2,237.7 L269.0,237.2 L269.8,236.6 L270.7,235.9 L271.5,235.2 L272.4,234.4 L273.2,233.5 L274.1,232.5 L274.9,231.4 L275.8,230.2 L276.6,228.8 L277.5,227.3 L278.3,225.6 L279.2,223.7 L280.0,221.6 L280.9,219.3 L281.7,216.8 L282.6,213.9 L283.4,210.7 L284.3,207.2 L285.1,203.4 L286.0,199.1 L286.8,194.3 L287.7,189.1 L288.5,183.2 L289.4,176.8 L290.2,169.7 L291.1,161.8 L291.9,153.1 L292.8,143.5 L293.6,132.9 L294.5,121.2 L295.3,108.3 L296.2,94.1 L297.0,78.4 L297.9,61.1 L298.7,42.0" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.42" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,242.0 L298.7,242.0" fill="none" stroke="var(--color-practice)" stroke-width="2.6" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="298.7" cy="242.0" r="3.6" fill="var(--academic-bg)" stroke="var(--color-practice)" stroke-width="1.6"/>
  <circle cx="298.7" cy="42.0" r="3.8" fill="var(--color-practice)"/>
  <text x="163.4" y="136.0" fill="var(--color-theory)" font-size="10.5" text-anchor="end" font-style="italic">n = 1</text>
  <text x="306.7" y="182.0" fill="var(--color-theory)" font-size="10.5" text-anchor="start" font-style="italic">n = 30</text>
  <text x="100.0" y="258.0" fill="var(--color-practice)" font-size="10.5" text-anchor="middle" font-style="italic">noktasal limit</text>
</svg>
<figcaption><em>f<sub>n</sub></em>(<em>x</em>) = <em>x<sup>n</sup></em> dizisinin <em>n</em> = 1, 2, 3, 5, 10, 30 terimleri. [0, 1) üzerinde eğriler yatay eksene çöker; (1, 1) noktası ise yerinde kalır. Noktasal limit <em>x</em> = 1'de sıçrar.</figcaption>
</figure>
```

Şekilde $n$ büyüdükçe grafiklerin $[0, 1)$ üzerinde yatay eksene doğru çöktüğü, ama $(1, 1)$ noktasının hiç kıpırdamadığı görülür.

## Noktasal Yakınsaklık

Her noktada ayrı ayrı limit alma fikrini tanıma dökelim.

::: {#def-nok-noktasal-yakinsaklik name="Noktasal Yakınsaklık ve Noktasal Limit"}
$(f_n)$, $E \subseteq \mathbb{R}$ üzerinde tanımlı bir fonksiyon dizisi ve $f : E \to \mathbb{R}$ bir fonksiyon olsun. Her $x \in E$ için

$$\lim_{n \to \infty} f_n(x) = f(x)$$

ise $(f_n)$ dizisi $E$ üzerinde $f$ fonksiyonuna **noktasal yakınsar** denir. $f$ fonksiyonuna $(f_n)$ dizisinin **noktasal limiti** denir ve

$$f_n \to f \quad (\text{noktasal},\ E)$$

yazılır. Açık yazımıyla: her $\varepsilon > 0$ ve her $x \in E$ için öyle bir $N = N(\varepsilon, x) \in \mathbb{N}$ vardır ki $n \ge N$ olan her $n$ için

$$|f_n(x) - f(x)| < \varepsilon$$

olur.
:::

Yani noktasal yakınsaklık, $E$'nin her noktasında ayrı bir sayı dizisi limiti almaktır; fazladan hiçbir şey istemez. Tanımdaki $N$ sayısının hem $\varepsilon$'a hem de $x$'e bağlı olduğuna dikkat edelim: aynı $\varepsilon$ için bir noktada $N = 5$ yeterken başka bir noktada $N = 5000$ gerekebilir. Bu bağımlılık, sonraki bölümde düzgün yakınsaklıkla noktasal yakınsaklığı ayıran tek şey olacaktır.

Bir sayı dizisinin limiti tek olduğundan (bkz. [Analiz 1](../analiz-1/dizilerde-yakinsaklik.html#thm-limit-tekligi)) noktasal limit de varsa tektir.

::: {#def-nok-iraksaklik name="Bir Noktada ve Bir Kümede Iraksaklık"}
$(f_n)$, $E$ üzerinde tanımlı bir fonksiyon dizisi ve $a \in E$ olsun. $\big(f_n(a)\big)$ sayı dizisi yakınsaksa $(f_n)$ dizisi **$a$ noktasında yakınsaktır**, ıraksaksa **$a$ noktasında ıraksaktır** denir. $(f_n)$ dizisi $E$'nin her noktasında ıraksaksa **$E$ üzerinde ıraksaktır** denir.
:::

Yani bir fonksiyon dizisi bazı noktalarda yakınsayıp bazılarında ıraksayabilir. $E$ üzerinde noktasal yakınsak olması için $E$'nin **her** noktasında yakınsaması gerekir; tek bir noktada ıraksaması noktasal yakınsaklığı bozar.

::: {.callout-tip title="Üç adımda noktasal limit"}
1. **Noktayı sabitle.** $x \in E$ bir sabit gibi düşünülür; değişken yalnız $n$'dir.
2. **Özel noktaları ayır.** Formülün davranışının değiştiği noktalar ($x = 0$, $x = 1$, payda sıfırları gibi) ayrı ayrı incelenir.
3. **Sayı dizisi limitini al.** Her durumda $\lim_{n \to \infty} f_n(x)$ hesaplanır; sonuçlar parçalı bir $f$ fonksiyonunda toplanır.
:::

:::: {#exm-nok-xn name="Kuvvet Dizisinin Noktasal Limiti"}
$E = [0, 1]$ üzerinde $f_n(x) = x^n$ ile tanımlı $(f_n)$ dizisinin noktasal limitini bulunuz ve $0 < x < 1$ için tanımdaki $N(\varepsilon, x)$ sayısını açıkça yazınız.

::: {.cozum}
Noktayı sabitleyip üç durumu ayıralım.

- $x = 0$ için her $n$'de $f_n(0) = 0$'dır; dolayısıyla $\lim_{n \to \infty} f_n(0) = 0$.
- $x = 1$ için her $n$'de $f_n(1) = 1^n = 1$'dir; dolayısıyla $\lim_{n \to \infty} f_n(1) = 1$.
- $0 < x < 1$ için $(x^n)$ ortak çarpanı $1$'den küçük bir geometrik dizidir ve $\lim_{n \to \infty} x^n = 0$'dır (bkz. [Analiz 1](../analiz-1/sonsuz-limitler-ve-ozel-limitler.html#thm-geometrik-dizi)).

Öyleyse dizi $[0, 1]$ üzerinde noktasal yakınsaktır ve noktasal limiti

$$f(x) = \begin{cases} 0, & 0 \le x < 1 \\ 1, & x = 1 \end{cases}$$

fonksiyonudur.

**$N$ sayısı.** $0 < x < 1$ ve $0 < \varepsilon < 1$ olsun. $|x^n - 0| = x^n < \varepsilon$ eşitsizliğinin iki yanının logaritmasını alalım: $n \ln x < \ln \varepsilon$. Burada $\ln x < 0$ olduğundan bölünce eşitsizlik yön değiştirir:

$$n > \frac{\ln \varepsilon}{\ln x}.$$

Dolayısıyla

$$N(\varepsilon, x) = \left\lfloor \frac{\ln \varepsilon}{\ln x} \right\rfloor + 1$$

seçilebilir: $n \ge N$ ise $n > \dfrac{\ln \varepsilon}{\ln x}$ ve buradan $x^n < \varepsilon$ olur. ($\varepsilon \ge 1$ ise her $n$ için $x^n < 1 \le \varepsilon$ olduğundan $N = 1$ yeter.)

Bu $N$ gerçekten $x$'e bağlıdır. Örneğin $\varepsilon = 0{,}01$ için $x = 0{,}5$ noktasında $N = 7$ yeterken $x = 0{,}99$ noktasında $N = 459$ gerekir. $x$ sayısı $1$'e yaklaştıkça $\ln x \to 0$ olur ve $N$ sınırsız büyür. [$\blacksquare$]{.qed}
:::
::::

:::: {#exm-nok-tepe name="Tepesi Sola Kayan Bir Dizi"}
$E = [0, 1]$ üzerinde $f_n(x) = \dfrac{2nx}{1 + n^2x^2}$ ile tanımlı $(f_n)$ dizisi noktasal yakınsak mıdır? Yakınsaksa limitini $\varepsilon$–$N$ tanımıyla doğrulayınız.

::: {.cozum}
```{=html}
<figure class="ders-grafik ders-grafik-dar">
<svg viewBox="8.0 -11.5 360.0 265.5" role="img" aria-label="Bumps of height one sliding to the left while the pointwise limit is zero">
  <g stroke="var(--academic-text)" stroke-width="1.1" opacity="0.45">
  <line x1="44.0" y1="222.0" x2="342.0" y2="222.0"/>
  <line x1="44.0" y1="14.0" x2="44.0" y2="222.0"/>
  </g>
  <g fill="var(--academic-text)" font-size="11" opacity="0.7">
  <text x="113.0" y="238.0" text-anchor="middle">0,25</text>
  <text x="182.1" y="238.0" text-anchor="middle">0,5</text>
  <text x="320.2" y="238.0" text-anchor="middle">1</text>
  <text x="37.0" y="141.3" text-anchor="end">0,5</text>
  <text x="37.0" y="56.5" text-anchor="end">1</text>
  <text x="348.0" y="226.0" font-style="italic">x</text>
  <text x="40.0" y="8.0" text-anchor="middle" font-style="italic">y</text>
  </g>
  <path d="M44.0,52.5 L320.2,52.5" fill="none" stroke="var(--academic-text)" stroke-width="1.0" stroke-dasharray="4 3" opacity="0.5" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,222.0 L44.6,221.3 L45.1,220.6 L45.7,220.0 L46.2,219.3 L46.8,218.6 L47.3,217.9 L47.9,217.3 L48.4,216.6 L49.0,215.9 L49.5,215.2 L50.1,214.5 L50.6,213.9 L51.2,213.2 L51.7,212.5 L52.3,211.8 L52.8,211.2 L53.4,210.5 L53.9,209.8 L54.5,209.1 L55.0,208.5 L55.6,207.8 L56.2,207.1 L56.7,206.4 L57.3,205.8 L57.8,205.1 L58.4,204.4 L58.9,203.7 L59.5,203.1 L60.0,202.4 L60.6,201.7 L61.1,201.1 L61.7,200.4 L62.2,199.7 L62.8,199.1 L63.3,198.4 L63.9,197.7 L64.4,197.1 L65.0,196.4 L65.5,195.7 L66.1,195.1 L66.6,194.4 L67.2,193.7 L67.8,193.1 L68.3,192.4 L68.9,191.7 L69.4,191.1 L70.0,190.4 L70.5,189.8 L71.1,189.1 L71.6,188.4 L72.2,187.8 L72.7,187.1 L73.3,186.5 L73.8,185.8 L74.4,185.2 L74.9,184.5 L75.5,183.9 L76.0,183.2 L76.6,182.5 L77.1,181.9 L77.7,181.3 L78.2,180.6 L78.8,180.0 L79.4,179.3 L79.9,178.7 L80.5,178.0 L81.0,177.4 L81.6,176.7 L82.1,176.1 L82.7,175.5 L83.2,174.8 L83.8,174.2 L84.3,173.5 L84.9,172.9 L85.4,172.3 L86.0,171.6 L86.5,171.0 L87.1,170.4 L87.6,169.7 L88.2,169.1 L88.7,168.5 L89.3,167.9 L89.8,167.2 L90.4,166.6 L91.0,166.0 L91.5,165.4 L92.1,164.8 L92.6,164.1 L93.2,163.5 L93.7,162.9 L94.3,162.3 L94.8,161.7 L95.4,161.1 L95.9,160.4 L96.5,159.8 L97.0,159.2 L97.6,158.6 L98.1,158.0 L98.7,157.4 L99.2,156.8 L99.8,156.2 L100.3,155.6 L100.9,155.0 L101.4,154.4 L102.0,153.8 L102.6,153.2 L103.1,152.6 L103.7,152.0 L104.2,151.5 L104.8,150.9 L105.3,150.3 L105.9,149.7 L106.4,149.1 L107.0,148.5 L107.5,148.0 L108.1,147.4 L108.6,146.8 L109.2,146.2 L109.7,145.6 L110.3,145.1 L110.8,144.5 L111.4,143.9 L111.9,143.4 L112.5,142.8 L113.0,142.2 L113.6,141.7 L114.2,141.1 L114.7,140.6 L115.3,140.0 L115.8,139.4 L116.4,138.9 L116.9,138.3 L117.5,137.8 L118.0,137.2 L118.6,136.7 L119.1,136.1 L119.7,135.6 L120.2,135.1 L120.8,134.5 L121.3,134.0 L121.9,133.4 L122.4,132.9 L123.0,132.4 L123.5,131.9 L124.1,131.3 L124.6,130.8 L125.2,130.3 L125.8,129.7 L126.3,129.2 L126.9,128.7 L127.4,128.2 L128.0,127.7 L128.5,127.2 L129.1,126.6 L129.6,126.1 L130.2,125.6 L130.7,125.1 L131.3,124.6 L131.8,124.1 L132.4,123.6 L132.9,123.1 L133.5,122.6 L134.0,122.1 L134.6,121.6 L135.1,121.1 L135.7,120.6 L136.2,120.1 L136.8,119.7 L137.4,119.2 L137.9,118.7 L138.5,118.2 L139.0,117.7 L139.6,117.3 L140.1,116.8 L140.7,116.3 L141.2,115.8 L141.8,115.4 L142.3,114.9 L142.9,114.4 L143.4,114.0 L144.0,113.5 L144.5,113.0 L145.1,112.6 L145.6,112.1 L146.2,111.7 L146.7,111.2 L147.3,110.8 L147.8,110.3 L148.4,109.9 L149.0,109.4 L149.5,109.0 L150.1,108.6 L150.6,108.1 L151.2,107.7 L151.7,107.3 L152.3,106.8 L152.8,106.4 L153.4,106.0 L153.9,105.5 L154.5,105.1 L155.0,104.7 L155.6,104.3 L156.1,103.8 L156.7,103.4 L157.2,103.0 L157.8,102.6 L158.3,102.2 L158.9,101.8 L159.4,101.4 L160.0,101.0 L160.6,100.6 L161.1,100.2 L161.7,99.8 L162.2,99.4 L162.8,99.0 L163.3,98.6 L163.9,98.2 L164.4,97.8 L165.0,97.4 L165.5,97.0 L166.1,96.7 L166.6,96.3 L167.2,95.9 L167.7,95.5 L168.3,95.1 L168.8,94.8 L169.4,94.4 L169.9,94.0 L170.5,93.7 L171.0,93.3 L171.6,92.9 L172.2,92.6 L172.7,92.2 L173.3,91.9 L173.8,91.5 L174.4,91.2 L174.9,90.8 L175.5,90.5 L176.0,90.1 L176.6,89.8 L177.1,89.4 L177.7,89.1 L178.2,88.7 L178.8,88.4 L179.3,88.1 L179.9,87.7 L180.4,87.4 L181.0,87.1 L181.5,86.7 L182.1,86.4 L182.6,86.1 L183.2,85.8 L183.8,85.4 L184.3,85.1 L184.9,84.8 L185.4,84.5 L186.0,84.2 L186.5,83.9 L187.1,83.6 L187.6,83.2 L188.2,82.9 L188.7,82.6 L189.3,82.3 L189.8,82.0 L190.4,81.7 L190.9,81.4 L191.5,81.1 L192.0,80.9 L192.6,80.6 L193.1,80.3 L193.7,80.0 L194.2,79.7 L194.8,79.4 L195.4,79.1 L195.9,78.9 L196.5,78.6 L197.0,78.3 L197.6,78.0 L198.1,77.8 L198.7,77.5 L199.2,77.2 L199.8,77.0 L200.3,76.7 L200.9,76.4 L201.4,76.2 L202.0,75.9 L202.5,75.6 L203.1,75.4 L203.6,75.1 L204.2,74.9 L204.7,74.6 L205.3,74.4 L205.8,74.1 L206.4,73.9 L207.0,73.6 L207.5,73.4 L208.1,73.2 L208.6,72.9 L209.2,72.7 L209.7,72.4 L210.3,72.2 L210.8,72.0 L211.4,71.8 L211.9,71.5 L212.5,71.3 L213.0,71.1 L213.6,70.8 L214.1,70.6 L214.7,70.4 L215.2,70.2 L215.8,70.0 L216.3,69.8 L216.9,69.5 L217.4,69.3 L218.0,69.1 L218.6,68.9 L219.1,68.7 L219.7,68.5 L220.2,68.3 L220.8,68.1 L221.3,67.9 L221.9,67.7 L222.4,67.5 L223.0,67.3 L223.5,67.1 L224.1,66.9 L224.6,66.7 L225.2,66.5 L225.7,66.3 L226.3,66.2 L226.8,66.0 L227.4,65.8 L227.9,65.6 L228.5,65.4 L229.0,65.2 L229.6,65.1 L230.2,64.9 L230.7,64.7 L231.3,64.5 L231.8,64.4 L232.4,64.2 L232.9,64.0 L233.5,63.9 L234.0,63.7 L234.6,63.5 L235.1,63.4 L235.7,63.2 L236.2,63.1 L236.8,62.9 L237.3,62.7 L237.9,62.6 L238.4,62.4 L239.0,62.3 L239.5,62.1 L240.1,62.0 L240.6,61.8 L241.2,61.7 L241.8,61.5 L242.3,61.4 L242.9,61.3 L243.4,61.1 L244.0,61.0 L244.5,60.8 L245.1,60.7 L245.6,60.6 L246.2,60.4 L246.7,60.3 L247.3,60.2 L247.8,60.0 L248.4,59.9 L248.9,59.8 L249.5,59.7 L250.0,59.5 L250.6,59.4 L251.1,59.3 L251.7,59.2 L252.2,59.0 L252.8,58.9 L253.4,58.8 L253.9,58.7 L254.5,58.6 L255.0,58.5 L255.6,58.4 L256.1,58.2 L256.7,58.1 L257.2,58.0 L257.8,57.9 L258.3,57.8 L258.9,57.7 L259.4,57.6 L260.0,57.5 L260.5,57.4 L261.1,57.3 L261.6,57.2 L262.2,57.1 L262.7,57.0 L263.3,56.9 L263.8,56.8 L264.4,56.7 L265.0,56.6 L265.5,56.6 L266.1,56.5 L266.6,56.4 L267.2,56.3 L267.7,56.2 L268.3,56.1 L268.8,56.0 L269.4,56.0 L269.9,55.9 L270.5,55.8 L271.0,55.7 L271.6,55.6 L272.1,55.6 L272.7,55.5 L273.2,55.4 L273.8,55.3 L274.3,55.3 L274.9,55.2 L275.4,55.1 L276.0,55.1 L276.6,55.0 L277.1,54.9 L277.7,54.9 L278.2,54.8 L278.8,54.7 L279.3,54.7 L279.9,54.6 L280.4,54.5 L281.0,54.5 L281.5,54.4 L282.1,54.4 L282.6,54.3 L283.2,54.2 L283.7,54.2 L284.3,54.1 L284.8,54.1 L285.4,54.0 L285.9,54.0 L286.5,53.9 L287.0,53.9 L287.6,53.8 L288.2,53.8 L288.7,53.7 L289.3,53.7 L289.8,53.7 L290.4,53.6 L290.9,53.6 L291.5,53.5 L292.0,53.5 L292.6,53.4 L293.1,53.4 L293.7,53.4 L294.2,53.3 L294.8,53.3 L295.3,53.3 L295.9,53.2 L296.4,53.2 L297.0,53.2 L297.5,53.1 L298.1,53.1 L298.6,53.1 L299.2,53.0 L299.8,53.0 L300.3,53.0 L300.9,53.0 L301.4,52.9 L302.0,52.9 L302.5,52.9 L303.1,52.9 L303.6,52.8 L304.2,52.8 L304.7,52.8 L305.3,52.8 L305.8,52.7 L306.4,52.7 L306.9,52.7 L307.5,52.7 L308.0,52.7 L308.6,52.7 L309.1,52.6 L309.7,52.6 L310.2,52.6 L310.8,52.6 L311.4,52.6 L311.9,52.6 L312.5,52.6 L313.0,52.6 L313.6,52.6 L314.1,52.6 L314.7,52.5 L315.2,52.5 L315.8,52.5 L316.3,52.5 L316.9,52.5 L317.4,52.5 L318.0,52.5 L318.5,52.5 L319.1,52.5 L319.6,52.5 L320.2,52.5" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="320.2" cy="52.5" r="3.0" fill="var(--color-practice)"/>
  <path d="M44.0,222.0 L44.6,220.6 L45.1,219.3 L45.7,217.9 L46.2,216.6 L46.8,215.2 L47.3,213.9 L47.9,212.5 L48.4,211.2 L49.0,209.8 L49.5,208.5 L50.1,207.1 L50.6,205.8 L51.2,204.4 L51.7,203.1 L52.3,201.7 L52.8,200.4 L53.4,199.1 L53.9,197.7 L54.5,196.4 L55.0,195.1 L55.6,193.7 L56.2,192.4 L56.7,191.1 L57.3,189.8 L57.8,188.4 L58.4,187.1 L58.9,185.8 L59.5,184.5 L60.0,183.2 L60.6,181.9 L61.1,180.6 L61.7,179.3 L62.2,178.0 L62.8,176.7 L63.3,175.5 L63.9,174.2 L64.4,172.9 L65.0,171.6 L65.5,170.4 L66.1,169.1 L66.6,167.9 L67.2,166.6 L67.8,165.4 L68.3,164.1 L68.9,162.9 L69.4,161.7 L70.0,160.4 L70.5,159.2 L71.1,158.0 L71.6,156.8 L72.2,155.6 L72.7,154.4 L73.3,153.2 L73.8,152.0 L74.4,150.9 L74.9,149.7 L75.5,148.5 L76.0,147.4 L76.6,146.2 L77.1,145.1 L77.7,143.9 L78.2,142.8 L78.8,141.7 L79.4,140.6 L79.9,139.4 L80.5,138.3 L81.0,137.2 L81.6,136.1 L82.1,135.1 L82.7,134.0 L83.2,132.9 L83.8,131.9 L84.3,130.8 L84.9,129.7 L85.4,128.7 L86.0,127.7 L86.5,126.6 L87.1,125.6 L87.6,124.6 L88.2,123.6 L88.7,122.6 L89.3,121.6 L89.8,120.6 L90.4,119.7 L91.0,118.7 L91.5,117.7 L92.1,116.8 L92.6,115.8 L93.2,114.9 L93.7,114.0 L94.3,113.0 L94.8,112.1 L95.4,111.2 L95.9,110.3 L96.5,109.4 L97.0,108.6 L97.6,107.7 L98.1,106.8 L98.7,106.0 L99.2,105.1 L99.8,104.3 L100.3,103.4 L100.9,102.6 L101.4,101.8 L102.0,101.0 L102.6,100.2 L103.1,99.4 L103.7,98.6 L104.2,97.8 L104.8,97.0 L105.3,96.3 L105.9,95.5 L106.4,94.8 L107.0,94.0 L107.5,93.3 L108.1,92.6 L108.6,91.9 L109.2,91.2 L109.7,90.5 L110.3,89.8 L110.8,89.1 L111.4,88.4 L111.9,87.7 L112.5,87.1 L113.0,86.4 L113.6,85.8 L114.2,85.1 L114.7,84.5 L115.3,83.9 L115.8,83.2 L116.4,82.6 L116.9,82.0 L117.5,81.4 L118.0,80.9 L118.6,80.3 L119.1,79.7 L119.7,79.1 L120.2,78.6 L120.8,78.0 L121.3,77.5 L121.9,77.0 L122.4,76.4 L123.0,75.9 L123.5,75.4 L124.1,74.9 L124.6,74.4 L125.2,73.9 L125.8,73.4 L126.3,72.9 L126.9,72.4 L127.4,72.0 L128.0,71.5 L128.5,71.1 L129.1,70.6 L129.6,70.2 L130.2,69.8 L130.7,69.3 L131.3,68.9 L131.8,68.5 L132.4,68.1 L132.9,67.7 L133.5,67.3 L134.0,66.9 L134.6,66.5 L135.1,66.2 L135.7,65.8 L136.2,65.4 L136.8,65.1 L137.4,64.7 L137.9,64.4 L138.5,64.0 L139.0,63.7 L139.6,63.4 L140.1,63.1 L140.7,62.7 L141.2,62.4 L141.8,62.1 L142.3,61.8 L142.9,61.5 L143.4,61.3 L144.0,61.0 L144.5,60.7 L145.1,60.4 L145.6,60.2 L146.2,59.9 L146.7,59.7 L147.3,59.4 L147.8,59.2 L148.4,58.9 L149.0,58.7 L149.5,58.5 L150.1,58.2 L150.6,58.0 L151.2,57.8 L151.7,57.6 L152.3,57.4 L152.8,57.2 L153.4,57.0 L153.9,56.8 L154.5,56.6 L155.0,56.5 L155.6,56.3 L156.1,56.1 L156.7,56.0 L157.2,55.8 L157.8,55.6 L158.3,55.5 L158.9,55.3 L159.4,55.2 L160.0,55.1 L160.6,54.9 L161.1,54.8 L161.7,54.7 L162.2,54.5 L162.8,54.4 L163.3,54.3 L163.9,54.2 L164.4,54.1 L165.0,54.0 L165.5,53.9 L166.1,53.8 L166.6,53.7 L167.2,53.6 L167.7,53.5 L168.3,53.4 L168.8,53.4 L169.4,53.3 L169.9,53.2 L170.5,53.2 L171.0,53.1 L171.6,53.0 L172.2,53.0 L172.7,52.9 L173.3,52.9 L173.8,52.8 L174.4,52.8 L174.9,52.7 L175.5,52.7 L176.0,52.7 L176.6,52.6 L177.1,52.6 L177.7,52.6 L178.2,52.6 L178.8,52.6 L179.3,52.5 L179.9,52.5 L180.4,52.5 L181.0,52.5 L181.5,52.5 L182.1,52.5 L182.6,52.5 L183.2,52.5 L183.8,52.5 L184.3,52.5 L184.9,52.5 L185.4,52.6 L186.0,52.6 L186.5,52.6 L187.1,52.6 L187.6,52.6 L188.2,52.7 L188.7,52.7 L189.3,52.7 L189.8,52.8 L190.4,52.8 L190.9,52.8 L191.5,52.9 L192.0,52.9 L192.6,53.0 L193.1,53.0 L193.7,53.1 L194.2,53.1 L194.8,53.2 L195.4,53.2 L195.9,53.3 L196.5,53.3 L197.0,53.4 L197.6,53.5 L198.1,53.5 L198.7,53.6 L199.2,53.7 L199.8,53.7 L200.3,53.8 L200.9,53.9 L201.4,54.0 L202.0,54.0 L202.5,54.1 L203.1,54.2 L203.6,54.3 L204.2,54.4 L204.7,54.4 L205.3,54.5 L205.8,54.6 L206.4,54.7 L207.0,54.8 L207.5,54.9 L208.1,55.0 L208.6,55.1 L209.2,55.2 L209.7,55.3 L210.3,55.4 L210.8,55.5 L211.4,55.6 L211.9,55.7 L212.5,55.8 L213.0,55.9 L213.6,56.0 L214.1,56.1 L214.7,56.2 L215.2,56.4 L215.8,56.5 L216.3,56.6 L216.9,56.7 L217.4,56.8 L218.0,56.9 L218.6,57.1 L219.1,57.2 L219.7,57.3 L220.2,57.4 L220.8,57.5 L221.3,57.7 L221.9,57.8 L222.4,57.9 L223.0,58.1 L223.5,58.2 L224.1,58.3 L224.6,58.4 L225.2,58.6 L225.7,58.7 L226.3,58.8 L226.8,59.0 L227.4,59.1 L227.9,59.2 L228.5,59.4 L229.0,59.5 L229.6,59.7 L230.2,59.8 L230.7,59.9 L231.3,60.1 L231.8,60.2 L232.4,60.4 L232.9,60.5 L233.5,60.6 L234.0,60.8 L234.6,60.9 L235.1,61.1 L235.7,61.2 L236.2,61.4 L236.8,61.5 L237.3,61.7 L237.9,61.8 L238.4,62.0 L239.0,62.1 L239.5,62.3 L240.1,62.4 L240.6,62.6 L241.2,62.7 L241.8,62.9 L242.3,63.0 L242.9,63.2 L243.4,63.3 L244.0,63.5 L244.5,63.6 L245.1,63.8 L245.6,64.0 L246.2,64.1 L246.7,64.3 L247.3,64.4 L247.8,64.6 L248.4,64.7 L248.9,64.9 L249.5,65.1 L250.0,65.2 L250.6,65.4 L251.1,65.5 L251.7,65.7 L252.2,65.9 L252.8,66.0 L253.4,66.2 L253.9,66.4 L254.5,66.5 L255.0,66.7 L255.6,66.8 L256.1,67.0 L256.7,67.2 L257.2,67.3 L257.8,67.5 L258.3,67.7 L258.9,67.8 L259.4,68.0 L260.0,68.2 L260.5,68.3 L261.1,68.5 L261.6,68.6 L262.2,68.8 L262.7,69.0 L263.3,69.1 L263.8,69.3 L264.4,69.5 L265.0,69.6 L265.5,69.8 L266.1,70.0 L266.6,70.1 L267.2,70.3 L267.7,70.5 L268.3,70.7 L268.8,70.8 L269.4,71.0 L269.9,71.2 L270.5,71.3 L271.0,71.5 L271.6,71.7 L272.1,71.8 L272.7,72.0 L273.2,72.2 L273.8,72.3 L274.3,72.5 L274.9,72.7 L275.4,72.8 L276.0,73.0 L276.6,73.2 L277.1,73.4 L277.7,73.5 L278.2,73.7 L278.8,73.9 L279.3,74.0 L279.9,74.2 L280.4,74.4 L281.0,74.5 L281.5,74.7 L282.1,74.9 L282.6,75.0 L283.2,75.2 L283.7,75.4 L284.3,75.6 L284.8,75.7 L285.4,75.9 L285.9,76.1 L286.5,76.2 L287.0,76.4 L287.6,76.6 L288.2,76.7 L288.7,76.9 L289.3,77.1 L289.8,77.2 L290.4,77.4 L290.9,77.6 L291.5,77.8 L292.0,77.9 L292.6,78.1 L293.1,78.3 L293.7,78.4 L294.2,78.6 L294.8,78.8 L295.3,78.9 L295.9,79.1 L296.4,79.3 L297.0,79.4 L297.5,79.6 L298.1,79.8 L298.6,79.9 L299.2,80.1 L299.8,80.3 L300.3,80.4 L300.9,80.6 L301.4,80.8 L302.0,81.0 L302.5,81.1 L303.1,81.3 L303.6,81.5 L304.2,81.6 L304.7,81.8 L305.3,82.0 L305.8,82.1 L306.4,82.3 L306.9,82.5 L307.5,82.6 L308.0,82.8 L308.6,83.0 L309.1,83.1 L309.7,83.3 L310.2,83.5 L310.8,83.6 L311.4,83.8 L311.9,83.9 L312.5,84.1 L313.0,84.3 L313.6,84.4 L314.1,84.6 L314.7,84.8 L315.2,84.9 L315.8,85.1 L316.3,85.3 L316.9,85.4 L317.4,85.6 L318.0,85.8 L318.5,85.9 L319.1,86.1 L319.6,86.2 L320.2,86.4" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.85" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="182.1" cy="52.5" r="3.0" fill="var(--color-practice)"/>
  <path d="M44.0,222.0 L44.6,219.3 L45.1,216.6 L45.7,213.9 L46.2,211.2 L46.8,208.5 L47.3,205.8 L47.9,203.1 L48.4,200.4 L49.0,197.7 L49.5,195.1 L50.1,192.4 L50.6,189.8 L51.2,187.1 L51.7,184.5 L52.3,181.9 L52.8,179.3 L53.4,176.7 L53.9,174.2 L54.5,171.6 L55.0,169.1 L55.6,166.6 L56.2,164.1 L56.7,161.7 L57.3,159.2 L57.8,156.8 L58.4,154.4 L58.9,152.0 L59.5,149.7 L60.0,147.4 L60.6,145.1 L61.1,142.8 L61.7,140.6 L62.2,138.3 L62.8,136.1 L63.3,134.0 L63.9,131.9 L64.4,129.7 L65.0,127.7 L65.5,125.6 L66.1,123.6 L66.6,121.6 L67.2,119.7 L67.8,117.7 L68.3,115.8 L68.9,114.0 L69.4,112.1 L70.0,110.3 L70.5,108.6 L71.1,106.8 L71.6,105.1 L72.2,103.4 L72.7,101.8 L73.3,100.2 L73.8,98.6 L74.4,97.0 L74.9,95.5 L75.5,94.0 L76.0,92.6 L76.6,91.2 L77.1,89.8 L77.7,88.4 L78.2,87.1 L78.8,85.8 L79.4,84.5 L79.9,83.2 L80.5,82.0 L81.0,80.9 L81.6,79.7 L82.1,78.6 L82.7,77.5 L83.2,76.4 L83.8,75.4 L84.3,74.4 L84.9,73.4 L85.4,72.4 L86.0,71.5 L86.5,70.6 L87.1,69.8 L87.6,68.9 L88.2,68.1 L88.7,67.3 L89.3,66.5 L89.8,65.8 L90.4,65.1 L91.0,64.4 L91.5,63.7 L92.1,63.1 L92.6,62.4 L93.2,61.8 L93.7,61.3 L94.3,60.7 L94.8,60.2 L95.4,59.7 L95.9,59.2 L96.5,58.7 L97.0,58.2 L97.6,57.8 L98.1,57.4 L98.7,57.0 L99.2,56.6 L99.8,56.3 L100.3,56.0 L100.9,55.6 L101.4,55.3 L102.0,55.1 L102.6,54.8 L103.1,54.5 L103.7,54.3 L104.2,54.1 L104.8,53.9 L105.3,53.7 L105.9,53.5 L106.4,53.4 L107.0,53.2 L107.5,53.1 L108.1,53.0 L108.6,52.9 L109.2,52.8 L109.7,52.7 L110.3,52.6 L110.8,52.6 L111.4,52.6 L111.9,52.5 L112.5,52.5 L113.0,52.5 L113.6,52.5 L114.2,52.5 L114.7,52.6 L115.3,52.6 L115.8,52.6 L116.4,52.7 L116.9,52.8 L117.5,52.8 L118.0,52.9 L118.6,53.0 L119.1,53.1 L119.7,53.2 L120.2,53.3 L120.8,53.5 L121.3,53.6 L121.9,53.7 L122.4,53.9 L123.0,54.0 L123.5,54.2 L124.1,54.4 L124.6,54.5 L125.2,54.7 L125.8,54.9 L126.3,55.1 L126.9,55.3 L127.4,55.5 L128.0,55.7 L128.5,55.9 L129.1,56.1 L129.6,56.4 L130.2,56.6 L130.7,56.8 L131.3,57.1 L131.8,57.3 L132.4,57.5 L132.9,57.8 L133.5,58.1 L134.0,58.3 L134.6,58.6 L135.1,58.8 L135.7,59.1 L136.2,59.4 L136.8,59.7 L137.4,59.9 L137.9,60.2 L138.5,60.5 L139.0,60.8 L139.6,61.1 L140.1,61.4 L140.7,61.7 L141.2,62.0 L141.8,62.3 L142.3,62.6 L142.9,62.9 L143.4,63.2 L144.0,63.5 L144.5,63.8 L145.1,64.1 L145.6,64.4 L146.2,64.7 L146.7,65.1 L147.3,65.4 L147.8,65.7 L148.4,66.0 L149.0,66.4 L149.5,66.7 L150.1,67.0 L150.6,67.3 L151.2,67.7 L151.7,68.0 L152.3,68.3 L152.8,68.6 L153.4,69.0 L153.9,69.3 L154.5,69.6 L155.0,70.0 L155.6,70.3 L156.1,70.7 L156.7,71.0 L157.2,71.3 L157.8,71.7 L158.3,72.0 L158.9,72.3 L159.4,72.7 L160.0,73.0 L160.6,73.4 L161.1,73.7 L161.7,74.0 L162.2,74.4 L162.8,74.7 L163.3,75.0 L163.9,75.4 L164.4,75.7 L165.0,76.1 L165.5,76.4 L166.1,76.7 L166.6,77.1 L167.2,77.4 L167.7,77.8 L168.3,78.1 L168.8,78.4 L169.4,78.8 L169.9,79.1 L170.5,79.4 L171.0,79.8 L171.6,80.1 L172.2,80.4 L172.7,80.8 L173.3,81.1 L173.8,81.5 L174.4,81.8 L174.9,82.1 L175.5,82.5 L176.0,82.8 L176.6,83.1 L177.1,83.5 L177.7,83.8 L178.2,84.1 L178.8,84.4 L179.3,84.8 L179.9,85.1 L180.4,85.4 L181.0,85.8 L181.5,86.1 L182.1,86.4 L182.6,86.7 L183.2,87.1 L183.8,87.4 L184.3,87.7 L184.9,88.0 L185.4,88.3 L186.0,88.7 L186.5,89.0 L187.1,89.3 L187.6,89.6 L188.2,89.9 L188.7,90.3 L189.3,90.6 L189.8,90.9 L190.4,91.2 L190.9,91.5 L191.5,91.8 L192.0,92.1 L192.6,92.5 L193.1,92.8 L193.7,93.1 L194.2,93.4 L194.8,93.7 L195.4,94.0 L195.9,94.3 L196.5,94.6 L197.0,94.9 L197.6,95.2 L198.1,95.5 L198.7,95.8 L199.2,96.1 L199.8,96.4 L200.3,96.7 L200.9,97.0 L201.4,97.3 L202.0,97.6 L202.5,97.9 L203.1,98.2 L203.6,98.5 L204.2,98.8 L204.7,99.1 L205.3,99.4 L205.8,99.7 L206.4,99.9 L207.0,100.2 L207.5,100.5 L208.1,100.8 L208.6,101.1 L209.2,101.4 L209.7,101.7 L210.3,101.9 L210.8,102.2 L211.4,102.5 L211.9,102.8 L212.5,103.1 L213.0,103.3 L213.6,103.6 L214.1,103.9 L214.7,104.2 L215.2,104.4 L215.8,104.7 L216.3,105.0 L216.9,105.2 L217.4,105.5 L218.0,105.8 L218.6,106.1 L219.1,106.3 L219.7,106.6 L220.2,106.9 L220.8,107.1 L221.3,107.4 L221.9,107.6 L222.4,107.9 L223.0,108.2 L223.5,108.4 L224.1,108.7 L224.6,108.9 L225.2,109.2 L225.7,109.5 L226.3,109.7 L226.8,110.0 L227.4,110.2 L227.9,110.5 L228.5,110.7 L229.0,111.0 L229.6,111.2 L230.2,111.5 L230.7,111.7 L231.3,112.0 L231.8,112.2 L232.4,112.5 L232.9,112.7 L233.5,112.9 L234.0,113.2 L234.6,113.4 L235.1,113.7 L235.7,113.9 L236.2,114.2 L236.8,114.4 L237.3,114.6 L237.9,114.9 L238.4,115.1 L239.0,115.3 L239.5,115.6 L240.1,115.8 L240.6,116.0 L241.2,116.3 L241.8,116.5 L242.3,116.7 L242.9,117.0 L243.4,117.2 L244.0,117.4 L244.5,117.6 L245.1,117.9 L245.6,118.1 L246.2,118.3 L246.7,118.5 L247.3,118.8 L247.8,119.0 L248.4,119.2 L248.9,119.4 L249.5,119.7 L250.0,119.9 L250.6,120.1 L251.1,120.3 L251.7,120.5 L252.2,120.7 L252.8,121.0 L253.4,121.2 L253.9,121.4 L254.5,121.6 L255.0,121.8 L255.6,122.0 L256.1,122.2 L256.7,122.4 L257.2,122.6 L257.8,122.9 L258.3,123.1 L258.9,123.3 L259.4,123.5 L260.0,123.7 L260.5,123.9 L261.1,124.1 L261.6,124.3 L262.2,124.5 L262.7,124.7 L263.3,124.9 L263.8,125.1 L264.4,125.3 L265.0,125.5 L265.5,125.7 L266.1,125.9 L266.6,126.1 L267.2,126.3 L267.7,126.5 L268.3,126.7 L268.8,126.9 L269.4,127.1 L269.9,127.2 L270.5,127.4 L271.0,127.6 L271.6,127.8 L272.1,128.0 L272.7,128.2 L273.2,128.4 L273.8,128.6 L274.3,128.8 L274.9,129.0 L275.4,129.1 L276.0,129.3 L276.6,129.5 L277.1,129.7 L277.7,129.9 L278.2,130.1 L278.8,130.2 L279.3,130.4 L279.9,130.6 L280.4,130.8 L281.0,131.0 L281.5,131.1 L282.1,131.3 L282.6,131.5 L283.2,131.7 L283.7,131.8 L284.3,132.0 L284.8,132.2 L285.4,132.4 L285.9,132.5 L286.5,132.7 L287.0,132.9 L287.6,133.1 L288.2,133.2 L288.7,133.4 L289.3,133.6 L289.8,133.7 L290.4,133.9 L290.9,134.1 L291.5,134.2 L292.0,134.4 L292.6,134.6 L293.1,134.7 L293.7,134.9 L294.2,135.1 L294.8,135.2 L295.3,135.4 L295.9,135.6 L296.4,135.7 L297.0,135.9 L297.5,136.1 L298.1,136.2 L298.6,136.4 L299.2,136.5 L299.8,136.7 L300.3,136.9 L300.9,137.0 L301.4,137.2 L302.0,137.3 L302.5,137.5 L303.1,137.6 L303.6,137.8 L304.2,138.0 L304.7,138.1 L305.3,138.3 L305.8,138.4 L306.4,138.6 L306.9,138.7 L307.5,138.9 L308.0,139.0 L308.6,139.2 L309.1,139.3 L309.7,139.5 L310.2,139.6 L310.8,139.8 L311.4,139.9 L311.9,140.1 L312.5,140.2 L313.0,140.4 L313.6,140.5 L314.1,140.7 L314.7,140.8 L315.2,141.0 L315.8,141.1 L316.3,141.2 L316.9,141.4 L317.4,141.5 L318.0,141.7 L318.5,141.8 L319.1,142.0 L319.6,142.1 L320.2,142.2" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.7" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="113.0" cy="52.5" r="3.0" fill="var(--color-practice)"/>
  <path d="M44.0,222.0 L44.6,216.6 L45.1,211.2 L45.7,205.8 L46.2,200.4 L46.8,195.1 L47.3,189.8 L47.9,184.5 L48.4,179.3 L49.0,174.2 L49.5,169.1 L50.1,164.1 L50.6,159.2 L51.2,154.4 L51.7,149.7 L52.3,145.1 L52.8,140.6 L53.4,136.1 L53.9,131.9 L54.5,127.7 L55.0,123.6 L55.6,119.7 L56.2,115.8 L56.7,112.1 L57.3,108.6 L57.8,105.1 L58.4,101.8 L58.9,98.6 L59.5,95.5 L60.0,92.6 L60.6,89.8 L61.1,87.1 L61.7,84.5 L62.2,82.0 L62.8,79.7 L63.3,77.5 L63.9,75.4 L64.4,73.4 L65.0,71.5 L65.5,69.8 L66.1,68.1 L66.6,66.5 L67.2,65.1 L67.8,63.7 L68.3,62.4 L68.9,61.3 L69.4,60.2 L70.0,59.2 L70.5,58.2 L71.1,57.4 L71.6,56.6 L72.2,56.0 L72.7,55.3 L73.3,54.8 L73.8,54.3 L74.4,53.9 L74.9,53.5 L75.5,53.2 L76.0,53.0 L76.6,52.8 L77.1,52.6 L77.7,52.6 L78.2,52.5 L78.8,52.5 L79.4,52.6 L79.9,52.6 L80.5,52.8 L81.0,52.9 L81.6,53.1 L82.1,53.3 L82.7,53.6 L83.2,53.9 L83.8,54.2 L84.3,54.5 L84.9,54.9 L85.4,55.3 L86.0,55.7 L86.5,56.1 L87.1,56.6 L87.6,57.1 L88.2,57.5 L88.7,58.1 L89.3,58.6 L89.8,59.1 L90.4,59.7 L91.0,60.2 L91.5,60.8 L92.1,61.4 L92.6,62.0 L93.2,62.6 L93.7,63.2 L94.3,63.8 L94.8,64.4 L95.4,65.1 L95.9,65.7 L96.5,66.4 L97.0,67.0 L97.6,67.7 L98.1,68.3 L98.7,69.0 L99.2,69.6 L99.8,70.3 L100.3,71.0 L100.9,71.7 L101.4,72.3 L102.0,73.0 L102.6,73.7 L103.1,74.4 L103.7,75.0 L104.2,75.7 L104.8,76.4 L105.3,77.1 L105.9,77.8 L106.4,78.4 L107.0,79.1 L107.5,79.8 L108.1,80.4 L108.6,81.1 L109.2,81.8 L109.7,82.5 L110.3,83.1 L110.8,83.8 L111.4,84.4 L111.9,85.1 L112.5,85.8 L113.0,86.4 L113.6,87.1 L114.2,87.7 L114.7,88.3 L115.3,89.0 L115.8,89.6 L116.4,90.3 L116.9,90.9 L117.5,91.5 L118.0,92.1 L118.6,92.8 L119.1,93.4 L119.7,94.0 L120.2,94.6 L120.8,95.2 L121.3,95.8 L121.9,96.4 L122.4,97.0 L123.0,97.6 L123.5,98.2 L124.1,98.8 L124.6,99.4 L125.2,99.9 L125.8,100.5 L126.3,101.1 L126.9,101.7 L127.4,102.2 L128.0,102.8 L128.5,103.3 L129.1,103.9 L129.6,104.4 L130.2,105.0 L130.7,105.5 L131.3,106.1 L131.8,106.6 L132.4,107.1 L132.9,107.6 L133.5,108.2 L134.0,108.7 L134.6,109.2 L135.1,109.7 L135.7,110.2 L136.2,110.7 L136.8,111.2 L137.4,111.7 L137.9,112.2 L138.5,112.7 L139.0,113.2 L139.6,113.7 L140.1,114.2 L140.7,114.6 L141.2,115.1 L141.8,115.6 L142.3,116.0 L142.9,116.5 L143.4,117.0 L144.0,117.4 L144.5,117.9 L145.1,118.3 L145.6,118.8 L146.2,119.2 L146.7,119.7 L147.3,120.1 L147.8,120.5 L148.4,121.0 L149.0,121.4 L149.5,121.8 L150.1,122.2 L150.6,122.6 L151.2,123.1 L151.7,123.5 L152.3,123.9 L152.8,124.3 L153.4,124.7 L153.9,125.1 L154.5,125.5 L155.0,125.9 L155.6,126.3 L156.1,126.7 L156.7,127.1 L157.2,127.4 L157.8,127.8 L158.3,128.2 L158.9,128.6 L159.4,129.0 L160.0,129.3 L160.6,129.7 L161.1,130.1 L161.7,130.4 L162.2,130.8 L162.8,131.1 L163.3,131.5 L163.9,131.8 L164.4,132.2 L165.0,132.5 L165.5,132.9 L166.1,133.2 L166.6,133.6 L167.2,133.9 L167.7,134.2 L168.3,134.6 L168.8,134.9 L169.4,135.2 L169.9,135.6 L170.5,135.9 L171.0,136.2 L171.6,136.5 L172.2,136.9 L172.7,137.2 L173.3,137.5 L173.8,137.8 L174.4,138.1 L174.9,138.4 L175.5,138.7 L176.0,139.0 L176.6,139.3 L177.1,139.6 L177.7,139.9 L178.2,140.2 L178.8,140.5 L179.3,140.8 L179.9,141.1 L180.4,141.4 L181.0,141.7 L181.5,142.0 L182.1,142.2 L182.6,142.5 L183.2,142.8 L183.8,143.1 L184.3,143.4 L184.9,143.6 L185.4,143.9 L186.0,144.2 L186.5,144.4 L187.1,144.7 L187.6,145.0 L188.2,145.2 L188.7,145.5 L189.3,145.7 L189.8,146.0 L190.4,146.3 L190.9,146.5 L191.5,146.8 L192.0,147.0 L192.6,147.3 L193.1,147.5 L193.7,147.8 L194.2,148.0 L194.8,148.3 L195.4,148.5 L195.9,148.7 L196.5,149.0 L197.0,149.2 L197.6,149.5 L198.1,149.7 L198.7,149.9 L199.2,150.2 L199.8,150.4 L200.3,150.6 L200.9,150.8 L201.4,151.1 L202.0,151.3 L202.5,151.5 L203.1,151.7 L203.6,152.0 L204.2,152.2 L204.7,152.4 L205.3,152.6 L205.8,152.8 L206.4,153.1 L207.0,153.3 L207.5,153.5 L208.1,153.7 L208.6,153.9 L209.2,154.1 L209.7,154.3 L210.3,154.5 L210.8,154.7 L211.4,154.9 L211.9,155.1 L212.5,155.3 L213.0,155.5 L213.6,155.7 L214.1,155.9 L214.7,156.1 L215.2,156.3 L215.8,156.5 L216.3,156.7 L216.9,156.9 L217.4,157.1 L218.0,157.3 L218.6,157.5 L219.1,157.7 L219.7,157.9 L220.2,158.0 L220.8,158.2 L221.3,158.4 L221.9,158.6 L222.4,158.8 L223.0,159.0 L223.5,159.1 L224.1,159.3 L224.6,159.5 L225.2,159.7 L225.7,159.8 L226.3,160.0 L226.8,160.2 L227.4,160.4 L227.9,160.5 L228.5,160.7 L229.0,160.9 L229.6,161.1 L230.2,161.2 L230.7,161.4 L231.3,161.6 L231.8,161.7 L232.4,161.9 L232.9,162.1 L233.5,162.2 L234.0,162.4 L234.6,162.5 L235.1,162.7 L235.7,162.9 L236.2,163.0 L236.8,163.2 L237.3,163.3 L237.9,163.5 L238.4,163.7 L239.0,163.8 L239.5,164.0 L240.1,164.1 L240.6,164.3 L241.2,164.4 L241.8,164.6 L242.3,164.7 L242.9,164.9 L243.4,165.0 L244.0,165.2 L244.5,165.3 L245.1,165.5 L245.6,165.6 L246.2,165.8 L246.7,165.9 L247.3,166.0 L247.8,166.2 L248.4,166.3 L248.9,166.5 L249.5,166.6 L250.0,166.8 L250.6,166.9 L251.1,167.0 L251.7,167.2 L252.2,167.3 L252.8,167.4 L253.4,167.6 L253.9,167.7 L254.5,167.8 L255.0,168.0 L255.6,168.1 L256.1,168.3 L256.7,168.4 L257.2,168.5 L257.8,168.6 L258.3,168.8 L258.9,168.9 L259.4,169.0 L260.0,169.2 L260.5,169.3 L261.1,169.4 L261.6,169.5 L262.2,169.7 L262.7,169.8 L263.3,169.9 L263.8,170.0 L264.4,170.2 L265.0,170.3 L265.5,170.4 L266.1,170.5 L266.6,170.7 L267.2,170.8 L267.7,170.9 L268.3,171.0 L268.8,171.1 L269.4,171.3 L269.9,171.4 L270.5,171.5 L271.0,171.6 L271.6,171.7 L272.1,171.8 L272.7,172.0 L273.2,172.1 L273.8,172.2 L274.3,172.3 L274.9,172.4 L275.4,172.5 L276.0,172.6 L276.6,172.8 L277.1,172.9 L277.7,173.0 L278.2,173.1 L278.8,173.2 L279.3,173.3 L279.9,173.4 L280.4,173.5 L281.0,173.6 L281.5,173.7 L282.1,173.9 L282.6,174.0 L283.2,174.1 L283.7,174.2 L284.3,174.3 L284.8,174.4 L285.4,174.5 L285.9,174.6 L286.5,174.7 L287.0,174.8 L287.6,174.9 L288.2,175.0 L288.7,175.1 L289.3,175.2 L289.8,175.3 L290.4,175.4 L290.9,175.5 L291.5,175.6 L292.0,175.7 L292.6,175.8 L293.1,175.9 L293.7,176.0 L294.2,176.1 L294.8,176.2 L295.3,176.3 L295.9,176.4 L296.4,176.5 L297.0,176.6 L297.5,176.7 L298.1,176.8 L298.6,176.9 L299.2,177.0 L299.8,177.1 L300.3,177.2 L300.9,177.2 L301.4,177.3 L302.0,177.4 L302.5,177.5 L303.1,177.6 L303.6,177.7 L304.2,177.8 L304.7,177.9 L305.3,178.0 L305.8,178.1 L306.4,178.2 L306.9,178.2 L307.5,178.3 L308.0,178.4 L308.6,178.5 L309.1,178.6 L309.7,178.7 L310.2,178.8 L310.8,178.9 L311.4,178.9 L311.9,179.0 L312.5,179.1 L313.0,179.2 L313.6,179.3 L314.1,179.4 L314.7,179.5 L315.2,179.5 L315.8,179.6 L316.3,179.7 L316.9,179.8 L317.4,179.9 L318.0,180.0 L318.5,180.0 L319.1,180.1 L319.6,180.2 L320.2,180.3" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.58" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="78.5" cy="52.5" r="3.0" fill="var(--color-practice)"/>
  <path d="M44.0,222.0 L44.6,208.5 L45.1,195.1 L45.7,181.9 L46.2,169.1 L46.8,156.8 L47.3,145.1 L47.9,134.0 L48.4,123.6 L49.0,114.0 L49.5,105.1 L50.1,97.0 L50.6,89.8 L51.2,83.2 L51.7,77.5 L52.3,72.4 L52.8,68.1 L53.4,64.4 L53.9,61.3 L54.5,58.7 L55.0,56.6 L55.6,55.1 L56.2,53.9 L56.7,53.1 L57.3,52.6 L57.8,52.5 L58.4,52.6 L58.9,53.0 L59.5,53.6 L60.0,54.4 L60.6,55.3 L61.1,56.4 L61.7,57.5 L62.2,58.8 L62.8,60.2 L63.3,61.7 L63.9,63.2 L64.4,64.7 L65.0,66.4 L65.5,68.0 L66.1,69.6 L66.6,71.3 L67.2,73.0 L67.8,74.7 L68.3,76.4 L68.9,78.1 L69.4,79.8 L70.0,81.5 L70.5,83.1 L71.1,84.8 L71.6,86.4 L72.2,88.0 L72.7,89.6 L73.3,91.2 L73.8,92.8 L74.4,94.3 L74.9,95.8 L75.5,97.3 L76.0,98.8 L76.6,100.2 L77.1,101.7 L77.7,103.1 L78.2,104.4 L78.8,105.8 L79.4,107.1 L79.9,108.4 L80.5,109.7 L81.0,111.0 L81.6,112.2 L82.1,113.4 L82.7,114.6 L83.2,115.8 L83.8,117.0 L84.3,118.1 L84.9,119.2 L85.4,120.3 L86.0,121.4 L86.5,122.4 L87.1,123.5 L87.6,124.5 L88.2,125.5 L88.7,126.5 L89.3,127.4 L89.8,128.4 L90.4,129.3 L91.0,130.2 L91.5,131.1 L92.1,132.0 L92.6,132.9 L93.2,133.7 L93.7,134.6 L94.3,135.4 L94.8,136.2 L95.4,137.0 L95.9,137.8 L96.5,138.6 L97.0,139.3 L97.6,140.1 L98.1,140.8 L98.7,141.5 L99.2,142.2 L99.8,142.9 L100.3,143.6 L100.9,144.3 L101.4,145.0 L102.0,145.6 L102.6,146.3 L103.1,146.9 L103.7,147.5 L104.2,148.1 L104.8,148.7 L105.3,149.3 L105.9,149.9 L106.4,150.5 L107.0,151.1 L107.5,151.6 L108.1,152.2 L108.6,152.7 L109.2,153.3 L109.7,153.8 L110.3,154.3 L110.8,154.8 L111.4,155.3 L111.9,155.8 L112.5,156.3 L113.0,156.8 L113.6,157.3 L114.2,157.8 L114.7,158.2 L115.3,158.7 L115.8,159.1 L116.4,159.6 L116.9,160.0 L117.5,160.5 L118.0,160.9 L118.6,161.3 L119.1,161.7 L119.7,162.1 L120.2,162.5 L120.8,162.9 L121.3,163.3 L121.9,163.7 L122.4,164.1 L123.0,164.5 L123.5,164.9 L124.1,165.2 L124.6,165.6 L125.2,166.0 L125.8,166.3 L126.3,166.7 L126.9,167.0 L127.4,167.4 L128.0,167.7 L128.5,168.1 L129.1,168.4 L129.6,168.7 L130.2,169.0 L130.7,169.4 L131.3,169.7 L131.8,170.0 L132.4,170.3 L132.9,170.6 L133.5,170.9 L134.0,171.2 L134.6,171.5 L135.1,171.8 L135.7,172.1 L136.2,172.4 L136.8,172.6 L137.4,172.9 L137.9,173.2 L138.5,173.5 L139.0,173.7 L139.6,174.0 L140.1,174.3 L140.7,174.5 L141.2,174.8 L141.8,175.1 L142.3,175.3 L142.9,175.6 L143.4,175.8 L144.0,176.1 L144.5,176.3 L145.1,176.5 L145.6,176.8 L146.2,177.0 L146.7,177.2 L147.3,177.5 L147.8,177.7 L148.4,177.9 L149.0,178.2 L149.5,178.4 L150.1,178.6 L150.6,178.8 L151.2,179.0 L151.7,179.2 L152.3,179.5 L152.8,179.7 L153.4,179.9 L153.9,180.1 L154.5,180.3 L155.0,180.5 L155.6,180.7 L156.1,180.9 L156.7,181.1 L157.2,181.3 L157.8,181.5 L158.3,181.6 L158.9,181.8 L159.4,182.0 L160.0,182.2 L160.6,182.4 L161.1,182.6 L161.7,182.8 L162.2,182.9 L162.8,183.1 L163.3,183.3 L163.9,183.5 L164.4,183.6 L165.0,183.8 L165.5,184.0 L166.1,184.1 L166.6,184.3 L167.2,184.5 L167.7,184.6 L168.3,184.8 L168.8,185.0 L169.4,185.1 L169.9,185.3 L170.5,185.4 L171.0,185.6 L171.6,185.7 L172.2,185.9 L172.7,186.0 L173.3,186.2 L173.8,186.3 L174.4,186.5 L174.9,186.6 L175.5,186.8 L176.0,186.9 L176.6,187.1 L177.1,187.2 L177.7,187.4 L178.2,187.5 L178.8,187.6 L179.3,187.8 L179.9,187.9 L180.4,188.0 L181.0,188.2 L181.5,188.3 L182.1,188.4 L182.6,188.6 L183.2,188.7 L183.8,188.8 L184.3,189.0 L184.9,189.1 L185.4,189.2 L186.0,189.3 L186.5,189.5 L187.1,189.6 L187.6,189.7 L188.2,189.8 L188.7,189.9 L189.3,190.1 L189.8,190.2 L190.4,190.3 L190.9,190.4 L191.5,190.5 L192.0,190.7 L192.6,190.8 L193.1,190.9 L193.7,191.0 L194.2,191.1 L194.8,191.2 L195.4,191.3 L195.9,191.4 L196.5,191.5 L197.0,191.7 L197.6,191.8 L198.1,191.9 L198.7,192.0 L199.2,192.1 L199.8,192.2 L200.3,192.3 L200.9,192.4 L201.4,192.5 L202.0,192.6 L202.5,192.7 L203.1,192.8 L203.6,192.9 L204.2,193.0 L204.7,193.1 L205.3,193.2 L205.8,193.3 L206.4,193.4 L207.0,193.5 L207.5,193.6 L208.1,193.7 L208.6,193.8 L209.2,193.9 L209.7,193.9 L210.3,194.0 L210.8,194.1 L211.4,194.2 L211.9,194.3 L212.5,194.4 L213.0,194.5 L213.6,194.6 L214.1,194.7 L214.7,194.8 L215.2,194.8 L215.8,194.9 L216.3,195.0 L216.9,195.1 L217.4,195.2 L218.0,195.3 L218.6,195.3 L219.1,195.4 L219.7,195.5 L220.2,195.6 L220.8,195.7 L221.3,195.8 L221.9,195.8 L222.4,195.9 L223.0,196.0 L223.5,196.1 L224.1,196.2 L224.6,196.2 L225.2,196.3 L225.7,196.4 L226.3,196.5 L226.8,196.5 L227.4,196.6 L227.9,196.7 L228.5,196.8 L229.0,196.8 L229.6,196.9 L230.2,197.0 L230.7,197.1 L231.3,197.1 L231.8,197.2 L232.4,197.3 L232.9,197.4 L233.5,197.4 L234.0,197.5 L234.6,197.6 L235.1,197.6 L235.7,197.7 L236.2,197.8 L236.8,197.8 L237.3,197.9 L237.9,198.0 L238.4,198.0 L239.0,198.1 L239.5,198.2 L240.1,198.2 L240.6,198.3 L241.2,198.4 L241.8,198.4 L242.3,198.5 L242.9,198.6 L243.4,198.6 L244.0,198.7 L244.5,198.8 L245.1,198.8 L245.6,198.9 L246.2,199.0 L246.7,199.0 L247.3,199.1 L247.8,199.1 L248.4,199.2 L248.9,199.3 L249.5,199.3 L250.0,199.4 L250.6,199.4 L251.1,199.5 L251.7,199.6 L252.2,199.6 L252.8,199.7 L253.4,199.7 L253.9,199.8 L254.5,199.9 L255.0,199.9 L255.6,200.0 L256.1,200.0 L256.7,200.1 L257.2,200.1 L257.8,200.2 L258.3,200.2 L258.9,200.3 L259.4,200.4 L260.0,200.4 L260.5,200.5 L261.1,200.5 L261.6,200.6 L262.2,200.6 L262.7,200.7 L263.3,200.7 L263.8,200.8 L264.4,200.8 L265.0,200.9 L265.5,200.9 L266.1,201.0 L266.6,201.1 L267.2,201.1 L267.7,201.2 L268.3,201.2 L268.8,201.3 L269.4,201.3 L269.9,201.4 L270.5,201.4 L271.0,201.5 L271.6,201.5 L272.1,201.6 L272.7,201.6 L273.2,201.7 L273.8,201.7 L274.3,201.8 L274.9,201.8 L275.4,201.8 L276.0,201.9 L276.6,201.9 L277.1,202.0 L277.7,202.0 L278.2,202.1 L278.8,202.1 L279.3,202.2 L279.9,202.2 L280.4,202.3 L281.0,202.3 L281.5,202.4 L282.1,202.4 L282.6,202.4 L283.2,202.5 L283.7,202.5 L284.3,202.6 L284.8,202.6 L285.4,202.7 L285.9,202.7 L286.5,202.8 L287.0,202.8 L287.6,202.8 L288.2,202.9 L288.7,202.9 L289.3,203.0 L289.8,203.0 L290.4,203.1 L290.9,203.1 L291.5,203.1 L292.0,203.2 L292.6,203.2 L293.1,203.3 L293.7,203.3 L294.2,203.3 L294.8,203.4 L295.3,203.4 L295.9,203.5 L296.4,203.5 L297.0,203.6 L297.5,203.6 L298.1,203.6 L298.6,203.7 L299.2,203.7 L299.8,203.7 L300.3,203.8 L300.9,203.8 L301.4,203.9 L302.0,203.9 L302.5,203.9 L303.1,204.0 L303.6,204.0 L304.2,204.1 L304.7,204.1 L305.3,204.1 L305.8,204.2 L306.4,204.2 L306.9,204.2 L307.5,204.3 L308.0,204.3 L308.6,204.4 L309.1,204.4 L309.7,204.4 L310.2,204.5 L310.8,204.5 L311.4,204.5 L311.9,204.6 L312.5,204.6 L313.0,204.6 L313.6,204.7 L314.1,204.7 L314.7,204.7 L315.2,204.8 L315.8,204.8 L316.3,204.9 L316.9,204.9 L317.4,204.9 L318.0,205.0 L318.5,205.0 L319.1,205.0 L319.6,205.1 L320.2,205.1" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.46" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="57.8" cy="52.5" r="3.0" fill="var(--color-practice)"/>
  <text x="316.2" y="44.5" fill="var(--color-theory)" font-size="10.5" text-anchor="end" font-style="italic">n = 1</text>
  <text x="316.2" y="198.1" fill="var(--color-theory)" font-size="10.5" text-anchor="end" font-style="italic">n = 20</text>
</svg>
<figcaption><em>f<sub>n</sub></em>(<em>x</em>) = 2<em>nx</em>/(1 + <em>n</em><sup>2</sup><em>x</em><sup>2</sup>) dizisinin <em>n</em> = 1, 2, 4, 8, 20 terimleri. Tepe noktası (1/<em>n</em>, 1) sola kayar ama alçalmaz; her sabit <em>x</em> noktasında değerler yine de 0'a gider.</figcaption>
</figure>
```

Dizinin ilk terimleri

$$f_1(x) = \frac{2x}{1 + x^2}, \qquad f_2(x) = \frac{4x}{1 + 4x^2}, \qquad f_3(x) = \frac{6x}{1 + 9x^2}$$

fonksiyonlarıdır.

**Limit adayı.** $x = 0$ için her $n$'de $f_n(0) = 0$ olduğundan $\lim_{n \to \infty} f_n(0) = 0$'dır. $0 < x \le 1$ için pay ve paydayı $n^2$ ile bölelim:

$$\lim_{n \to \infty} \frac{2nx}{1 + n^2x^2} = \lim_{n \to \infty} \frac{\dfrac{2x}{n}}{\dfrac{1}{n^2} + x^2} = \frac{0}{0 + x^2} = 0.$$

Öyleyse limit adayı $f(x) = 0$ sabit fonksiyonudur.

**Tanımla doğrulama.** $\varepsilon > 0$ ve $x \in (0, 1]$ verilsin. Paydayı küçülterek kesri büyütelim: $1 + n^2x^2 > n^2x^2$ olduğundan

$$\left| \frac{2nx}{1 + n^2x^2} - 0 \right| = \frac{2nx}{1 + n^2x^2} < \frac{2nx}{n^2x^2} = \frac{2}{nx}.$$

$\dfrac{2}{nx} < \varepsilon$ olması için $n > \dfrac{2}{\varepsilon x}$ yeter. Dolayısıyla

$$N(\varepsilon, x) = \left\lfloor \frac{2}{\varepsilon x} \right\rfloor + 1$$

seçilirse $n \ge N$ için $|f_n(x) - 0| < \varepsilon$ olur. $x = 0$ noktasında her $N$ işe yarar. Sonuç: $f_n \to 0$ (noktasal, $[0, 1]$).

**Bir gözlem.** $(1 - nx)^2 \ge 0$ eşitsizliği $2nx \le 1 + n^2x^2$ demektir; yani her $x$ için $f_n(x) \le 1$'dir ve eşitlik $x = \dfrac{1}{n}$ noktasında sağlanır: $f_n\left(\dfrac{1}{n}\right) = 1$. Her $f_n$'nin grafiğinde yüksekliği $1$ olan bir tepe vardır; $n$ büyüdükçe tepe sola kayar ama alçalmaz. Her sabit $x$ noktasında değerler $0$'a gittiği hâlde grafikler bir bütün olarak $0$ fonksiyonuna yaklaşmaz. Bu olguyu [Düzgün Yakınsaklık](duzgun-yakinsaklik.qmd) bölümünde yeniden ele alacağız. [$\blacksquare$]{.qed}
:::
::::

### Noktasal yakınsamama

Bir dizinin verilen bir fonksiyona noktasal yakınsamadığını göstermek için tanımın olumsuzunu yazmak gerekir.

:::: {#prp-nok-yakinsamama name="Noktasal Yakınsamamanın Sembolik İfadesi"}
$(f_n)$, $E$ üzerinde tanımlı bir fonksiyon dizisi ve $f : E \to \mathbb{R}$ olsun. $(f_n)$ dizisinin $E$ üzerinde $f$'ye noktasal yakınsamaması için gerek ve yeter koşul şudur: öyle bir $\varepsilon_0 > 0$ ve öyle bir $x_0 \in E$ vardır ki her $N \in \mathbb{N}$ için

$$n_N \ge N \qquad \text{ve} \qquad |f_{n_N}(x_0) - f(x_0)| \ge \varepsilon_0$$

olacak biçimde bir $n_N \in \mathbb{N}$ bulunur.

::: {.ispat}
Noktasal yakınsaklık, "her $x \in E$ için $f_n(x) \to f(x)$" önermesidir. Olumsuzu, "en az bir $x_0 \in E$ için $\big(f_n(x_0)\big)$ dizisi $f(x_0)$'a yakınsamaz" önermesidir. Bir sayı dizisinin verilen bir sayıya yakınsamaması ise tam olarak şu demektir (bkz. [Analiz 1](../analiz-1/dizilerde-yakinsaklik.html#prp-yakinsamama-olumsuzlama)): öyle bir $\varepsilon_0 > 0$ vardır ki her $N$ için $n_N \ge N$ ve $|f_{n_N}(x_0) - f(x_0)| \ge \varepsilon_0$ olacak biçimde bir $n_N$ bulunur. İki adım birleşince iddia çıkar. [$\blacksquare$]{.qed}
:::
::::

:::: {#exm-nok-nx name="Hiçbir Noktada Yakınsamayan Bir Dizi"}
$E = (0, +\infty)$ üzerinde $f_n(x) = nx$ ile tanımlı $(f_n)$ dizisinin $E$ üzerinde noktasal yakınsak olmadığını gösteriniz.

::: {.cozum}
```{=html}
<figure class="ders-grafik ders-grafik-dar">
<svg viewBox="17.0 -11.5 311.0 283.5" role="img" aria-label="Lines through the origin with slopes one to five and their values at x equal one">
  <g stroke="var(--academic-text)" stroke-width="1.1" opacity="0.45">
  <line x1="44.0" y1="242.0" x2="302.0" y2="242.0"/>
  <line x1="44.0" y1="14.0" x2="44.0" y2="242.0"/>
  </g>
  <g fill="var(--academic-text)" font-size="11" opacity="0.7">
  <text x="152.7" y="258.0" text-anchor="middle">1</text>
  <text x="261.4" y="258.0" text-anchor="middle">2</text>
  <text x="37.0" y="206.7" text-anchor="end">1</text>
  <text x="37.0" y="167.4" text-anchor="end">2</text>
  <text x="37.0" y="128.1" text-anchor="end">3</text>
  <text x="37.0" y="88.9" text-anchor="end">4</text>
  <text x="37.0" y="49.6" text-anchor="end">5</text>
  <text x="308.0" y="246.0" font-style="italic">x</text>
  <text x="40.0" y="8.0" text-anchor="middle" font-style="italic">y</text>
  </g>
  <path d="M152.7,242.0 L152.7,33.8" fill="none" stroke="var(--academic-text)" stroke-width="1.0" stroke-dasharray="4 3" opacity="0.5" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,242.0 L283.1,155.6" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.9" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="152.7" cy="202.7" r="3.2" fill="var(--color-practice)"/>
  <path d="M44.0,202.7 L152.7,202.7" fill="none" stroke="var(--academic-text)" stroke-width="1.0" stroke-dasharray="2 3" opacity="0.35" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,242.0 L283.1,69.1" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.8" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="152.7" cy="163.4" r="3.2" fill="var(--color-practice)"/>
  <path d="M44.0,163.4 L152.7,163.4" fill="none" stroke="var(--academic-text)" stroke-width="1.0" stroke-dasharray="2 3" opacity="0.35" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,242.0 L239.7,29.9" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.7" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="152.7" cy="124.1" r="3.2" fill="var(--color-practice)"/>
  <path d="M44.0,124.1 L152.7,124.1" fill="none" stroke="var(--academic-text)" stroke-width="1.0" stroke-dasharray="2 3" opacity="0.35" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,242.0 L190.7,29.9" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.6" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="152.7" cy="84.9" r="3.2" fill="var(--color-practice)"/>
  <path d="M44.0,84.9 L152.7,84.9" fill="none" stroke="var(--academic-text)" stroke-width="1.0" stroke-dasharray="2 3" opacity="0.35" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M44.0,242.0 L161.4,29.9" fill="none" stroke="var(--color-theory)" stroke-width="1.8" opacity="0.5" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="152.7" cy="45.6" r="3.2" fill="var(--color-practice)"/>
  <path d="M44.0,45.6 L152.7,45.6" fill="none" stroke="var(--academic-text)" stroke-width="1.0" stroke-dasharray="2 3" opacity="0.35" stroke-linejoin="round" stroke-linecap="round"/>
  <text x="288.1" y="159.6" fill="var(--color-theory)" font-size="11" text-anchor="start" font-style="italic">f<tspan font-size="9" dy="4">1</tspan><tspan dy="-4">&#8203;</tspan></text>
  <text x="288.1" y="73.1" fill="var(--color-theory)" font-size="11" text-anchor="start" font-style="italic">f<tspan font-size="9" dy="4">2</tspan><tspan dy="-4">&#8203;</tspan></text>
  <text x="159.4" y="22.9" fill="var(--color-theory)" font-size="11" text-anchor="middle" font-style="italic">f<tspan font-size="9" dy="4">5</tspan><tspan dy="-4">&#8203;</tspan></text>
</svg>
<figcaption><em>f<sub>n</sub></em>(<em>x</em>) = <em>nx</em> doğruları. <em>x</em> = 1 noktasındaki değerler 1, 2, 3, &#8230; sayı dizisini oluşturur ve bu dizi ıraksaktır.</figcaption>
</figure>
```

$x \in E$ sabit olsun. $x > 0$ olduğundan

$$\lim_{n \to \infty} f_n(x) = \lim_{n \to \infty} nx = +\infty$$

olur; $\big(f_n(x)\big)$ dizisi sınırsızdır, dolayısıyla ıraksaktır (bkz. [Analiz 1](../analiz-1/dizilerde-yakinsaklik.html#cor-sinirsiz-iraksak)). Dizi $E$'nin her noktasında ıraksadığından $E$ üzerinde ıraksaktır; hiçbir $f$ fonksiyonuna noktasal yakınsamaz.

Aynı sonucu @prp-nok-yakinsamama ile de görelim. $f : E \to \mathbb{R}$ herhangi bir fonksiyon olsun. $x_0 = 1$ ve $\varepsilon_0 = \dfrac{1}{2}$ alalım. $N \in \mathbb{N}$ verilsin. Arşimet özelliğine göre $n_N \ge N$ ve $n_N \ge |f(1)| + 1$ olan bir $n_N$ doğal sayısı vardır. Bu sayı için

$$|f_{n_N}(1) - f(1)| \ge n_N - |f(1)| \ge 1 > \frac{1}{2} = \varepsilon_0$$

olur. Dikkat edilirse $\big(f_n(1)\big) = (1, 2, 3, 4, \dots)$ bir reel sayı dizisidir ve ıraksaklığı doğrudan görülür. [$\blacksquare$]{.qed}
:::
::::

:::: {#exm-nok-x-bolu-n name="Yatıklaşan Doğrular"}
$E = [0, +\infty)$ üzerinde $f_n(x) = \dfrac{x}{n}$ ile tanımlı $(f_n)$ dizisi noktasal yakınsak mıdır?

::: {.cozum}
$x = 0$ için her $n$'de $f_n(0) = 0$ olduğundan $\lim_{n \to \infty} f_n(0) = 0$'dır. $x > 0$ için

$$\lim_{n \to \infty} \frac{x}{n} = x \cdot \lim_{n \to \infty} \frac{1}{n} = x \cdot 0 = 0$$

olur. Limit adayı $f(x) = 0$ fonksiyonudur. Tanımla doğrulayalım: $\varepsilon > 0$ ve $x > 0$ verilsin. $n \ge N$ için

$$|f_n(x) - 0| = \frac{x}{n} \le \frac{x}{N}$$

olduğundan $\dfrac{x}{N} < \varepsilon$, yani $N > \dfrac{x}{\varepsilon}$ olması yeter. $N(\varepsilon, x) = \left\lfloor \dfrac{x}{\varepsilon} \right\rfloor + 1$ seçilir. Sonuç: $f_n \to 0$ (noktasal, $[0, +\infty)$).

Burada da $N$ sayısı $x$'e bağlıdır ve $x$ büyüdükçe sınırsız büyür. [$\blacksquare$]{.qed}
:::
::::

## Noktasal Limitin Cebirsel Özellikleri

Noktasal limit her noktada bir sayı dizisi limiti olduğundan, sayı dizilerindeki limit aritmetiği fonksiyon dizilerine aynen taşınır.

:::: {#thm-nok-cebir name="Noktasal Limitin Cebirsel Özellikleri"}
$E \subseteq \mathbb{R}$ boş olmayan bir küme, $(f_n)$ ve $(g_n)$ dizileri $E$ üzerinde tanımlı fonksiyon dizileri, $c \in \mathbb{R}$ olsun. $E$ üzerinde $f_n \to f$ ve $g_n \to g$ noktasal yakınsıyorsa:

(i) $f_n + g_n \to f + g$ (noktasal, $E$),

(ii) $c \cdot f_n \to c \cdot f$ (noktasal, $E$),

(iii) $f_n \cdot g_n \to f \cdot g$ (noktasal, $E$),

(iv) her $x \in E$ ve her $n \in \mathbb{N}$ için $g_n(x) \ne 0$ ve $g(x) \ne 0$ ise $\dfrac{f_n}{g_n} \to \dfrac{f}{g}$ (noktasal, $E$).

::: {.ispat}
**(i)** $\varepsilon > 0$ ve $x \in E$ verilsin. $f_n(x) \to f(x)$ olduğundan öyle bir $N_1 = N_1(\varepsilon, x)$ vardır ki $n \ge N_1$ için $|f_n(x) - f(x)| < \dfrac{\varepsilon}{2}$ olur. $g_n(x) \to g(x)$ olduğundan öyle bir $N_2 = N_2(\varepsilon, x)$ vardır ki $n \ge N_2$ için $|g_n(x) - g(x)| < \dfrac{\varepsilon}{2}$ olur. $N = \max\{N_1, N_2\}$ alalım. $n \ge N$ için üçgen eşitsizliğiyle

$$
\begin{aligned}
\big|(f_n + g_n)(x) - (f + g)(x)\big| &= \big|\big(f_n(x) - f(x)\big) + \big(g_n(x) - g(x)\big)\big| \\[1mm]
&\le |f_n(x) - f(x)| + |g_n(x) - g(x)| \\[1mm]
&< \frac{\varepsilon}{2} + \frac{\varepsilon}{2} = \varepsilon
\end{aligned}
$$

bulunur. Öyleyse $f_n + g_n \to f + g$ (noktasal).

**(ii), (iii), (iv)** $x \in E$ sabit olsun. $\big(f_n(x)\big)$ ve $\big(g_n(x)\big)$ yakınsak sayı dizileridir; limitleri $f(x)$ ve $g(x)$'tir. Sayı dizileri için limit aritmetiği (bkz. [Analiz 1](../analiz-1/limit-islemleri-ve-sikistirma.html#thm-limit-aritmetigi)) gereği

$$c f_n(x) \to c f(x), \qquad f_n(x)\,g_n(x) \to f(x)\,g(x)$$

olur; ayrıca (iv)'ün koşulları altında $g_n(x) \ne 0$ ve $g(x) \ne 0$ olduğundan $\dfrac{f_n(x)}{g_n(x)} \to \dfrac{f(x)}{g(x)}$ olur. $x \in E$ keyfi olduğundan üç yakınsama da $E$ üzerinde noktasaldır. [$\blacksquare$]{.qed}
:::
::::

## Noktasal Limit Neleri Korumaz?

Bir dizinin bütün terimleri iyi bir özelliğe sahipse limit fonksiyonunun da o özelliğe sahip olmasını bekleriz. Noktasal yakınsaklık bu beklentiyi karşılamaz. Üç temel özelliğe sırayla bakalım.

:::: {#exm-nok-sureklilik-bozulur name="Sürekli Fonksiyonların Süreksiz Noktasal Limiti"}
Sürekli ve türevlenebilir fonksiyonlardan oluşan, ama noktasal limiti sürekli olmayan bir fonksiyon dizisi veriniz.

::: {.cozum}
$[0, 1]$ üzerinde $f_n(x) = x^n$ alalım. Her $f_n$ bir polinomdur; $[0, 1]$ üzerinde sürekli ve türevlenebilirdir. @exm-nok-xn gereği noktasal limit

$$f(x) = \begin{cases} 0, & 0 \le x < 1 \\ 1, & x = 1 \end{cases}$$

fonksiyonudur. $f$, $x = 1$ noktasında sürekli değildir: $x \to 1^-$ iken $f(x) = 0 \to 0$ olur, ama $f(1) = 1$'dir. Bir noktada sürekli olmayan fonksiyon o noktada türevlenebilir de olamaz; dolayısıyla $f$, $x = 1$'de türevlenebilir değildir.

Öyleyse sürekli fonksiyonların noktasal limiti sürekli olmayabilir; türevlenebilir fonksiyonların noktasal limiti türevlenebilir olmayabilir. [$\blacksquare$]{.qed}
:::
::::

:::: {#exm-nok-integral-bozulur name="İntegrallenebilir Fonksiyonların İntegrallenemeyen Noktasal Limiti"}
$[0, 1]$ üzerinde Riemann integrallenebilir fonksiyonlardan oluşan, ama noktasal limiti integrallenebilir olmayan bir fonksiyon dizisi veriniz.

::: {.cozum}
Her $n \in \mathbb{N}$ için $[0, 1]$ aralığındaki, paydası en çok $n$ olan kesirlerin kümesini

$$A_n = \left\{ \frac{p}{m} : m \in \{1, \dots, n\},\ p \in \{0, 1, \dots, m\} \right\}$$

ile gösterelim ve

$$f_n(x) = \begin{cases} 1, & x \in A_n \\ 0, & x \in [0, 1] \setminus A_n \end{cases}$$

tanımlayalım.

**Her $f_n$ integrallenebilirdir.** $A_n$ sonlu bir kümedir. $f_n$ fonksiyonu, sıfır fonksiyonundan yalnız bu sonlu sayıda noktada ayrılır. Sonlu sayıda noktada değer değiştirmek integrallenebilirliği ve integrali etkilemediğinden (bkz. [Analiz 2](../analiz-2/riemann-integrallenebilirlik-olcutu.html#prp-olcut-deger-degistirme)) $f_n$ integrallenebilirdir ve $\int_0^1 f_n(x)\,dx = 0$'dır.

**Noktasal limit.** $x \in [0, 1]$ rasyonel olsun; $x = \dfrac{p}{m}$ yazalım. $n \ge m$ olan her $n$ için $x \in A_n$, yani $f_n(x) = 1$'dir; dolayısıyla $f_n(x) \to 1$. $x$ irrasyonelse hiçbir $A_n$'ye ait değildir ve her $n$ için $f_n(x) = 0$'dır; dolayısıyla $f_n(x) \to 0$. Noktasal limit

$$f(x) = \begin{cases} 1, & x \in \mathbb{Q} \cap [0, 1] \\ 0, & x \in [0, 1] \setminus \mathbb{Q} \end{cases}$$

Dirichlet fonksiyonudur.

**Limit integrallenemez.** Dirichlet fonksiyonu $[0, 1]$ üzerinde Riemann integrallenebilir değildir (bkz. [Analiz 2](../analiz-2/riemann-integrallenebilirlik-olcutu.html#exm-dirichlet-integrallenemez)).

Öyleyse integrallenebilir fonksiyonların noktasal limiti integrallenebilir olmayabilir. [$\blacksquare$]{.qed}
:::
::::

:::: {#exm-nok-sinirlilik-bozulur name="Sınırlı Fonksiyonların Sınırsız Noktasal Limiti"}
$(0, 1]$ üzerinde sınırlı fonksiyonlardan oluşan, ama noktasal limiti sınırlı olmayan bir fonksiyon dizisi veriniz.

::: {.cozum}
$(0, 1]$ üzerinde $f_n(x) = \dfrac{n}{1 + nx}$ alalım. $x > 0$ için $1 + nx > 1$ olduğundan

$$0 < f_n(x) = \frac{n}{1 + nx} < n$$

olur; her $f_n$ sınırlıdır (sınır $n$'ye bağlıdır). Noktasal limit için pay ve paydayı $n$ ile bölelim:

$$\lim_{n \to \infty} \frac{n}{1 + nx} = \lim_{n \to \infty} \frac{1}{\dfrac{1}{n} + x} = \frac{1}{x}.$$

Noktasal limit $f(x) = \dfrac{1}{x}$ fonksiyonudur ve $(0, 1]$ üzerinde sınırlı değildir: $x \to 0^+$ iken $\dfrac{1}{x} \to +\infty$ olur. [$\blacksquare$]{.qed}
:::
::::

Üç örneğin ortak dersi şudur: noktasal yakınsaklık, limit fonksiyonu hakkında çok az bilgi taşır. Sorunun kaynağı, yakınsama hızının noktadan noktaya sınırsızca yavaşlayabilmesidir.

## Alıştırmalar

:::: {#exr-nok-rasyonel-kuvvet name="Üç Parçalı Bir Noktasal Limit"}
$E = [0, +\infty)$ üzerinde $f_n(x) = \dfrac{x^n}{1 + x^n}$ ile tanımlı dizinin noktasal limitini bulunuz.

::: {.cozum}
$x \ge 0$ sabit olsun. $(x^n)$ geometrik dizisinin davranışı $x$'in $1$'e göre konumuna bağlıdır; üç durumu ayıralım.

- $0 \le x < 1$ ise $x^n \to 0$ olur. Dolayısıyla $f_n(x) \to \dfrac{0}{1 + 0} = 0$.
- $x = 1$ ise her $n$ için $f_n(1) = \dfrac{1}{1 + 1} = \dfrac{1}{2}$'dir. Dolayısıyla $f_n(1) \to \dfrac{1}{2}$.
- $x > 1$ ise $x^n \to +\infty$ olur. Pay ve paydayı $x^n$ ile bölelim:
$$f_n(x) = \frac{1}{\dfrac{1}{x^n} + 1} \to \frac{1}{0 + 1} = 1.$$

Dizi $[0, +\infty)$ üzerinde noktasal yakınsaktır ve limiti

$$f(x) = \begin{cases} 0, & 0 \le x < 1 \\[1mm] \dfrac{1}{2}, & x = 1 \\[1mm] 1, & x > 1 \end{cases}$$

fonksiyonudur. Her $f_n$ sürekli olduğu hâlde $f$, $x = 1$ noktasında süreksizdir. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-nok-nx-bolu name="Sıfırda Sıçrayan Bir Limit"}
$E = [0, 1]$ üzerinde $f_n(x) = \dfrac{nx}{1 + nx}$ ile tanımlı dizinin noktasal limitini bulunuz ve $0 < x \le 1$ için $N(\varepsilon, x)$ sayısını belirleyiniz.

::: {.cozum}
$x = 0$ için her $n$'de $f_n(0) = 0$'dır; $f_n(0) \to 0$. $0 < x \le 1$ için pay ve paydayı $n$ ile bölelim:

$$f_n(x) = \frac{x}{\dfrac{1}{n} + x} \to \frac{x}{x} = 1.$$

Noktasal limit

$$f(x) = \begin{cases} 0, & x = 0 \\ 1, & 0 < x \le 1 \end{cases}$$

fonksiyonudur.

**$N$ sayısı.** $0 < x \le 1$ ve $\varepsilon > 0$ verilsin.

$$|f_n(x) - 1| = \left| \frac{nx}{1 + nx} - 1 \right| = \frac{1}{1 + nx} < \frac{1}{nx}$$

olduğundan $\dfrac{1}{nx} < \varepsilon$, yani $n > \dfrac{1}{\varepsilon x}$ olması yeter. $N(\varepsilon, x) = \left\lfloor \dfrac{1}{\varepsilon x} \right\rfloor + 1$ seçilir. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-nok-isaret-degistiren name="Tek Noktada Yakınsayan Bir Dizi"}
$E = \mathbb{R}$ üzerinde $f_n(x) = (-1)^n x$ ile tanımlı dizinin hangi noktalarda yakınsadığını bulunuz.

::: {.cozum}
$x = 0$ için her $n$'de $f_n(0) = 0$'dır; dizi bu noktada $0$'a yakınsar.

$x \ne 0$ olsun. $\big(f_n(x)\big) = (-x,\ x,\ -x,\ x,\ \dots)$ dizisinin çift indisli terimleri $x$, tek indisli terimleri $-x$ sabitidir. İki alt dizi farklı limitlere ($x \ne -x$) yakınsadığından dizi ıraksaktır.

Öyleyse $(f_n)$ yalnız $x = 0$ noktasında yakınsar; $\mathbb{R}$ üzerinde noktasal yakınsak değildir. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-nok-arctan name="Arktanjantla İşaret Fonksiyonu"}
$E = \mathbb{R}$ üzerinde $f_n(x) = \arctan(nx)$ ile tanımlı dizinin noktasal limitini bulunuz. Limit fonksiyonu sürekli midir?

::: {.cozum}
$x$ sabit olsun.

- $x = 0$ için $f_n(0) = \arctan 0 = 0$; limit $0$'dır.
- $x > 0$ için $n \to \infty$ iken $nx \to +\infty$ olur ve $\lim_{t \to +\infty} \arctan t = \dfrac{\pi}{2}$ olduğundan $f_n(x) \to \dfrac{\pi}{2}$.
- $x < 0$ için $nx \to -\infty$ olur ve $\lim_{t \to -\infty} \arctan t = -\dfrac{\pi}{2}$ olduğundan $f_n(x) \to -\dfrac{\pi}{2}$.

Noktasal limit

$$f(x) = \begin{cases} -\dfrac{\pi}{2}, & x < 0 \\[1mm] 0, & x = 0 \\[1mm] \dfrac{\pi}{2}, & x > 0 \end{cases}$$

fonksiyonudur. Sağdan limit $\dfrac{\pi}{2}$, soldan limit $-\dfrac{\pi}{2}$ olduğundan $f$, $x = 0$ noktasında sürekli değildir; oysa her $f_n$ bütün $\mathbb{R}$'de süreklidir. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-nok-kubik name="Parametreli Bir Rasyonel Dizi"}
$a > 0$ olmak üzere $E = [a, +\infty)$ üzerinde $f_n(x) = \dfrac{7n^3x}{3 + n^3x^2}$ ile tanımlı dizinin noktasal limitini bulunuz.

::: {.cozum}
$x \ge a > 0$ sabit olsun. Pay ve paydayı $n^3$ ile bölelim:

$$\lim_{n \to \infty} \frac{7n^3x}{3 + n^3x^2} = \lim_{n \to \infty} \frac{7x}{\dfrac{3}{n^3} + x^2} = \frac{7x}{x^2} = \frac{7}{x}.$$

Öyleyse $f_n \to f$ (noktasal, $[a, +\infty)$) ve $f(x) = \dfrac{7}{x}$'tir. Bu yakınsamanın düzgün olup olmadığı @exr-dzg-kubik alıştırmasında incelenir. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-nok-toplam-carpim name="Cebirsel Özelliklerle Limit"}
$E = [0, 1)$ üzerinde $h_n(x) = \left(x^n + \dfrac{x}{n}\right)\left(3 + \dfrac{nx}{1 + nx}\right)$ ile tanımlı dizinin noktasal limitini @thm-nok-cebir yardımıyla bulunuz.

::: {.cozum}
$[0, 1)$ üzerinde $x^n \to 0$ (@exm-nok-xn) ve $\dfrac{x}{n} \to 0$ (@exm-nok-x-bolu-n) noktasal yakınsar. @thm-nok-cebir (i) gereği birinci çarpan $x^n + \dfrac{x}{n} \to 0$ noktasal yakınsar.

İkinci çarpanda $\dfrac{nx}{1 + nx}$ dizisi, @exr-nok-nx-bolu gereği $x = 0$'da $0$'a, $0 < x < 1$ için $1$'e yakınsar. Sabit $3$ dizisiyle toplanınca ikinci çarpanın noktasal limiti

$$g(x) = \begin{cases} 3, & x = 0 \\ 4, & 0 < x < 1 \end{cases}$$

olur. @thm-nok-cebir (iii) gereği çarpımın noktasal limiti, limitlerin çarpımıdır: $h_n \to 0 \cdot g = 0$ (noktasal, $[0, 1)$). [$\blacksquare$]{.qed}
:::
::::

Noktasal yakınsaklığın sürekliliği, integrallenebilirliği ve sınırlılığı koruyamadığını gördük. Bu eksikliği gideren, $N$ sayısının $x$'ten bağımsız seçilebilmesini isteyen daha güçlü kavramı [Düzgün Yakınsaklık](duzgun-yakinsaklik.qmd) bölümünde tanımlıyoruz.
