project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Olasılık Teorisi"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Olasılık Uzayları"
      chapters:
        - deney-ornek-uzay-olaylar.qmd
        - sigma-cebirler.qmd
        - olasilik-olcusu-ve-uzayi.qmd
        - olasilik-uzayi-ornekleri.qmd
        - sayma-teknikleri.qmd
        - kosullu-olasilik-ve-bayes.qmd
        - bagimsiz-olaylar.qmd

    - part: "Rastgele Değişkenler"
      chapters:
        - rastgele-degisken.qmd
        - dagilim-fonksiyonu.qmd
        - kesikli-rastgele-degiskenler.qmd
        - surekli-rastgele-degiskenler.qmd
        - rastgele-degiskenin-donusumu.qmd

    - part: "Rastgele Vektörler"
      chapters:
        - rastgele-vektorler-ve-ortak-dagilimlar.qmd
        - bagimsizlik-ve-kosullu-dagilimlar.qmd
        - rastgele-vektorlerin-donusumleri.qmd

    - part: "Beklenen Değer"
      chapters:
        - beklenen-deger-ve-varyans.qmd
        - karakteristik-ve-moment-ureten-fonksiyonlar.qmd
        - rastgele-vektorlerde-beklenen-deger.qmd
        - kosullu-beklenen-deger.qmd

    - part: "Önemli Dağılımlar"
      chapters:
        - bernoulli-ve-binom-dagilimlari.qmd
        - poisson-dagilimi.qmd
        - geometrik-negatif-binom-ve-hipergeometrik.qmd
        - temel-surekli-dagilimlar.qmd
