project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Kompleks Analiz"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Kompleks Sayılar"
      chapters:
        - kompleks-sayilar/cebirsel-yapi.qmd
        - kompleks-sayilar/vektorler-ve-modul.qmd
        - kompleks-sayilar/ustel-form.qmd
        - kompleks-sayilar/kokler.qmd
        - kompleks-sayilar/bolgeler.qmd

    - part: "Analitik Fonksiyonlar"
      chapters:
        - analitik-fonksiyonlar/fonksiyonlar-ve-tasvirler.qmd
        - analitik-fonksiyonlar/limitler-ve-sureklilik.qmd
        - analitik-fonksiyonlar/turev.qmd
        - analitik-fonksiyonlar/cauchy-riemann.qmd
        - analitik-fonksiyonlar/analitiklik.qmd
        - analitik-fonksiyonlar/harmonik-fonksiyonlar.qmd
        - analitik-fonksiyonlar/analitik-uzanim-ve-yansima.qmd

    - part: "Elemanter Fonksiyonlar"
      chapters:
        - elemanter-fonksiyonlar/ustel-fonksiyon.qmd
        - elemanter-fonksiyonlar/logaritma.qmd
        - elemanter-fonksiyonlar/kompleks-usler.qmd
        - elemanter-fonksiyonlar/trigonometrik-fonksiyonlar.qmd
        - elemanter-fonksiyonlar/hiperbolik-fonksiyonlar.qmd
        - elemanter-fonksiyonlar/ters-fonksiyonlar.qmd

    - part: "İntegraller"
      chapters:
        - integraller/reel-degiskenli-integraller.qmd
        - integraller/cevreler.qmd
        - integraller/cevre-integralleri.qmd
        - integraller/ust-sinirlar.qmd
        - integraller/ters-turevler.qmd

    - part: "Cauchy Teoremleri"
      chapters:
        - cauchy-teoremleri/cauchy-goursat.qmd
        - cauchy-teoremleri/basit-ve-cok-baglantili-domenler.qmd
        - cauchy-teoremleri/cauchy-integral-formulu.qmd
        - cauchy-teoremleri/liouville-ve-cebirin-temel-teoremi.qmd
        - cauchy-teoremleri/maksimum-modul-ilkesi.qmd

    - part: "Seriler"
      chapters:
        - seriler/diziler-ve-seriler.qmd
        - seriler/taylor-serileri.qmd
        - seriler/laurent-serileri.qmd
        - seriler/kuvvet-serilerinin-yakinsakligi.qmd
        - seriler/kuvvet-serileriyle-islemler.qmd

    - part: "Rezidüler ve Kutuplar"
      chapters:
        - rezidu/ayrik-tekil-noktalar-ve-rezidu.qmd
        - rezidu/cauchy-rezidu-teoremi.qmd
        - rezidu/tekil-nokta-turleri.qmd
        - rezidu/sifirlar-ve-kutuplar.qmd
        - rezidu/tekil-noktalarda-davranis.qmd

    - part: "Rezidü Uygulamaları"
      chapters:
        - uygulamalar/has-olmayan-integraller.qmd
        - uygulamalar/fourier-integralleri-ve-jordan-lemmasi.qmd
        - uygulamalar/girintili-yollar.qmd
        - uygulamalar/dal-kesimi-boyunca-integrasyon.qmd
        - uygulamalar/trigonometrik-integraller.qmd
        - uygulamalar/arguman-ilkesi-ve-rouche.qmd
        - uygulamalar/ters-laplace-donusumu.qmd
