project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Kompleks Analiz"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Kompleks Sayılar"
      chapters:
        - kompleks-sayilar/cebirsel-yapi.qmd
        - kompleks-sayilar/vektorler-ve-modul.qmd
        - kompleks-sayilar/ustel-form.qmd
        - kompleks-sayilar/kokler.qmd
        - kompleks-sayilar/bolgeler.qmd

    - part: "Analitik Fonksiyonlar"
      chapters:
        - analitik-fonksiyonlar/fonksiyonlar-ve-tasvirler.qmd
        - analitik-fonksiyonlar/limitler-ve-sureklilik.qmd
        - analitik-fonksiyonlar/turev.qmd
        - analitik-fonksiyonlar/cauchy-riemann.qmd
        - analitik-fonksiyonlar/analitiklik.qmd
        - analitik-fonksiyonlar/harmonik-fonksiyonlar.qmd
        - analitik-fonksiyonlar/analitik-uzanim-ve-yansima.qmd

    - part: "Elemanter Fonksiyonlar"
      chapters:
        - elemanter-fonksiyonlar/ustel-fonksiyon.qmd
        - elemanter-fonksiyonlar/logaritma.qmd
        - elemanter-fonksiyonlar/kompleks-usler.qmd
        - elemanter-fonksiyonlar/trigonometrik-fonksiyonlar.qmd
        - elemanter-fonksiyonlar/hiperbolik-fonksiyonlar.qmd
        - elemanter-fonksiyonlar/ters-fonksiyonlar.qmd

    - part: "İntegraller"
      chapters:
        - integraller/reel-degiskenli-integraller.qmd
        - integraller/cevreler.qmd
        - integraller/cevre-integralleri.qmd
        - integraller/ust-sinirlar.qmd
        - integraller/ters-turevler.qmd
