project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Matematiğin Temelleri"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Önermeler Mantığı"
      chapters:
        - 1-mantik/mantiga-giris.qmd
        - 1-mantik/onermeler-ve-dogruluk-tablolari.qmd
        - 1-mantik/baglaclar-ve-onermeler-cebiri.qmd
        - 1-mantik/totoloji-ve-celiski.qmd
        - 1-mantik/de-morgan-ve-sadelestirme.qmd
        - 1-mantik/kosullu-onerme.qmd
        - 1-mantik/mantiksal-gerektirme.qmd
        - 1-mantik/niceleme-mantigi.qmd
