project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Raslantı Süreçleri"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Stokastik Süreçler ve Temel Kavramlar"
      chapters:
        - 1-temeller/stokastik-surec-kavrami.qmd
        - 1-temeller/varis-sayma-erlang.qmd
        - 1-temeller/poisson-sureci.qmd

    - part: "Markov Zincirleri"
      chapters:
        - 2-markov-zincirleri/markov-zincirlerine-giris.qmd
        - 2-markov-zincirleri/olasilik-dagilimi-chapman-kolmogorov.qmd
        - 2-markov-zincirleri/durumlarin-siniflandirilmasi.qmd
        - 2-markov-zincirleri/yutucu-durumlar.qmd

    - part: "Regresyon ve Veri Modelleme"
      chapters:
        - 3-tahmin/basit-lineer-regresyon.qmd
        - 3-tahmin/donusturulebilir-modeller.qmd

    - part: "Zaman Serileri ve Tahmin Yöntemleri"
      chapters:
        - 4-zaman-serileri/otokorelasyon-ve-hatalar.qmd
        - 4-zaman-serileri/tabii-model-trend-mevsimsellik.qmd
        - 4-zaman-serileri/hareketli-ortalamalar.qmd
