project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Lineer Programlama"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Temel Kavramlar"
      chapters:
        - lineer-programlama-problemi.qmd
        - temel-cozumler-ve-konveks-kumeler.qmd
        - uc-noktalar-ve-grafik-yontem.qmd

    - part: "Simpleks Yöntemi"
      chapters:
        - simpleks-yontem.qmd
        - buyuk-m-yontemi.qmd
        - iki-faz-yontemi.qmd
        - sinirsiz-ve-alternatif-optimal-cozum.qmd
        - isaret-kisitlamasiz-degiskenler.qmd
        - sinirli-degiskenler.qmd

    - part: "Duyarlılık Analizi ve Dualite"
      chapters:
        - duyarlilik-analizi.qmd
        - dualite.qmd
        - dual-simpleks-algoritmasi.qmd

    - part: "Tam Sayılı Programlama"
      chapters:
        - dal-sinir-yontemi.qmd

    - alistirmalar.qmd
