project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Topoloji"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Mantık ve Küme Kuramı"
      chapters:
        - onermeler-mantigi.qmd
        - kumeler-ve-islemler.qmd
        - indisli-aileler-ve-kartezyen-carpim.qmd
        - fonksiyonlar.qmd
        - birebir-orten-ve-ters-goruntu.qmd

    - part: "Topolojik Uzaylar"
      chapters:
        - topoloji-tanimi-ve-ilk-ornekler.qmd
        - acik-kapali-kumeler-ve-tumleyen-topolojileri.qmd
        - baz-ve-alt-baz.qmd
        - sira-topolojisi.qmd
        - carpim-topolojisi.qmd
        - alt-uzay-topolojisi.qmd
