project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Python ile Bilimsel Hesaplama"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd
