project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Kısmi Diferansiyel Denklemler"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Temeller ve Sınıflandırma"
      chapters:
        - temeller/siniflandirma.qmd
        - temeller/cozum-turleri-ve-ornekler.qmd
        - temeller/yardimci-kosullar.qmd
        - temeller/dogrudan-integrasyon.qmd

    - part: "Birinci Mertebeden Lineer ve Kuazi-Lineer Denklemler"
      chapters:
        - 1-mertebe/denklem-kurma.qmd
        - 1-mertebe/lineer-sabit-katsayili.qmd
        - 1-mertebe/lineer-degisken-katsayili.qmd
        - 1-mertebe/lagrange-yontemi.qmd
        - 1-mertebe/kuazilineer-cauchy.qmd

    - part: "Birinci Mertebeden Lineer Olmayan Denklemler"
      chapters:
        - 2-nonlineer/integral-turleri.qmd
        - 2-nonlineer/uyumlu-sistemler.qmd
        - 2-nonlineer/charpit-yontemi.qmd
        - 2-nonlineer/charpit-ozel-durumlar.qmd
        - 2-nonlineer/nonlineer-cauchy.qmd

    - part: "İkinci Mertebeden Denklemler"
      chapters:
        - 3-ikinci-mertebe/operator-ve-superpozisyon.qmd
        - 3-ikinci-mertebe/carpanlara-ayrilan-denklemler.qmd
        - 3-ikinci-mertebe/hiperbolik-eliptik-parabolik.qmd
