project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "İntegral Calculus"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Çok Katlı İntegraller"
      chapters:
        - dikdortgen-bolgelerde-iki-katli-integraller.qmd
        - genel-bolgelerde-iki-katli-integraller.qmd
        - kutupsal-koordinatlarda-iki-katli-integraller.qmd
        - iki-katli-integralin-uygulamalari.qmd
        - yuzey-alani.qmd
        - uc-katli-integraller.qmd
        - silindirik-koordinatlarda-uc-katli-integraller.qmd
        - kuresel-koordinatlarda-uc-katli-integraller.qmd
        - cok-katli-integrallerde-degisken-degistirme.qmd

    - part: "Vektör Analizi"
      chapters:
        - vektor-alanlari.qmd
        - egrisel-integraller.qmd
        - egrisel-integraller-icin-temel-teorem.qmd
        - green-teoremi.qmd
        - rotasyonel-ve-diverjans.qmd
        - parametrik-yuzeyler-ve-alanlari.qmd
        - yuzey-integralleri.qmd
        - stokes-teoremi.qmd
        - diverjans-teoremi.qmd
