---
title: "Eğrisel İntegraller için Temel Teorem"
pagetitle: "Eğrisel İntegraller için Temel Teorem"
description: "Gradyan alanlarının eğrisel integralini uç noktalardaki değerlere indiren temel teorem, yoldan bağımsızlık ve kapalı yollar, yoldan bağımsız alanların konservatifliği, basit bağlantılı bölgelerde konservatiflik ölçütü, potansiyel fonksiyonun kısmi integrasyonla bulunması ve enerjinin korunumu yasası."
---

Tek değişkenli analizin temel teoremi, türevi sürekli olan bir $F$ fonksiyonu için

$$\int_a^b F'(x)\,dx = F(b) - F(a) \tag{1}$$

olduğunu söyler (bkz. [Analiz 2](../analiz-2/analizin-temel-teoremleri.html#thm-temel-teorem-birinci)). Türevin integralini bulmak için $F$'nin yalnız aralığın iki ucundaki değerlerini bilmek yeter; aradaki noktalarda ne olduğu önemli değildir.

İki ya da üç değişkenli bir $f$ fonksiyonunun gradyanı $\nabla f$, $f$'nin bir tür türevidir (bkz. [Analiz 4](../analiz-4/kismi-turevler.html#def-kis-gradyan)). Bu bölümde (1) eşitliğinin eğrisel integrallerdeki karşılığını kuracağız: bir gradyan alanının bir eğri boyunca integrali, $f$'nin eğrinin iki ucundaki değerlerinin farkıdır. Bu basit sonuçtan birkaç önemli soru doğar: Hangi alanların eğrisel integrali izlenen yola bağlı değildir? Bir alanın konservatif olup olmadığını nasıl anlarız ve potansiyel fonksiyonunu nasıl buluruz? "Konservatif" adı nereden gelir?

## Gradyan Alanlarının Eğrisel İntegrali

Önce teoremi ifade edip ispatlayalım, ardından onu iki örnekte kullanalım.

Bir $C$ eğrisi $\mathbf{r}(t)$, $a \le t \le b$ vektör fonksiyonuyla verilsin. $\mathbf{r}'$ sürekli ve hiçbir yerde sıfır değilse $C$'nin düzgün olduğunu hatırlayalım. $\mathbf{r}(a)$ eğrinin başlangıç noktası, $\mathbf{r}(b)$ bitiş noktasıdır. Sürekli bir $\mathbf{F}$ vektör alanının $C$ boyunca eğrisel integrali

$$\int_C \mathbf{F} \cdot d\mathbf{r} = \int_a^b \mathbf{F}(\mathbf{r}(t)) \cdot \mathbf{r}'(t)\,dt$$

ile tanımlanır (@def-egi-vektor-alani). Bir $f$ fonksiyonunun gradyanı olan $\nabla f$ alanına gradyan alanı (@def-val-gradyan-alani), $\mathbf{F} = \nabla f$ olan bir $f$ varsa $\mathbf{F}$'ye konservatif alan, $f$'ye de $\mathbf{F}$'nin potansiyel fonksiyonu denir (@def-val-konservatif).

:::: {#thm-tte-temel-teorem name="Eğrisel İntegraller için Temel Teorem"}
$C$, $\mathbf{r}(t)$, $a \le t \le b$ vektör fonksiyonuyla verilen düzgün bir eğri olsun. $f$ iki ya da üç değişkenli, türevlenebilir bir fonksiyon ve $\nabla f$ gradyanı $C$ üzerinde sürekli olsun. Bu durumda

$$\int_C \nabla f \cdot d\mathbf{r} = f(\mathbf{r}(b)) - f(\mathbf{r}(a))$$

olur.

```{=html}
<figure class="ders-grafik ders-grafik-dar">
<svg viewBox="22.0 12.0 402.0 390.0" role="img" aria-label="Quarter circles x^2 + y^2 = 1, 2, ..., 6 in the first quadrant, a point A on the circle f = 1 and a point B on the circle f = 4, joined by a short path C1 and by a long path C2 that goes out beyond the circle f = 6 and comes back">
  <g stroke="var(--academic-text)" stroke-width="1.1" opacity="0.5" fill="var(--academic-text)">
  <line x1="36.0" y1="354.5" x2="409.8" y2="354.5"/>
  <line x1="69.5" y1="388.0" x2="69.5" y2="26.0"/>
  <polygon points="409.8,354.5 401.8,351.0 401.8,358.0" stroke="none"/>
  <polygon points="69.5,26.0 66.0,34.0 73.0,34.0" stroke="none"/>
  </g>
  <g fill="var(--academic-text)" font-size="11" opacity="0.7">
  </g>
  <g fill="var(--academic-text)" font-size="11.5" font-style="italic" opacity="0.85">
  <text x="407.8" y="369.5" text-anchor="end"><tspan font-style="italic">x</tspan></text>
  <text x="76.5" y="35.0"><tspan font-style="italic">y</tspan></text>
  </g>
  <path d="M187.5,354.5 L187.5,352.4 L187.4,350.4 L187.3,348.3 L187.2,346.3 L187.1,344.2 L186.9,342.2 L186.6,340.1 L186.4,338.1 L186.0,336.0 L185.7,334.0 L185.3,332.0 L184.9,330.0 L184.5,328.0 L184.0,326.0 L183.5,324.0 L182.9,322.0 L182.3,320.0 L181.7,318.0 L181.1,316.1 L180.4,314.1 L179.7,312.2 L178.9,310.3 L178.1,308.4 L177.3,306.5 L176.4,304.6 L175.6,302.8 L174.6,300.9 L173.7,299.1 L172.7,297.3 L171.7,295.5 L170.6,293.7 L169.6,292.0 L168.5,290.2 L167.3,288.5 L166.2,286.8 L165.0,285.1 L163.7,283.5 L162.5,281.9 L161.2,280.2 L159.9,278.7 L158.6,277.1 L157.2,275.5 L155.8,274.0 L154.4,272.5 L152.9,271.1 L151.5,269.6 L150.0,268.2 L148.5,266.8 L146.9,265.4 L145.3,264.1 L143.8,262.8 L142.1,261.5 L140.5,260.3 L138.9,259.0 L137.2,257.8 L135.5,256.7 L133.8,255.5 L132.0,254.4 L130.3,253.4 L128.5,252.3 L126.7,251.3 L124.9,250.3 L123.1,249.4 L121.2,248.4 L119.4,247.6 L117.5,246.7 L115.6,245.9 L113.7,245.1 L111.8,244.3 L109.9,243.6 L107.9,242.9 L106.0,242.3 L104.0,241.7 L102.0,241.1 L100.0,240.5 L98.0,240.0 L96.0,239.5 L94.0,239.1 L92.0,238.7 L90.0,238.3 L88.0,238.0 L85.9,237.6 L83.9,237.4 L81.8,237.1 L79.8,236.9 L77.7,236.8 L75.7,236.7 L73.6,236.6 L71.6,236.5 L69.5,236.5" fill="none" stroke="var(--academic-text)" stroke-width="1.0" opacity="0.42" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M236.4,354.5 L236.4,351.6 L236.3,348.7 L236.1,345.8 L236.0,342.9 L235.7,340.0 L235.5,337.1 L235.1,334.2 L234.8,331.3 L234.3,328.4 L233.8,325.5 L233.3,322.7 L232.7,319.8 L232.1,317.0 L231.4,314.1 L230.7,311.3 L229.9,308.5 L229.1,305.7 L228.2,302.9 L227.3,300.2 L226.3,297.4 L225.3,294.7 L224.2,292.0 L223.1,289.3 L221.9,286.6 L220.7,284.0 L219.5,281.3 L218.2,278.7 L216.8,276.2 L215.5,273.6 L214.0,271.1 L212.5,268.6 L211.0,266.1 L209.5,263.6 L207.8,261.2 L206.2,258.8 L204.5,256.4 L202.8,254.1 L201.0,251.8 L199.2,249.5 L197.3,247.2 L195.4,245.0 L193.5,242.8 L191.5,240.7 L189.5,238.6 L187.5,236.5 L185.4,234.5 L183.3,232.5 L181.2,230.5 L179.0,228.6 L176.8,226.7 L174.5,224.8 L172.2,223.0 L169.9,221.2 L167.6,219.5 L165.2,217.8 L162.8,216.2 L160.4,214.5 L157.9,213.0 L155.4,211.5 L152.9,210.0 L150.4,208.5 L147.8,207.2 L145.3,205.8 L142.7,204.5 L140.0,203.3 L137.4,202.1 L134.7,200.9 L132.0,199.8 L129.3,198.7 L126.6,197.7 L123.8,196.7 L121.1,195.8 L118.3,194.9 L115.5,194.1 L112.7,193.3 L109.9,192.6 L107.0,191.9 L104.2,191.3 L101.3,190.7 L98.5,190.2 L95.6,189.7 L92.7,189.2 L89.8,188.9 L86.9,188.5 L84.0,188.3 L81.1,188.0 L78.2,187.9 L75.3,187.7 L72.4,187.6 L69.5,187.6" fill="none" stroke="var(--academic-text)" stroke-width="1.0" opacity="0.42" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M273.9,354.5 L273.9,350.9 L273.8,347.4 L273.6,343.8 L273.4,340.2 L273.1,336.7 L272.8,333.1 L272.4,329.6 L271.9,326.1 L271.4,322.5 L270.8,319.0 L270.1,315.5 L269.4,312.0 L268.6,308.5 L267.8,305.1 L266.9,301.6 L266.0,298.2 L265.0,294.7 L263.9,291.3 L262.7,288.0 L261.6,284.6 L260.3,281.3 L259.0,277.9 L257.6,274.6 L256.2,271.4 L254.7,268.1 L253.2,264.9 L251.6,261.7 L250.0,258.5 L248.3,255.4 L246.5,252.3 L244.7,249.2 L242.8,246.2 L240.9,243.2 L238.9,240.2 L236.9,237.3 L234.8,234.4 L232.7,231.5 L230.6,228.7 L228.3,225.9 L226.1,223.1 L223.7,220.4 L221.4,217.7 L219.0,215.1 L216.5,212.5 L214.0,210.0 L211.5,207.5 L208.9,205.0 L206.3,202.6 L203.6,200.3 L200.9,197.9 L198.1,195.7 L195.3,193.4 L192.5,191.3 L189.6,189.2 L186.7,187.1 L183.8,185.1 L180.8,183.1 L177.8,181.2 L174.8,179.3 L171.7,177.5 L168.6,175.7 L165.5,174.0 L162.3,172.4 L159.1,170.8 L155.9,169.3 L152.6,167.8 L149.4,166.4 L146.1,165.0 L142.7,163.7 L139.4,162.4 L136.0,161.3 L132.7,160.1 L129.3,159.0 L125.8,158.0 L122.4,157.1 L118.9,156.2 L115.5,155.4 L112.0,154.6 L108.5,153.9 L105.0,153.2 L101.5,152.6 L97.9,152.1 L94.4,151.6 L90.9,151.2 L87.3,150.9 L83.8,150.6 L80.2,150.4 L76.6,150.2 L73.1,150.1 L69.5,150.1" fill="none" stroke="var(--academic-text)" stroke-width="1.0" opacity="0.42" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M305.5,354.5 L305.5,350.4 L305.4,346.3 L305.2,342.1 L304.9,338.0 L304.6,333.9 L304.2,329.8 L303.7,325.7 L303.2,321.7 L302.6,317.6 L301.9,313.5 L301.2,309.5 L300.3,305.4 L299.5,301.4 L298.5,297.4 L297.5,293.4 L296.4,289.4 L295.2,285.5 L293.9,281.6 L292.6,277.7 L291.3,273.8 L289.8,269.9 L288.3,266.1 L286.7,262.3 L285.1,258.5 L283.4,254.8 L281.6,251.0 L279.8,247.4 L277.9,243.7 L275.9,240.1 L273.9,236.5 L271.8,233.0 L269.6,229.4 L267.4,226.0 L265.2,222.5 L262.8,219.1 L260.4,215.8 L258.0,212.5 L255.5,209.2 L252.9,206.0 L250.3,202.8 L247.6,199.7 L244.9,196.6 L242.1,193.5 L239.3,190.6 L236.4,187.6 L233.4,184.7 L230.5,181.9 L227.4,179.1 L224.3,176.4 L221.2,173.7 L218.0,171.1 L214.8,168.5 L211.5,166.0 L208.2,163.6 L204.9,161.2 L201.5,158.8 L198.0,156.6 L194.6,154.4 L191.0,152.2 L187.5,150.1 L183.9,148.1 L180.3,146.1 L176.6,144.2 L173.0,142.4 L169.2,140.6 L165.5,138.9 L161.7,137.3 L157.9,135.7 L154.1,134.2 L150.2,132.7 L146.3,131.4 L142.4,130.1 L138.5,128.8 L134.6,127.6 L130.6,126.5 L126.6,125.5 L122.6,124.5 L118.6,123.7 L114.5,122.8 L110.5,122.1 L106.4,121.4 L102.3,120.8 L98.3,120.3 L94.2,119.8 L90.1,119.4 L86.0,119.1 L81.9,118.8 L77.7,118.6 L73.6,118.5 L69.5,118.5" fill="none" stroke="var(--academic-text)" stroke-width="1.0" opacity="0.42" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M333.4,354.5 L333.3,349.9 L333.2,345.3 L333.0,340.7 L332.7,336.1 L332.4,331.5 L331.9,326.9 L331.4,322.3 L330.8,317.8 L330.1,313.2 L329.3,308.7 L328.5,304.2 L327.6,299.6 L326.6,295.1 L325.5,290.7 L324.4,286.2 L323.1,281.8 L321.8,277.4 L320.4,273.0 L319.0,268.6 L317.4,264.3 L315.8,259.9 L314.1,255.7 L312.4,251.4 L310.5,247.2 L308.6,243.0 L306.7,238.8 L304.6,234.7 L302.5,230.6 L300.3,226.6 L298.0,222.6 L295.7,218.6 L293.3,214.7 L290.8,210.8 L288.2,207.0 L285.6,203.2 L283.0,199.4 L280.2,195.7 L277.4,192.1 L274.6,188.5 L271.6,184.9 L268.6,181.4 L265.6,177.9 L262.5,174.6 L259.3,171.2 L256.1,167.9 L252.8,164.7 L249.4,161.5 L246.1,158.4 L242.6,155.4 L239.1,152.4 L235.5,149.4 L231.9,146.6 L228.3,143.8 L224.6,141.0 L220.8,138.4 L217.0,135.8 L213.2,133.2 L209.3,130.7 L205.4,128.3 L201.4,126.0 L197.4,123.7 L193.4,121.5 L189.3,119.4 L185.2,117.3 L181.0,115.4 L176.8,113.5 L172.6,111.6 L168.3,109.9 L164.1,108.2 L159.7,106.6 L155.4,105.0 L151.0,103.6 L146.6,102.2 L142.2,100.9 L137.8,99.6 L133.3,98.5 L128.9,97.4 L124.4,96.4 L119.8,95.5 L115.3,94.7 L110.8,93.9 L106.2,93.2 L101.7,92.6 L97.1,92.1 L92.5,91.6 L87.9,91.3 L83.3,91.0 L78.7,90.8 L74.1,90.7 L69.5,90.6" fill="none" stroke="var(--academic-text)" stroke-width="1.0" opacity="0.42" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M358.5,354.5 L358.5,349.5 L358.4,344.4 L358.1,339.4 L357.8,334.3 L357.4,329.3 L357.0,324.3 L356.4,319.3 L355.7,314.3 L355.0,309.3 L354.1,304.3 L353.2,299.3 L352.2,294.4 L351.1,289.5 L350.0,284.6 L348.7,279.7 L347.3,274.8 L345.9,270.0 L344.4,265.2 L342.8,260.4 L341.1,255.6 L339.3,250.9 L337.5,246.2 L335.6,241.6 L333.6,236.9 L331.5,232.3 L329.3,227.8 L327.0,223.3 L324.7,218.8 L322.3,214.4 L319.8,210.0 L317.3,205.6 L314.6,201.3 L311.9,197.1 L309.1,192.9 L306.3,188.7 L303.3,184.6 L300.3,180.6 L297.3,176.5 L294.1,172.6 L290.9,168.7 L287.6,164.9 L284.3,161.1 L280.9,157.4 L277.4,153.7 L273.9,150.1 L270.3,146.6 L266.6,143.1 L262.9,139.7 L259.1,136.4 L255.3,133.1 L251.4,129.9 L247.5,126.7 L243.4,123.7 L239.4,120.7 L235.3,117.7 L231.1,114.9 L226.9,112.1 L222.7,109.4 L218.4,106.7 L214.0,104.2 L209.6,101.7 L205.2,99.3 L200.7,97.0 L196.2,94.7 L191.7,92.5 L187.1,90.4 L182.4,88.4 L177.8,86.5 L173.1,84.7 L168.4,82.9 L163.6,81.2 L158.8,79.6 L154.0,78.1 L149.2,76.7 L144.3,75.3 L139.4,74.0 L134.5,72.9 L129.6,71.8 L124.7,70.8 L119.7,69.9 L114.7,69.0 L109.7,68.3 L104.7,67.6 L99.7,67.0 L94.7,66.6 L89.7,66.2 L84.6,65.9 L79.6,65.6 L74.5,65.5 L69.5,65.5" fill="none" stroke="var(--academic-text)" stroke-width="1.0" opacity="0.42" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M106.0,242.3 L106.6,241.5 L107.3,240.5 L108.0,239.4 L108.7,238.2 L109.5,236.8 L110.4,235.4 L111.2,233.8 L112.1,232.2 L113.1,230.5 L114.1,228.8 L115.1,227.0 L116.2,225.1 L117.3,223.2 L118.5,221.4 L119.7,219.5 L120.9,217.6 L122.2,215.7 L123.5,213.9 L124.9,212.1 L126.3,210.4 L127.7,208.8 L129.2,207.2 L130.8,205.7 L132.3,204.3 L133.9,203.0 L135.6,201.9 L137.3,200.9 L139.0,200.0 L140.8,199.3 L142.7,198.7 L144.6,198.3 L146.5,198.0 L148.6,197.7 L150.7,197.6 L152.8,197.4 L155.1,197.4 L157.4,197.4 L159.7,197.5 L162.1,197.7 L164.6,198.0 L167.0,198.3 L169.6,198.6 L172.1,199.1 L174.7,199.6 L177.3,200.1 L179.9,200.8 L182.6,201.4 L185.3,202.2 L187.9,203.0 L190.6,203.8 L193.3,204.8 L196.0,205.7 L198.7,206.7 L201.4,207.8 L204.0,208.9 L206.7,210.1 L209.3,211.3 L211.9,212.6 L214.5,213.9 L217.0,215.3 L219.6,216.7 L222.2,218.4 L224.9,220.2 L227.7,222.1 L230.6,224.2 L233.5,226.4 L236.4,228.7 L239.3,231.1 L242.3,233.6 L245.3,236.1 L248.3,238.7 L251.3,241.4 L254.3,244.1 L257.2,246.8 L260.1,249.4 L263.0,252.1 L265.8,254.8 L268.6,257.4 L271.3,260.0 L273.9,262.5 L276.4,265.0 L278.9,267.3 L281.2,269.6 L283.4,271.8 L285.5,273.8 L287.5,275.7 L289.4,277.4 L291.0,279.0 L292.6,280.4 L293.9,281.6" fill="none" stroke="var(--color-practice)" stroke-width="2.1" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M106.0,242.3 L105.5,241.0 L105.0,239.6 L104.3,238.1 L103.5,236.5 L102.6,234.7 L101.6,232.8 L100.6,230.8 L99.5,228.7 L98.4,226.5 L97.2,224.3 L96.0,221.9 L94.7,219.5 L93.5,217.0 L92.3,214.5 L91.1,211.9 L90.0,209.2 L88.9,206.6 L87.8,203.9 L86.8,201.1 L85.9,198.4 L85.1,195.6 L84.4,192.9 L83.8,190.1 L83.3,187.4 L82.9,184.7 L82.7,182.0 L82.7,179.3 L82.8,176.7 L83.1,174.1 L83.7,171.6 L84.3,169.0 L85.1,166.3 L86.0,163.5 L87.1,160.6 L88.2,157.6 L89.4,154.5 L90.8,151.4 L92.2,148.2 L93.8,145.0 L95.4,141.8 L97.2,138.5 L99.0,135.3 L100.9,132.0 L102.9,128.8 L104.9,125.7 L107.0,122.6 L109.2,119.5 L111.5,116.6 L113.8,113.7 L116.2,111.0 L118.7,108.4 L121.2,105.9 L123.7,103.6 L126.3,101.4 L128.9,99.4 L131.6,97.6 L134.3,96.0 L137.1,94.6 L139.9,93.5 L142.7,92.5 L145.5,91.8 L148.5,91.3 L151.7,90.8 L154.9,90.6 L158.2,90.4 L161.7,90.4 L165.2,90.6 L168.8,90.8 L172.4,91.2 L176.2,91.8 L180.0,92.4 L183.8,93.2 L187.7,94.0 L191.6,95.0 L195.5,96.2 L199.5,97.4 L203.5,98.7 L207.4,100.1 L211.4,101.7 L215.3,103.3 L219.3,105.0 L223.2,106.8 L227.0,108.7 L230.8,110.7 L234.6,112.8 L238.3,115.0 L242.0,117.2 L245.5,119.5 L249.0,121.9 L252.4,124.4 L255.8,127.0 L259.3,129.9 L262.9,133.1 L266.5,136.4 L270.3,140.0 L274.0,143.7 L277.8,147.7 L281.6,151.7 L285.5,156.0 L289.3,160.3 L293.1,164.7 L296.8,169.2 L300.5,173.7 L304.2,178.3 L307.8,182.9 L311.3,187.6 L314.6,192.2 L317.9,196.7 L321.1,201.3 L324.1,205.7 L326.9,210.1 L329.6,214.3 L332.1,218.5 L334.4,222.5 L336.4,226.3 L338.3,230.0 L339.9,233.4 L341.3,236.6 L342.4,239.6 L343.3,242.4 L343.8,245.0 L343.9,247.4 L343.8,249.7 L343.3,251.9 L342.6,253.9 L341.6,255.9 L340.3,257.8 L338.9,259.5 L337.2,261.2 L335.4,262.7 L333.4,264.2 L331.3,265.6 L329.0,266.9 L326.7,268.2 L324.3,269.4 L321.8,270.5 L319.3,271.5 L316.9,272.5 L314.4,273.4 L311.9,274.3 L309.5,275.2 L307.2,276.0 L305.0,276.8 L302.9,277.5 L300.9,278.2 L299.1,278.9 L297.5,279.6 L296.1,280.3 L294.9,280.9 L293.9,281.6" fill="none" stroke="var(--color-base)" stroke-width="2.1" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="152.8" y1="197.4" x2="155.3" y2="197.5" stroke="var(--color-practice)" stroke-width="2.1" opacity="1.0" stroke-linecap="round"/>
  <polygon points="162.1,197.7 153.5,201.0 153.7,193.9" fill="var(--color-practice)" opacity="1.0"/>
  <line x1="168.8" y1="90.8" x2="177.1" y2="92.1" stroke="var(--color-base)" stroke-width="2.1" opacity="1.0" stroke-linecap="round"/>
  <polygon points="183.8,93.2 174.9,95.4 176.0,88.3" fill="var(--color-base)" opacity="1.0"/>
  <circle cx="106.0" cy="242.3" r="4.2" fill="var(--academic-text)"/>
  <circle cx="293.9" cy="281.6" r="4.2" fill="var(--academic-text)"/>
  <text x="97.0" y="246.3" fill="var(--academic-text)" font-size="13" text-anchor="end" font-weight="600"><tspan font-style="italic">A</tspan></text>
  <text x="298.9" y="297.6" fill="var(--academic-text)" font-size="13" text-anchor="start" font-weight="600"><tspan font-style="italic">B</tspan></text>
  <text x="169.0" y="219.1" fill="var(--color-practice)" font-size="13" text-anchor="middle" font-weight="600"><tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">1</tspan><tspan dy="-3.5">&#8203;</tspan></text>
  <text x="319.7" y="135.0" fill="var(--color-base)" font-size="13" text-anchor="start" font-weight="600"><tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">2</tspan><tspan dy="-3.5">&#8203;</tspan></text>
  <rect x="171.2" y="336.8" width="31.2" height="13.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="186.9" y="346.2" fill="var(--academic-text)" font-size="10.5" text-anchor="middle"><tspan font-style="italic">f</tspan> = 1</text>
  <rect x="230.3" y="331.7" width="10.2" height="13.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="235.5" y="341.1" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">2</text>
  <rect x="267.6" y="327.7" width="10.2" height="13.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="272.8" y="337.1" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">3</text>
  <rect x="299.1" y="324.4" width="10.2" height="13.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="304.2" y="333.8" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">4</text>
  <rect x="326.8" y="321.5" width="10.2" height="13.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="331.9" y="330.9" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">5</text>
  <rect x="351.8" y="318.9" width="10.2" height="13.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="357.0" y="328.3" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">6</text>
  <text x="63.5" y="368.5" fill="var(--academic-text)" font-size="11" text-anchor="end">0</text>
</svg>
<figcaption><em>f</em>(<em>x</em>, <em>y</em>) = <em>x</em>² + <em>y</em>² fonksiyonunun <em>f</em> = 1, 2, …, 6 seviye eğrileri ve <em>A</em>'dan <em>B</em>'ye giden iki yol. <em>A</em> noktası <em>f</em> = 1, <em>B</em> noktası <em>f</em> = 4 eğrisi üzerindedir. <em>C</em><sub>2</sub> yolu <em>f</em> = 6 eğrisini aşıp geri dönse de iki yol boyunca ∫ ∇<em>f</em> · <em>d</em><strong>r</strong> = <em>f</em>(<em>B</em>) &#8722; <em>f</em>(<em>A</em>) = 4 &#8722; 1 = 3 olur: yükselirken toplanan değerler alçalırken geri verilir.</figcaption>
</figure>
```

::: {.ispat}
$f$ üç değişkenli olsun; iki değişkenli durumda $z$ terimlerini silmek yeter. $\mathbf{r}(t) = \langle x(t), y(t), z(t) \rangle$ yazalım. Eğrisel integralin tanımından ve iç çarpımı bileşenlerle yazarak

$$
\begin{aligned}
\int_C \nabla f \cdot d\mathbf{r} &= \int_a^b \nabla f(\mathbf{r}(t)) \cdot \mathbf{r}'(t)\,dt \\[1mm]
&= \int_a^b \left( \frac{\partial f}{\partial x} \frac{dx}{dt} + \frac{\partial f}{\partial y} \frac{dy}{dt} + \frac{\partial f}{\partial z} \frac{dz}{dt} \right) dt
\end{aligned}
$$

buluruz; kısmi türevler $\mathbf{r}(t)$ noktasında hesaplanır. Parantez içindeki toplam, zincir kuralına göre (bkz. [Analiz 4](../analiz-4/jacobi-matrisi-ve-zincir-kurali.html#thm-zin-zincir-kurali)) $t \mapsto f(\mathbf{r}(t))$ bileşke fonksiyonunun türevidir:

$$\frac{d}{dt} f(\mathbf{r}(t)) = \frac{\partial f}{\partial x} \frac{dx}{dt} + \frac{\partial f}{\partial y} \frac{dy}{dt} + \frac{\partial f}{\partial z} \frac{dz}{dt}.$$

$\nabla f$, $C$ üzerinde ve $\mathbf{r}'$, $[a, b]$ üzerinde sürekli olduğundan bu türev $[a, b]$ üzerinde süreklidir. Bu yüzden tek değişkenli temel teorem (1) uygulanabilir:

$$\int_C \nabla f \cdot d\mathbf{r} = \int_a^b \frac{d}{dt} f(\mathbf{r}(t))\,dt = f(\mathbf{r}(b)) - f(\mathbf{r}(a)).$$

[$\blacksquare$]{.qed}
:::
::::

Yani bir gradyan alanının eğrisel integrali, $f$'nin eğri boyunca **net değişimidir**. $C$ düzlemde $A(x_1, y_1)$ noktasından $B(x_2, y_2)$ noktasına gidiyorsa

$$\int_C \nabla f \cdot d\mathbf{r} = f(x_2, y_2) - f(x_1, y_1),$$

uzayda $A(x_1, y_1, z_1)$ noktasından $B(x_2, y_2, z_2)$ noktasına gidiyorsa

$$\int_C \nabla f \cdot d\mathbf{r} = f(x_2, y_2, z_2) - f(x_1, y_1, z_1)$$

olur. Konservatif bir alanın eğrisel integralini hesaplamak için potansiyel fonksiyonun yalnız uç noktalardaki değerleri yeter; eğrinin biçimi, uzunluğu ya da parametrelemesi hesaba girmez.

Teorem, art arda gelen sonlu sayıda düzgün parçadan oluşan eğriler, yani [Eğrisel İntegraller](egrisel-integraller.qmd) bölümündeki parçalı düzgün eğriler için de geçerlidir.

:::: {#cor-tte-parcali-duzgun name="Parçalı Düzgün Eğriler için Temel Teorem"}
$C$, bir $A$ noktasından bir $B$ noktasına giden parçalı düzgün bir eğri ve $\nabla f$, $C$ üzerinde sürekli olsun. Bu durumda

$$\int_C \nabla f \cdot d\mathbf{r} = f(B) - f(A)$$

olur.

::: {.ispat}
$C$ parçalı düzgün olduğundan, art arda gelen $C_1, C_2, \dots, C_n$ düzgün eğrilerinden oluşur: her parçanın bitiş noktası bir sonrakinin başlangıç noktasıdır. $C_k$'nin başlangıç noktasına $A_{k-1}$, bitiş noktasına $A_k$ diyelim; $A_0 = A$ ve $A_n = B$'dir. Parçalı düzgün bir eğri boyunca integral parçalar üzerindeki integrallerin toplamıdır. Her parçaya @thm-tte-temel-teorem uygulanırsa

$$
\begin{aligned}
\int_C \nabla f \cdot d\mathbf{r} &= \int_{C_1} \nabla f \cdot d\mathbf{r} + \dots + \int_{C_n} \nabla f \cdot d\mathbf{r} \\[1mm]
&= \big( f(A_1) - f(A_0) \big) + \big( f(A_2) - f(A_1) \big) + \dots \\[1mm]
&\quad + \big( f(A_n) - f(A_{n-1}) \big)
\end{aligned}
$$

bulunur. Her ara nokta bir kez artı, bir kez eksi işaretle geçtiğinden $f(A_1), \dots, f(A_{n-1})$ terimleri birbirini götürür ve geriye $f(A_n) - f(A_0) = f(B) - f(A)$ kalır. [$\blacksquare$]{.qed}
:::
::::

Teoremi önce her iki yoldan da hesaplanabilen bir örnekte deneyelim.

:::: {#exm-tte-sarmal name="Bir Sarmal Boyunca Gradyanın İntegrali"}
$f(x, y, z) = xy + z^2$ olsun ve $C$, $\mathbf{r}(t) = \langle \cos t, \sin t, t \rangle$, $0 \le t \le \pi$ sarmalı olsun. $\int_C \nabla f \cdot d\mathbf{r}$ integralini önce tanımdan, sonra temel teoremle hesaplayınız.

```{=html}
<figure class="ders-grafik ders-grafik-dar">
<svg viewBox="44.5 35.5 300.0 388.5" role="img" aria-label="A half turn of the helix (cos t, sin t, t) from A(1, 0, 0) up to B(-1, 0, pi) around the z axis, and the dashed straight segment from A to B">
  <path d="M293.7,347.1 L199.5,367.5" fill="none" stroke="var(--academic-text)" stroke-width="1.1" opacity="0.55" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="199.5" y1="367.5" x2="73.1" y2="394.8" stroke="var(--academic-text)" stroke-width="1.1" opacity="0.55" stroke-linecap="round"/>
  <polygon points="67.6,396.0 73.8,391.7 75.1,397.4" fill="var(--academic-text)" opacity="0.55"/>
  <text x="61.6" y="408.0" fill="var(--academic-text)" font-size="10" text-anchor="middle" font-style="italic">x</text>
  <path d="M133.5,338.4 L199.5,367.5" fill="none" stroke="var(--academic-text)" stroke-width="1.1" opacity="0.55" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="199.5" y1="367.5" x2="273.5" y2="400.2" stroke="var(--academic-text)" stroke-width="1.1" opacity="0.55" stroke-linecap="round"/>
  <polygon points="278.6,402.4 271.0,402.3 273.4,396.9" fill="var(--academic-text)" opacity="0.55"/>
  <text x="288.6" y="407.4" fill="var(--academic-text)" font-size="10" text-anchor="middle" font-style="italic">y</text>
  <line x1="199.5" y1="367.5" x2="199.5" y2="63.2" stroke="var(--academic-text)" stroke-width="1.1" opacity="0.55" stroke-linecap="round"/>
  <polygon points="199.5,57.6 202.4,64.6 196.5,64.6" fill="var(--academic-text)" opacity="0.55"/>
  <text x="189.5" y="54.6" fill="var(--academic-text)" font-size="10" text-anchor="middle" font-style="italic">z</text>
  <path d="M124.1,383.8 L125.0,382.8 L125.8,381.8 L126.7,380.7 L127.6,379.7 L128.5,378.7 L129.4,377.7 L130.4,376.6 L131.3,375.6 L132.3,374.5 L133.3,373.5 L134.3,372.4 L135.3,371.4 L136.4,370.3 L137.4,369.2 L138.5,368.2 L139.6,367.1 L140.7,366.0 L141.8,364.9 L143.0,363.8 L144.1,362.7 L145.3,361.6 L146.5,360.5 L147.6,359.4 L148.8,358.2 L150.1,357.1 L151.3,356.0 L152.5,354.8 L153.8,353.7 L155.0,352.5 L156.3,351.3 L157.6,350.2 L158.9,349.0 L160.2,347.8 L161.5,346.6 L162.8,345.4 L164.1,344.2 L165.5,343.0 L166.8,341.8 L168.2,340.6 L169.5,339.4 L170.9,338.2 L172.3,336.9 L173.7,335.7 L175.1,334.4 L176.4,333.2 L177.9,331.9 L179.3,330.6 L180.7,329.3 L182.1,328.1 L183.5,326.8 L184.9,325.5 L186.4,324.1 L187.8,322.8 L189.2,321.5 L190.7,320.2 L192.1,318.9 L193.5,317.5 L195.0,316.2 L196.4,314.8 L197.9,313.4 L199.3,312.1 L200.8,310.7 L202.2,309.3 L203.7,307.9 L205.1,306.5 L206.5,305.1 L208.0,303.7 L209.4,302.3 L210.9,300.9 L212.3,299.4 L213.7,298.0 L215.1,296.5 L216.6,295.1 L218.0,293.6 L219.4,292.2 L220.8,290.7 L222.2,289.2 L223.6,287.7 L225.0,286.2 L226.4,284.7 L227.8,283.2 L229.1,281.7 L230.5,280.2 L231.9,278.6 L233.2,277.1 L234.5,275.6 L235.9,274.0 L237.2,272.5 L238.5,270.9 L239.8,269.3 L241.1,267.8 L242.4,266.2 L243.7,264.6 L244.9,263.0 L246.2,261.4 L247.4,259.8 L248.6,258.2 L249.9,256.6 L251.1,255.0 L252.3,253.3 L253.4,251.7 L254.6,250.1 L255.7,248.4 L256.9,246.8 L258.0,245.1 L259.1,243.4 L260.2,241.8 L261.3,240.1 L262.3,238.4 L263.4,236.7 L264.4,235.1 L265.4,233.4 L266.4,231.7 L267.4,230.0 L268.4,228.3 L269.3,226.5 L270.3,224.8 L271.2,223.1 L272.1,221.4 L273.0,219.7 L273.8,217.9 L274.7,216.2 L275.5,214.4 L276.3,212.7 L277.1,211.0 L277.8,209.2 L278.6,207.4 L279.3,205.7 L280.0,203.9 L280.7,202.2 L281.4,200.4 L282.0,198.6 L282.7,196.8 L283.3,195.1 L283.9,193.3 L284.4,191.5 L285.0,189.7 L285.5,187.9 L286.0,186.1 L286.5,184.3 L286.9,182.5 L287.4,180.7 L287.8,178.9 L288.2,177.1 L288.6,175.3 L288.9,173.5 L289.2,171.7 L289.5,169.9 L289.8,168.1 L290.1,166.3 L290.3,164.4 L290.5,162.6 L290.7,160.8 L290.9,159.0 L291.1,157.2 L291.2,155.4 L291.3,153.5 L291.4,151.7 L291.4,149.9 L291.5,148.1 L291.5,146.3 L291.5,144.4 L291.4,142.6 L291.4,140.8 L291.3,139.0 L291.2,137.1 L291.1,135.3 L290.9,133.5 L290.8,131.7 L290.6,129.9 L290.4,128.1 L290.1,126.2 L289.9,124.4 L289.6,122.6 L289.3,120.8 L289.0,119.0 L288.6,117.2 L288.3,115.4 L287.9,113.6 L287.5,111.8 L287.0,110.0 L286.6,108.2 L286.1,106.4 L285.6,104.6 L285.1,102.8 L284.5,101.0 L284.0,99.2 L283.4,97.4 L282.8,95.7 L282.2,93.9 L281.5,92.1 L280.9,90.3 L280.2,88.6 L279.5,86.8 L278.8,85.0 L278.0,83.3 L277.2,81.5 L276.5,79.8 L275.7,78.0 L274.8,76.3" fill="none" stroke="var(--color-base)" stroke-width="2.2" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="271.2" y1="223.1" x2="274.7" y2="215.7" stroke="var(--color-base)" stroke-width="2.2" opacity="1.0" stroke-linecap="round"/>
  <polygon points="277.8,209.2 277.4,219.0 270.5,215.7" fill="var(--color-base)" opacity="1.0"/>
  <path d="M124.1,383.8 L274.8,76.3" fill="none" stroke="var(--color-practice)" stroke-width="1.9" stroke-dasharray="6 4" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="214.6" y1="199.3" x2="229.8" y2="168.1" stroke="var(--color-practice)" stroke-width="1.9" opacity="1.0" stroke-linecap="round"/>
  <polygon points="232.6,162.4 232.1,171.1 226.1,168.1" fill="var(--color-practice)" opacity="1.0"/>
  <path d="M274.8,76.3 L274.8,351.2" fill="none" stroke="var(--academic-text)" stroke-width="1.0" stroke-dasharray="4 3" opacity="0.45" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="274.8" cy="351.2" r="2.2" fill="var(--academic-text)"/>
  <path d="M124.1,383.8 L125.8,384.5 L127.6,385.2 L129.4,385.9 L131.3,386.6 L133.3,387.2 L135.3,387.9 L137.4,388.5 L139.6,389.1 L141.8,389.6 L144.1,390.2 L146.5,390.7 L148.8,391.2 L151.3,391.7 L153.8,392.1 L156.3,392.6 L158.9,393.0 L161.5,393.4 L164.1,393.7 L166.8,394.1 L169.5,394.4 L172.3,394.6 L175.1,394.9 L177.9,395.1 L180.7,395.3 L183.5,395.5 L186.4,395.6 L189.2,395.7 L192.1,395.8 L195.0,395.9 L197.9,395.9 L200.8,395.9 L203.7,395.9 L206.5,395.8 L209.4,395.7 L212.3,395.6 L215.1,395.5 L218.0,395.3 L220.8,395.1 L223.6,394.9 L226.4,394.7 L229.1,394.4 L231.9,394.1 L234.5,393.8 L237.2,393.4 L239.8,393.0 L242.4,392.6 L244.9,392.2 L247.4,391.7 L249.9,391.3 L252.3,390.8 L254.6,390.2 L256.9,389.7 L259.1,389.1 L261.3,388.5 L263.4,387.9 L265.4,387.3 L267.4,386.6 L269.3,386.0 L271.2,385.3 L273.0,384.6 L274.7,383.9 L276.3,383.1 L277.8,382.4 L279.3,381.6 L280.7,380.8 L282.0,380.0 L283.3,379.2 L284.4,378.4 L285.5,377.6 L286.5,376.7 L287.4,375.9 L288.2,375.0 L288.9,374.2 L289.5,373.3 L290.1,372.4 L290.5,371.5 L290.9,370.6 L291.2,369.8 L291.4,368.9 L291.5,368.0 L291.5,367.1 L291.4,366.2 L291.2,365.3 L290.9,364.4 L290.6,363.5 L290.1,362.6 L289.6,361.8 L289.0,360.9 L288.3,360.0 L287.5,359.2 L286.6,358.3 L285.6,357.5 L284.5,356.6 L283.4,355.8 L282.2,355.0 L280.9,354.2 L279.5,353.4 L278.0,352.7 L276.5,351.9 L274.8,351.2" fill="none" stroke="var(--academic-text)" stroke-width="1.0" stroke-dasharray="4 3" opacity="0.5" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="124.1" cy="383.8" r="4.2" fill="var(--academic-text)"/>
  <circle cx="274.8" cy="76.3" r="4.2" fill="var(--academic-text)"/>
  <rect x="62.6" y="366.8" width="55.0" height="13.0" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="115.1" y="375.8" fill="var(--academic-text)" font-size="10" text-anchor="end"><tspan font-style="italic">A</tspan>(1, 0, 0)</text>
  <rect x="281.3" y="60.3" width="60.0" height="13.0" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="283.8" y="69.3" fill="var(--academic-text)" font-size="10" text-anchor="start"><tspan font-style="italic">B</tspan>(&#8722;1, 0, <tspan font-style="italic">π</tspan>)</text>
  <text x="300.2" y="160.4" fill="var(--color-base)" font-size="12.5" text-anchor="start" font-weight="600"><tspan font-style="italic">C</tspan></text>
  <text x="192.5" y="380.5" fill="var(--academic-text)" font-size="10" text-anchor="end">O</text>
</svg>
<figcaption><em>C</em> sarmalı <em>A</em>(1, 0, 0) noktasından <em>B</em>(&#8722;1, 0, <em>π</em>) noktasına <em>z</em> ekseni çevresinde yarım tur atarak çıkar; zemindeki kesikli yay, sarmalın <em>xy</em>-düzlemindeki izdüşümüdür. Kesikli doğru parçası aynı iki noktayı birleştirir. Temel teoreme göre ∇<em>f</em> alanının bu iki yol boyunca integralleri eşittir.</figcaption>
</figure>
```

::: {.cozum}
**Tanımdan.** $\nabla f = \langle y, x, 2z \rangle$ ve $\mathbf{r}'(t) = \langle -\sin t, \cos t, 1 \rangle$'dir. Eğri üzerinde $x = \cos t$, $y = \sin t$, $z = t$ olduğundan, $\cos^2 t - \sin^2 t = \cos 2t$ özdeşliğiyle

$$
\begin{aligned}
\nabla f(\mathbf{r}(t)) \cdot \mathbf{r}'(t) &= \sin t\,(-\sin t) + \cos t \cos t + 2t \cdot 1 \\[1mm]
&= \cos 2t + 2t
\end{aligned}
$$

olur. Buradan

$$\int_C \nabla f \cdot d\mathbf{r} = \int_0^{\pi} (\cos 2t + 2t)\,dt = \Big[ \tfrac{1}{2} \sin 2t + t^2 \Big]_0^{\pi} = \pi^2$$

bulunur.

**Temel teoremle.** $\nabla f$ her yerde süreklidir ve $\mathbf{r}'(t)$ hiç sıfır olmadığından (üçüncü bileşeni $1$'dir) $C$ düzgündür. Başlangıç noktası $\mathbf{r}(0) = (1, 0, 0)$, bitiş noktası $\mathbf{r}(\pi) = (-1, 0, \pi)$'dir. @thm-tte-temel-teorem gereği

$$
\begin{aligned}
\int_C \nabla f \cdot d\mathbf{r} &= f(-1, 0, \pi) - f(1, 0, 0) \\[1mm]
&= (0 + \pi^2) - (0 + 0) = \pi^2
\end{aligned}
$$

olur. İki yol aynı sonucu verir; ikincisinde ne $\mathbf{r}'(t)$'yi ne de bir integrali hesaplamak gerekti. [$\blacksquare$]{.qed}
:::
::::

Temel teoremin asıl gücü, integrali tanımdan hesaplamanın zor ya da olanaksız olduğu durumlarda ortaya çıkar: eğri yalnız "parçalı düzgün" diye verilmiş olsa bile sonuç bulunabilir.

:::: {#exm-tte-kutle-cekimi name="Kütle Çekim Alanının Yaptığı İş"}
Orijindeki $M$ kütleli bir cismin, $\mathbf{x} = \langle x, y, z \rangle$ konumundaki $m$ kütleli bir parçacığa uyguladığı kütle çekim kuvveti

$$\mathbf{F}(\mathbf{x}) = -\frac{mMG}{|\mathbf{x}|^3}\,\mathbf{x}$$

alanıyla verilir. Parçacık $(3, 4, 12)$ noktasından $(2, 2, 0)$ noktasına parçalı düzgün bir $C$ eğrisi boyunca hareket ederken bu alanın yaptığı işi bulunuz.

::: {.cozum}
**Potansiyel fonksiyon.** Kütle çekim alanının konservatif olduğunu, ayrıca

$$f(x, y, z) = \frac{mMG}{\sqrt{x^2 + y^2 + z^2}}$$

için $\mathbf{F} = \nabla f$ olduğunu [Vektör Alanları](vektor-alanlari.qmd) bölümünde görmüştük. $\nabla f$, orijin dışında süreklidir.

**İş.** İş, kuvvet alanının eğrisel integralidir. $C$ orijinden geçmediği sürece @cor-tte-parcali-duzgun uygulanır:

$$
\begin{aligned}
W &= \int_C \mathbf{F} \cdot d\mathbf{r} = \int_C \nabla f \cdot d\mathbf{r} = f(2, 2, 0) - f(3, 4, 12) \\[1mm]
&= \frac{mMG}{\sqrt{2^2 + 2^2}} - \frac{mMG}{\sqrt{3^2 + 4^2 + 12^2}} \\[1mm]
&= mMG \left( \frac{1}{2\sqrt{2}} - \frac{1}{13} \right).
\end{aligned}
$$

Burada $\sqrt{8} = 2\sqrt{2}$ ve $\sqrt{169} = 13$'tür. Sonuç $C$'nin biçimine bağlı değildir. $1/(2\sqrt{2}) \approx 0{,}354$ sayısı $1/13 \approx 0{,}077$'den büyük olduğundan iş pozitiftir: parçacık, onu çeken kütleye yaklaşmıştır (orijine uzaklığı $13$'ten $2\sqrt{2}$'ye inmiştir). [$\blacksquare$]{.qed}
:::
::::

## Yoldan Bağımsızlık

Temel teoremin en önemli sonucu, gradyan alanlarında integralin izlenen yola bağlı olmamasıdır. Bunun genel bir alanda kendiliğinden gerçekleşmediğini bir örnekle görelim.

$\mathbf{F}(x, y) = -y\,\mathbf{i} + x\,\mathbf{j}$ alanını $(1, 0)$ noktasından $(-1, 0)$ noktasına üç farklı yoldan götürelim.

- Birim çemberin üst yarısı $\mathbf{r}(t) = \langle \cos t, \sin t \rangle$, $0 \le t \le \pi$ boyunca $\mathbf{F}(\mathbf{r}(t)) = \langle -\sin t, \cos t \rangle$ ve $\mathbf{r}'(t) = \langle -\sin t, \cos t \rangle$'dir. İç çarpım $\sin^2 t + \cos^2 t = 1$ olduğundan integral $\pi$'dir.
- Alt yarısı $\mathbf{r}(t) = \langle \cos t, -\sin t \rangle$, $0 \le t \le \pi$ boyunca $\mathbf{F}(\mathbf{r}(t)) = \langle \sin t, \cos t \rangle$ ve $\mathbf{r}'(t) = \langle -\sin t, -\cos t \rangle$'dir. İç çarpım $-\sin^2 t - \cos^2 t = -1$ olduğundan integral $-\pi$'dir.
- $x$ ekseni üzerindeki doğru parçası boyunca $y = 0$'dır; $\mathbf{F} = x\,\mathbf{j}$ ile hareket yönü $-\mathbf{i}$ birbirine dik olduğundan integral $0$'dır.

Uç noktalar aynı, sonuçlar farklı. Oysa bir gradyan alanında @cor-tte-parcali-duzgun bütün yollarda aynı $f(B) - f(A)$ değerini verir. Bu ayrımı adlandıralım.

::: {#def-tte-yoldan-bagimsizlik name="Yol ve Yoldan Bağımsızlık"}
Parçalı düzgün bir eğriye **yol** (path) denir. $\mathbf{F}$, bir $D$ kümesinde tanımlı ve sürekli bir vektör alanı olsun. $D$ içinde başlangıç noktaları aynı ve bitiş noktaları aynı olan her $C_1$ ve $C_2$ yolu için

$$\int_{C_1} \mathbf{F} \cdot d\mathbf{r} = \int_{C_2} \mathbf{F} \cdot d\mathbf{r}$$

oluyorsa $\int_C \mathbf{F} \cdot d\mathbf{r}$ integraline $D$'de **yoldan bağımsızdır** (independent of path) denir.
:::

Yani yoldan bağımsız bir integralin değeri yalnız yolun nereden başlayıp nerede bittiğine bağlıdır; aradaki güzergâh önemli değildir. Böyle bir integrali $D$ içinde $A$'dan $B$'ye giden herhangi bir yol boyunca, örneğin $D$'den çıkmıyorsa hesabı en kolay olan doğru parçası boyunca hesaplayabiliriz. Yukarıdaki $-y\,\mathbf{i} + x\,\mathbf{j}$ alanının integrali düzlemde yoldan bağımsız değildir.

:::: {#cor-tte-gradyan-yoldan-bagimsiz name="Konservatif Alanların İntegrali Yoldan Bağımsızdır"}
$\mathbf{F} = \nabla f$ ve $\nabla f$, $D$ üzerinde sürekli olsun. Bu durumda $\int_C \mathbf{F} \cdot d\mathbf{r}$ integrali $D$'de yoldan bağımsızdır.

::: {.ispat}
$C_1$ ve $C_2$, $D$ içinde aynı $A$ noktasından aynı $B$ noktasına giden iki yol olsun. @cor-tte-parcali-duzgun ikisine de uygulanırsa

$$\int_{C_1} \nabla f \cdot d\mathbf{r} = f(B) - f(A) = \int_{C_2} \nabla f \cdot d\mathbf{r}$$

bulunur. [$\blacksquare$]{.qed}
:::
::::

Yoldan bağımsızlığı kapalı eğrilerle de ifade edebiliriz.

::: {#def-tte-kapali-egri name="Kapalı Eğri"}
Bitiş noktası başlangıç noktasıyla çakışan eğriye **kapalı eğri** (closed curve) denir. $C$, $\mathbf{r}(t)$, $a \le t \le b$ ile verilmişse bu, $\mathbf{r}(b) = \mathbf{r}(a)$ demektir.
:::

Yani kapalı bir eğri boyunca hareket eden nokta, yola çıktığı yere geri döner. Çember, elips ve bir üçgenin kenarları kapalı eğrilerdir; bir doğru parçası ya da bir parabol yayı kapalı değildir.

Aşağıdaki ispatta eğrisel integralin iki kuralını kullanacağız. $C$ yolu, $C_1$ ile onun bitiş noktasından başlayan $C_2$'nin art arda izlenmesiyle oluşuyorsa integral toplanır:

$$\int_C \mathbf{F} \cdot d\mathbf{r} = \int_{C_1} \mathbf{F} \cdot d\mathbf{r} + \int_{C_2} \mathbf{F} \cdot d\mathbf{r}.$$

$-C$, aynı eğrinin ters yönde izlenmesidir ve $\int_{-C} \mathbf{F} \cdot d\mathbf{r} = -\int_C \mathbf{F} \cdot d\mathbf{r}$'dir (@prp-egi-yon).

:::: {#thm-tte-yoldan-bagimsizlik name="Yoldan Bağımsızlık ve Kapalı Yollar"}
$\mathbf{F}$, $D$ üzerinde sürekli bir vektör alanı olsun. $\int_C \mathbf{F} \cdot d\mathbf{r}$ integralinin $D$'de yoldan bağımsız olması için gerek ve yeter koşul, $D$ içindeki her kapalı $C$ yolu için

$$\int_C \mathbf{F} \cdot d\mathbf{r} = 0$$

olmasıdır.

```{=html}
<figure class="ders-grafik ders-grafik-genis">
<svg viewBox="29.0 9.0 699.0 263.0" role="img" aria-label="Two panels: a closed curve cut at a left point A and a right point B into an upper arc C1 from A to B and a lower arc C2 from B back to A; two paths from A to B, the upper one C1 and the lower one traversed backwards as -C2, together forming a closed path">
  <path d="M62.2,164.8 L62.2,162.5 L62.3,160.2 L62.6,158.0 L62.9,155.7 L63.4,153.5 L63.9,151.3 L64.6,149.1 L65.3,146.9 L66.1,144.7 L67.1,142.5 L68.1,140.4 L69.2,138.2 L70.4,136.1 L71.6,134.0 L73.0,132.0 L74.4,129.9 L75.9,127.9 L77.5,125.9 L79.2,123.9 L80.9,122.0 L82.7,120.0 L84.6,118.2 L86.6,116.3 L88.6,114.5 L90.7,112.7 L92.9,110.9 L95.2,109.2 L97.5,107.6 L99.9,105.9 L102.4,104.3 L104.9,102.8 L107.5,101.3 L110.2,99.8 L113.0,98.4 L115.8,97.1 L118.7,95.8 L121.6,94.6 L124.6,93.4 L127.6,92.3 L130.7,91.2 L133.9,90.2 L137.1,89.3 L140.3,88.5 L143.6,87.7 L146.9,87.0 L150.3,86.4 L153.7,85.8 L157.0,85.3 L160.5,84.9 L163.9,84.6 L167.3,84.3 L170.7,84.2 L174.2,84.0 L177.6,84.0 L181.0,84.0 L184.4,84.2 L187.8,84.3 L191.1,84.6 L194.5,84.9 L197.7,85.2 L201.0,85.7 L204.2,86.2 L207.4,86.7 L210.5,87.3 L213.6,87.9 L216.6,88.6 L219.6,89.3 L222.6,90.1 L225.5,90.9 L228.3,91.7 L231.1,92.6 L233.9,93.5 L236.6,94.4 L239.3,95.3 L241.9,96.3 L244.5,97.2 L247.0,98.2 L249.6,99.2 L252.1,100.2 L254.5,101.2 L257.0,102.2 L259.4,103.2 L261.8,104.3 L264.2,105.3 L266.7,106.3 L269.1,107.4 L271.5,108.4 L273.9,109.5 L276.3,110.5 L278.7,111.6 L281.1,112.7 L283.6,113.8 L286.0,114.9 L288.5,116.0 L291.0,117.2 L293.5,118.4 L296.0,119.6 L298.5,120.8 L301.1,122.1 L303.6,123.4 L306.1,124.8 L308.7,126.2 L311.2,127.6 L313.7,129.1 L316.2,130.6 L318.6,132.2 L321.0,133.9 L323.4,135.5 L325.8,137.3 L328.0,139.1 L330.3,141.0 L332.4,142.9 L334.4,144.9 L336.4,146.9 L338.3,149.0 L340.0,151.1 L341.7,153.3 L343.2,155.5 L344.5,157.8 L345.8,160.1 L346.9,162.5 L347.8,164.9 L348.5,167.3 L349.1,169.7 L349.5,172.2 L349.8,174.7 L349.8,177.2" fill="none" stroke="var(--color-practice)" stroke-width="2.1" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M349.8,177.2 L349.7,179.6 L349.4,182.1 L348.9,184.6 L348.2,187.0 L347.3,189.4 L346.2,191.8 L345.0,194.2 L343.5,196.5 L341.9,198.8 L340.1,201.0 L338.1,203.2 L336.0,205.3 L333.7,207.3 L331.3,209.3 L328.7,211.1 L326.0,213.0 L323.1,214.7 L320.2,216.3 L317.1,217.9 L313.9,219.3 L310.7,220.7 L307.3,222.0 L303.9,223.2 L300.5,224.3 L297.0,225.4 L293.4,226.3 L289.8,227.2 L286.2,227.9 L282.6,228.6 L279.0,229.2 L275.4,229.8 L271.7,230.2 L268.2,230.6 L264.6,231.0 L261.0,231.2 L257.5,231.5 L254.0,231.6 L250.6,231.8 L247.2,231.8 L243.8,231.9 L240.5,231.9 L237.3,231.9 L234.0,231.8 L230.9,231.8 L227.7,231.7 L224.6,231.6 L221.6,231.5 L218.6,231.4 L215.6,231.3 L212.6,231.2 L209.7,231.1 L206.8,231.0 L203.9,230.8 L201.0,230.7 L198.1,230.6 L195.3,230.5 L192.4,230.4 L189.5,230.3 L186.7,230.2 L183.8,230.0 L180.9,229.9 L178.0,229.8 L175.1,229.7 L172.1,229.5 L169.1,229.3 L166.2,229.2 L163.1,228.9 L160.1,228.7 L157.1,228.4 L154.0,228.2 L150.9,227.8 L147.8,227.4 L144.6,227.0 L141.5,226.6 L138.3,226.1 L135.2,225.5 L132.0,224.9 L128.9,224.2 L125.8,223.5 L122.6,222.7 L119.5,221.8 L116.5,220.9 L113.4,219.9 L110.4,218.8 L107.5,217.7 L104.5,216.5 L101.7,215.2 L98.9,213.9 L96.2,212.5 L93.6,211.0 L91.0,209.5 L88.5,207.9 L86.2,206.2 L83.9,204.5 L81.7,202.8 L79.6,200.9 L77.7,199.1 L75.8,197.2 L74.0,195.2 L72.4,193.2 L70.9,191.1 L69.5,189.1 L68.2,186.9 L67.1,184.8 L66.1,182.6 L65.2,180.4 L64.4,178.2 L63.7,176.0 L63.2,173.8 L62.8,171.5 L62.4,169.3 L62.2,167.0 L62.2,164.8" fill="none" stroke="var(--color-base)" stroke-width="2.1" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="201.0" y1="85.7" x2="206.9" y2="86.7" stroke="var(--color-practice)" stroke-width="2.1" opacity="1.0" stroke-linecap="round"/>
  <polygon points="213.6,87.9 204.6,89.9 205.9,82.9" fill="var(--color-practice)" opacity="1.0"/>
  <line x1="201.0" y1="230.7" x2="196.3" y2="230.5" stroke="var(--color-base)" stroke-width="2.1" opacity="1.0" stroke-linecap="round"/>
  <polygon points="189.5,230.3 198.2,227.0 197.9,234.2" fill="var(--color-base)" opacity="1.0"/>
  <circle cx="62.2" cy="164.8" r="4.2" fill="var(--academic-text)"/>
  <circle cx="349.8" cy="177.2" r="4.2" fill="var(--academic-text)"/>
  <text x="54.2" y="169.8" fill="var(--academic-text)" font-size="13" text-anchor="end" font-weight="600"><tspan font-style="italic">A</tspan></text>
  <text x="357.8" y="182.2" fill="var(--academic-text)" font-size="13" text-anchor="start" font-weight="600"><tspan font-style="italic">B</tspan></text>
  <text x="210.5" y="75.3" fill="var(--color-practice)" font-size="13" text-anchor="middle" font-weight="600"><tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">1</tspan><tspan dy="-3.5">&#8203;</tspan></text>
  <text x="192.4" y="254.4" fill="var(--color-base)" font-size="13" text-anchor="middle" font-weight="600"><tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">2</tspan><tspan dy="-3.5">&#8203;</tspan></text>
  <text x="201.0" y="32.0" fill="var(--academic-text)" font-size="11.5" text-anchor="middle" font-weight="600">(a)  <tspan font-style="italic">C</tspan> = <tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">1</tspan><tspan dy="-3.5">&#8203;</tspan> ardından <tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">2</tspan><tspan dy="-3.5">&#8203;</tspan></text>
  <path d="M430.0,180.0 L431.1,178.4 L432.3,176.5 L433.7,174.4 L435.1,172.1 L436.6,169.6 L438.2,166.9 L439.9,164.0 L441.7,160.9 L443.6,157.8 L445.6,154.5 L447.6,151.1 L449.7,147.6 L451.8,144.1 L454.0,140.5 L456.2,136.9 L458.5,133.3 L460.9,129.7 L463.3,126.2 L465.7,122.6 L468.1,119.2 L470.6,115.8 L473.1,112.6 L475.5,109.5 L478.0,106.5 L480.6,103.6 L483.1,101.0 L485.6,98.5 L488.1,96.3 L490.5,94.3 L493.0,92.5 L495.5,90.9 L498.0,89.5 L500.6,88.3 L503.3,87.1 L505.9,86.1 L508.7,85.2 L511.5,84.4 L514.3,83.7 L517.1,83.1 L520.0,82.6 L522.9,82.2 L525.8,81.9 L528.7,81.7 L531.6,81.5 L534.6,81.3 L537.5,81.3 L540.5,81.2 L543.4,81.2 L546.3,81.3 L549.3,81.4 L552.2,81.4 L555.1,81.5 L557.9,81.6 L560.8,81.7 L563.6,81.8 L566.3,81.9 L569.1,82.0 L571.8,82.0 L574.4,82.0 L577.0,82.0 L579.6,81.9 L582.1,81.9 L584.7,81.8 L587.2,81.7 L589.7,81.6 L592.2,81.6 L594.7,81.5 L597.2,81.4 L599.7,81.4 L602.1,81.4 L604.6,81.3 L607.0,81.4 L609.4,81.4 L611.8,81.5 L614.2,81.6 L616.5,81.7 L618.9,81.9 L621.2,82.1 L623.5,82.3 L625.7,82.6 L628.0,83.0 L630.2,83.4 L632.4,83.9 L634.6,84.4 L636.7,85.0 L638.8,85.7 L640.9,86.4 L643.0,87.2 L645.0,88.0 L647.0,89.0 L649.0,90.1 L651.0,91.3 L653.0,92.6 L655.0,94.1 L656.9,95.7 L658.9,97.4 L660.9,99.2 L662.9,101.1 L664.8,103.1 L666.7,105.1 L668.6,107.1 L670.5,109.2 L672.3,111.4 L674.1,113.5 L675.9,115.7 L677.6,117.8 L679.3,120.0 L680.9,122.1 L682.5,124.2 L684.1,126.2 L685.6,128.2 L687.0,130.1 L688.4,131.9 L689.7,133.6 L690.9,135.3 L692.1,136.8 L693.2,138.2 L694.2,139.4 L695.1,140.5 L696.0,141.5" fill="none" stroke="var(--color-practice)" stroke-width="2.1" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M430.0,180.0 L431.2,181.0 L432.6,182.3 L434.1,183.7 L435.7,185.3 L437.5,187.0 L439.3,188.8 L441.2,190.8 L443.3,192.9 L445.4,195.1 L447.6,197.4 L449.9,199.7 L452.3,202.1 L454.7,204.5 L457.2,206.9 L459.8,209.3 L462.3,211.7 L465.0,214.1 L467.6,216.5 L470.3,218.7 L473.0,221.0 L475.8,223.1 L478.5,225.1 L481.2,227.0 L484.0,228.8 L486.7,230.5 L489.4,232.0 L492.1,233.3 L494.8,234.4 L497.4,235.3 L500.0,236.0 L502.6,236.5 L505.2,236.8 L507.9,236.9 L510.6,236.8 L513.4,236.6 L516.1,236.2 L518.9,235.6 L521.8,235.0 L524.6,234.3 L527.5,233.4 L530.4,232.5 L533.3,231.5 L536.2,230.4 L539.1,229.3 L542.0,228.1 L544.9,226.9 L547.8,225.8 L550.7,224.6 L553.6,223.4 L556.5,222.3 L559.4,221.2 L562.2,220.1 L565.1,219.1 L567.9,218.2 L570.6,217.4 L573.4,216.6 L576.1,216.0 L578.8,215.5 L581.4,215.2 L584.0,215.0 L586.6,215.0 L589.1,215.1 L591.7,215.4 L594.3,215.9 L596.8,216.5 L599.3,217.2 L601.9,218.0 L604.4,218.9 L606.9,219.8 L609.4,220.8 L611.9,221.9 L614.4,223.0 L616.8,224.0 L619.2,225.1 L621.6,226.2 L624.0,227.2 L626.4,228.1 L628.7,229.0 L631.0,229.8 L633.3,230.6 L635.5,231.2 L637.7,231.6 L639.9,232.0 L642.0,232.1 L644.1,232.1 L646.2,231.9 L648.2,231.6 L650.2,230.9 L652.1,230.1 L654.0,229.0 L655.9,227.6 L657.7,225.9 L659.5,224.0 L661.3,221.7 L663.1,219.3 L664.9,216.6 L666.6,213.7 L668.3,210.7 L670.0,207.5 L671.6,204.1 L673.2,200.7 L674.8,197.1 L676.4,193.5 L677.9,189.8 L679.4,186.1 L680.8,182.4 L682.2,178.7 L683.6,175.1 L684.9,171.5 L686.1,167.9 L687.4,164.5 L688.5,161.2 L689.7,158.0 L690.7,155.0 L691.8,152.2 L692.7,149.6 L693.6,147.2 L694.5,145.0 L695.3,143.1 L696.0,141.5" fill="none" stroke="var(--color-base)" stroke-width="2.1" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="571.8" y1="82.0" x2="575.3" y2="82.0" stroke="var(--color-practice)" stroke-width="2.1" opacity="1.0" stroke-linecap="round"/>
  <polygon points="582.1,81.9 573.7,85.6 573.6,78.4" fill="var(--color-practice)" opacity="1.0"/>
  <line x1="573.4" y1="216.6" x2="568.7" y2="218.1" stroke="var(--color-base)" stroke-width="2.1" opacity="1.0" stroke-linecap="round"/>
  <polygon points="562.2,220.1 569.3,214.2 571.4,221.0" fill="var(--color-base)" opacity="1.0"/>
  <circle cx="430.0" cy="180.0" r="4.2" fill="var(--academic-text)"/>
  <circle cx="696.0" cy="141.5" r="4.2" fill="var(--academic-text)"/>
  <text x="422.0" y="185.0" fill="var(--academic-text)" font-size="13" text-anchor="end" font-weight="600"><tspan font-style="italic">A</tspan></text>
  <text x="704.0" y="146.5" fill="var(--academic-text)" font-size="13" text-anchor="start" font-weight="600"><tspan font-style="italic">B</tspan></text>
  <text x="577.0" y="70.0" fill="var(--color-practice)" font-size="13" text-anchor="middle" font-weight="600"><tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">1</tspan><tspan dy="-3.5">&#8203;</tspan></text>
  <text x="584.0" y="248.0" fill="var(--color-base)" font-size="13" text-anchor="middle" font-weight="600">&#8722;<tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">2</tspan><tspan dy="-3.5">&#8203;</tspan></text>
  <text x="563.0" y="32.0" fill="var(--academic-text)" font-size="11.5" text-anchor="middle" font-weight="600">(b)  <tspan font-style="italic">C</tspan> = <tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">1</tspan><tspan dy="-3.5">&#8203;</tspan> ardından &#8722;<tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">2</tspan><tspan dy="-3.5">&#8203;</tspan></text>
</svg>
<figcaption>(a) Kapalı bir <em>C</em> yolu, üzerindeki iki <em>A</em>, <em>B</em> noktasında ikiye ayrılır: <em>A</em>'dan <em>B</em>'ye giden <em>C</em><sub>1</sub> ve <em>B</em>'den <em>A</em>'ya dönen <em>C</em><sub>2</sub>. (b) <em>A</em>'dan <em>B</em>'ye giden iki yoldan <em>C</em><sub>1</sub>'i izleyip <em>C</em><sub>2</sub>'yi ters yönde (&#8722;<em>C</em><sub>2</sub>) geri dönmek kapalı bir yol verir.</figcaption>
</figure>
```

::: {.ispat}
**Yoldan bağımsızlıktan kapalı yollara.** İntegral $D$'de yoldan bağımsız ve $C$, $D$ içinde $\mathbf{r}(t)$, $a \le t \le b$ ile verilen kapalı bir yol olsun. Başlangıç noktası $A = \mathbf{r}(a) = \mathbf{r}(b)$ olsun ve bir $a < c < b$ için $B = \mathbf{r}(c)$ diyelim. $\mathbf{r}$'nin $[a, c]$ üzerindeki kısıtlaması $A$'dan $B$'ye giden bir $C_1$ yolu, $[c, b]$ üzerindeki kısıtlaması da $B$'den $A$'ya dönen bir $C_2$ yoludur; $C$, $C_1$ ile ardından gelen $C_2$'dir (şeklin (a) paneli). $-C_2$ yolu $A$'dan $B$'ye gider; yani $C_1$ ile $-C_2$'nin uç noktaları aynıdır ve yoldan bağımsızlıktan integralleri eşittir. Buna göre

$$
\begin{aligned}
\int_C \mathbf{F} \cdot d\mathbf{r} &= \int_{C_1} \mathbf{F} \cdot d\mathbf{r} + \int_{C_2} \mathbf{F} \cdot d\mathbf{r} \\[1mm]
&= \int_{C_1} \mathbf{F} \cdot d\mathbf{r} - \int_{-C_2} \mathbf{F} \cdot d\mathbf{r} = 0
\end{aligned}
$$

olur.

**Kapalı yollardan yoldan bağımsızlığa.** $D$ içindeki her kapalı yolda integral sıfır olsun. $C_1$ ve $C_2$, $D$ içinde $A$'dan $B$'ye giden iki yol olsun. $C_1$ ile ardından gelen $-C_2$'nin oluşturduğu $C$ yolu $A$'dan çıkıp yine $A$'ya döner, yani kapalıdır (şeklin (b) paneli). Varsayımdan

$$
\begin{aligned}
0 = \int_C \mathbf{F} \cdot d\mathbf{r} &= \int_{C_1} \mathbf{F} \cdot d\mathbf{r} + \int_{-C_2} \mathbf{F} \cdot d\mathbf{r} \\[1mm]
&= \int_{C_1} \mathbf{F} \cdot d\mathbf{r} - \int_{C_2} \mathbf{F} \cdot d\mathbf{r}
\end{aligned}
$$

ve buradan $\int_{C_1} \mathbf{F} \cdot d\mathbf{r} = \int_{C_2} \mathbf{F} \cdot d\mathbf{r}$ bulunur. [$\blacksquare$]{.qed}
:::
::::

@cor-tte-gradyan-yoldan-bagimsiz ile bu teorem birlikte şunu söyler: konservatif bir alanın her kapalı yol boyunca integrali sıfırdır. Fiziksel yorumu şudur: kütle çekim alanı ya da bir elektrik alanı gibi konservatif bir kuvvet alanı, bir cismi kapalı bir yol boyunca dolaştırıp başladığı yere getirdiğinde toplamda hiç iş yapmaz.

## Yoldan Bağımsız Alanlar Konservatiftir

Şimdi tersini soralım: integrali yoldan bağımsız olan her alan konservatif midir? Cevap evettir, ama tanım kümesinin iki özelliği olmalıdır.

Birinci özellik açıklıktır. $D$'nin her $P$ noktası için merkezi $P$ olan ve tamamen $D$'de kalan bir disk varsa $D$ **açık** kümedir (bkz. [Analiz 4](../analiz-4/acik-ve-kapali-kumeler.html#def-ack-acik-kume)). Açık bir küme sınır noktalarının hiçbirini içermez: $x^2 + y^2 < 1$ diski açıktır, $x^2 + y^2 \le 1$ diski açık değildir. İkinci özellik, kümenin tek parça olmasıdır.

::: {#def-tte-yol-baglantili name="Yol Bağlantılı Küme"}
$D$'nin herhangi iki noktası, tamamen $D$ içinde kalan bir yolla birleştirilebiliyorsa $D$ kümesine **yol bağlantılı** (path-connected) denir.
:::

Yani yol bağlantılı bir kümenin iki noktası arasında kümeden çıkmadan gidilebilir. İki ayrık diskin birleşimi yol bağlantılı değildir: bir diskten ötekine giden her yol aradaki boşluktan geçer. Açık kümeler için bu tanım, Analiz 4'teki bağlantılılık tanımına denktir (bkz. [Analiz 4](../analiz-4/kompakt-ve-baglantili-kumeler.html#def-kmp-baglantili)). Bu yüzden bu ve sonraki bölümlerde "bağlantılı" sözcüğünü yol bağlantılı anlamında kullanacağız. Açık ve bağlantılı bir kümeye **bölge** dendiğini de hatırlayalım (bkz. [Analiz 4](../analiz-4/kompakt-ve-baglantili-kumeler.html#def-kmp-bolge)).

:::: {#thm-tte-konservatif name="Yoldan Bağımsız Alan Konservatiftir"}
$\mathbf{F}$, açık ve bağlantılı bir $D$ bölgesinde sürekli bir vektör alanı olsun. $\int_C \mathbf{F} \cdot d\mathbf{r}$ integrali $D$'de yoldan bağımsızsa $\mathbf{F}$, $D$'de konservatiftir; yani $D$'de $\nabla f = \mathbf{F}$ olan bir $f$ fonksiyonu vardır.

::: {.ispat}
Düzlemdeki alanlar için ispatlayalım; uzaydaki ispat aynıdır, yalnız üçüncü bir doğru parçası eklenir. $\mathbf{F} = P\,\mathbf{i} + Q\,\mathbf{j}$ yazalım ve $D$'de sabit bir $(a, b)$ noktası seçelim. $D$'nin her $(x, y)$ noktası için

$$f(x, y) = \int_{(a, b)}^{(x, y)} \mathbf{F} \cdot d\mathbf{r}$$

tanımlayalım. Sağdaki integral, $D$ içinde $(a, b)$'den $(x, y)$'ye giden herhangi bir yol boyunca alınır. $D$ bağlantılı olduğundan böyle bir yol vardır; integral yoldan bağımsız olduğundan sonuç seçilen yola bağlı değildir. Demek ki $f$ iyi tanımlıdır. $f_x = P$ ve $f_y = Q$ olduğunu göstereceğiz.

```{=html}
<figure class="ders-grafik ders-grafik-genis">
<svg viewBox="22.0 9.0 717.0 297.0" role="img" aria-label="Two panels with a region D, a base point (a, b) and a disk around (x, y) inside D: a path C1 to (x1, y) followed by a horizontal segment C2 to (x, y); a path C1 to (x, y1) followed by a vertical segment C2 to (x, y)">
  <g stroke="var(--academic-text)" stroke-width="1.1" opacity="0.5" fill="var(--academic-text)">
  <line x1="36.0" y1="269.4" x2="366.4" y2="269.4"/>
  <line x1="58.6" y1="292.0" x2="58.6" y2="36.0"/>
  <polygon points="366.4,269.4 358.4,265.9 358.4,272.9" stroke="none"/>
  <polygon points="58.6,36.0 55.1,44.0 62.1,44.0" stroke="none"/>
  </g>
  <g fill="var(--academic-text)" font-size="11" opacity="0.7">
  </g>
  <g fill="var(--academic-text)" font-size="11.5" font-style="italic" opacity="0.85">
  <text x="364.4" y="284.4" text-anchor="end"><tspan font-style="italic">x</tspan></text>
  <text x="65.6" y="45.0"><tspan font-style="italic">y</tspan></text>
  </g>
  <polygon points="351.1,160.9 349.8,158.2 348.4,155.6 346.8,153.1 345.1,150.6 343.2,148.1 341.1,145.8 339.0,143.5 336.8,141.3 334.5,139.1 332.2,137.0 329.8,135.0 327.4,133.0 325.0,131.1 322.7,129.2 320.3,127.4 318.0,125.6 315.8,123.8 313.5,122.1 311.4,120.3 309.3,118.6 307.3,116.9 305.3,115.1 303.4,113.4 301.5,111.6 299.7,109.8 297.9,108.0 296.1,106.2 294.4,104.3 292.6,102.4 290.8,100.5 289.0,98.6 287.2,96.7 285.2,94.8 283.3,92.9 281.2,91.0 279.1,89.1 276.8,87.3 274.5,85.5 272.1,83.7 269.5,82.1 266.9,80.5 264.1,79.0 261.3,77.6 258.3,76.3 255.2,75.1 252.1,74.0 248.9,73.1 245.6,72.3 242.2,71.6 238.8,71.0 235.4,70.6 231.9,70.3 228.4,70.1 224.9,70.1 221.4,70.1 218.0,70.2 214.5,70.5 211.1,70.8 207.7,71.2 204.3,71.6 201.0,72.2 197.7,72.7 194.4,73.3 191.2,73.9 188.0,74.6 184.9,75.2 181.7,75.9 178.6,76.6 175.5,77.2 172.4,77.9 169.3,78.5 166.2,79.2 163.1,79.8 160.0,80.4 156.9,81.1 153.8,81.7 150.6,82.4 147.4,83.0 144.2,83.7 141.0,84.4 137.8,85.2 134.5,86.0 131.3,86.8 128.1,87.7 124.8,88.7 121.6,89.7 118.5,90.8 115.3,92.0 112.2,93.2 109.2,94.6 106.3,96.0 103.4,97.5 100.6,99.1 97.9,100.8 95.3,102.5 92.8,104.4 90.4,106.3 88.1,108.2 85.9,110.3 83.9,112.4 81.9,114.5 80.1,116.7 78.3,119.0 76.7,121.3 75.1,123.6 73.7,125.9 72.3,128.3 71.0,130.7 69.8,133.1 68.7,135.5 67.6,138.0 66.5,140.5 65.5,143.0 64.6,145.5 63.7,148.0 62.8,150.5 62.0,153.1 61.3,155.7 60.6,158.3 59.9,160.9 59.4,163.5 58.9,166.2 58.5,168.9 58.2,171.6 58.0,174.3 57.9,177.1 58.0,179.8 58.2,182.6 58.6,185.3 59.1,188.0 59.9,190.7 60.8,193.4 61.9,196.1 63.2,198.7 64.8,201.2 66.5,203.7 68.5,206.1 70.6,208.4 73.0,210.6 75.6,212.7 78.4,214.7 81.3,216.6 84.4,218.4 87.7,220.0 91.1,221.5 94.7,222.8 98.3,224.1 102.0,225.1 105.8,226.1 109.7,226.9 113.5,227.6 117.4,228.2 121.3,228.7 125.1,229.1 128.9,229.5 132.6,229.7 136.3,229.9 139.9,230.1 143.4,230.2 146.9,230.3 150.2,230.4 153.5,230.5 156.6,230.7 159.7,230.8 162.7,231.0 165.6,231.3 168.4,231.6 171.2,232.0 173.9,232.4 176.7,232.9 179.3,233.4 182.0,234.1 184.7,234.7 187.4,235.5 190.1,236.2 192.8,237.1 195.6,237.9 198.5,238.8 201.3,239.6 204.3,240.5 207.3,241.4 210.4,242.2 213.6,243.0 216.8,243.8 220.1,244.4 223.4,245.1 226.8,245.6 230.2,246.1 233.7,246.4 237.3,246.7 240.8,246.9 244.4,246.9 247.9,246.9 251.5,246.7 255.1,246.5 258.7,246.1 262.2,245.6 265.7,245.0 269.2,244.3 272.7,243.5 276.1,242.6 279.5,241.7 282.8,240.6 286.1,239.5 289.4,238.2 292.6,237.0 295.8,235.6 298.9,234.2 302.0,232.7 305.1,231.2 308.1,229.6 311.1,228.0 314.0,226.3 316.9,224.5 319.8,222.7 322.6,220.9 325.3,218.9 328.0,217.0 330.6,214.9 333.2,212.8 335.6,210.6 338.0,208.4 340.2,206.1 342.3,203.8 344.3,201.4 346.1,198.9 347.8,196.3 349.3,193.8 350.6,191.1 351.7,188.5 352.6,185.7 353.4,183.0 353.8,180.2 354.1,177.5 354.2,174.7 354.0,171.9 353.6,169.1 353.0,166.3 352.1,163.6" fill="var(--color-theory)" fill-opacity="0.1" stroke="var(--color-theory)" stroke-width="1.5"/>
  <polygon points="292.3,136.1 292.2,133.4 292.0,130.8 291.5,128.1 290.9,125.5 290.0,123.0 289.0,120.5 287.8,118.1 286.5,115.7 285.0,113.5 283.3,111.4 281.6,109.4 279.6,107.5 277.6,105.8 275.4,104.2 273.1,102.8 270.8,101.6 268.3,100.5 265.8,99.5 263.2,98.8 260.6,98.2 257.9,97.9 255.2,97.7 252.6,97.7 249.9,97.9 247.2,98.2 244.6,98.8 242.0,99.5 239.5,100.5 237.0,101.6 234.7,102.8 232.4,104.2 230.2,105.8 228.2,107.5 226.2,109.4 224.5,111.4 222.8,113.5 221.3,115.7 220.0,118.1 218.8,120.5 217.8,123.0 216.9,125.5 216.3,128.1 215.8,130.8 215.6,133.4 215.5,136.1 215.6,138.8 215.8,141.4 216.3,144.1 216.9,146.7 217.8,149.2 218.8,151.7 220.0,154.1 221.3,156.5 222.8,158.7 224.5,160.8 226.2,162.8 228.2,164.7 230.2,166.4 232.4,168.0 234.7,169.4 237.0,170.6 239.5,171.7 242.0,172.7 244.6,173.4 247.2,174.0 249.9,174.3 252.6,174.5 255.2,174.5 257.9,174.3 260.6,174.0 263.2,173.4 265.8,172.7 268.3,171.7 270.8,170.6 273.1,169.4 275.4,168.0 277.6,166.4 279.6,164.7 281.6,162.8 283.3,160.8 285.0,158.7 286.5,156.5 287.8,154.1 289.0,151.7 290.0,149.2 290.9,146.7 291.5,144.1 292.0,141.4 292.2,138.8" fill="var(--color-base)" fill-opacity="0.16" stroke="var(--color-base)" stroke-width="1.0"/>
  <path d="M117.5,222.9 L117.9,222.0 L118.4,221.0 L118.9,219.9 L119.4,218.6 L120.0,217.3 L120.6,215.8 L121.2,214.3 L121.9,212.7 L122.5,211.0 L123.2,209.2 L124.0,207.4 L124.7,205.6 L125.5,203.7 L126.3,201.8 L127.2,199.8 L128.1,197.9 L128.9,195.9 L129.9,194.0 L130.8,192.0 L131.7,190.1 L132.7,188.1 L133.7,186.3 L134.7,184.4 L135.8,182.6 L136.8,180.9 L137.9,179.2 L139.0,177.6 L140.1,176.1 L141.2,174.6 L142.3,173.3 L143.5,172.0 L144.7,170.8 L145.9,169.5 L147.2,168.4 L148.5,167.2 L149.8,166.0 L151.2,164.9 L152.6,163.8 L154.1,162.7 L155.5,161.7 L157.0,160.7 L158.5,159.7 L160.0,158.7 L161.5,157.8 L163.0,156.8 L164.6,155.9 L166.1,155.0 L167.7,154.2 L169.2,153.3 L170.8,152.5 L172.3,151.7 L173.9,150.9 L175.4,150.2 L176.9,149.4 L178.4,148.7 L179.9,148.0 L181.4,147.3 L182.9,146.7 L184.3,146.0 L185.7,145.4 L187.1,144.8 L188.6,144.2 L190.0,143.7 L191.5,143.2 L193.1,142.7 L194.6,142.2 L196.2,141.8 L197.7,141.3 L199.3,140.9 L200.9,140.6 L202.4,140.2 L204.0,139.9 L205.5,139.6 L207.1,139.3 L208.6,139.0 L210.0,138.7 L211.5,138.5 L212.9,138.3 L214.3,138.0 L215.7,137.8 L217.0,137.6 L218.2,137.4 L219.4,137.2 L220.6,137.1 L221.7,136.9 L222.7,136.7 L223.6,136.6 L224.5,136.4 L225.3,136.3 L226.0,136.1" fill="none" stroke="var(--color-practice)" stroke-width="2.0" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="166.1" y1="155.0" x2="166.7" y2="154.7" stroke="var(--color-practice)" stroke-width="2.0" opacity="1.0" stroke-linecap="round"/>
  <polygon points="172.3,151.7 166.9,158.5 163.7,152.5" fill="var(--color-practice)" opacity="1.0"/>
  <line x1="226.0" y1="136.1" x2="247.5" y2="136.1" stroke="var(--color-base)" stroke-width="2.4" opacity="1.0" stroke-linecap="round"/>
  <polygon points="253.9,136.1 245.9,139.5 245.9,132.7" fill="var(--color-base)" opacity="1.0"/>
  <circle cx="117.5" cy="222.9" r="3.6" fill="var(--academic-text)"/>
  <circle cx="226.0" cy="136.1" r="3.6" fill="var(--academic-text)"/>
  <circle cx="253.9" cy="136.1" r="3.6" fill="var(--academic-text)"/>
  <text x="121.5" y="237.9" fill="var(--academic-text)" font-size="11.5" text-anchor="start">(<tspan font-style="italic">a</tspan>, <tspan font-style="italic">b</tspan>)</text>
  <text x="102.0" y="98.9" fill="var(--color-theory)" font-size="14" text-anchor="middle" font-weight="600"><tspan font-style="italic">D</tspan></text>
  <rect x="178.8" y="116.9" width="43.8" height="14.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="220.0" y="127.1" fill="var(--academic-text)" font-size="11.5" text-anchor="end">(<tspan font-style="italic">x</tspan><tspan font-size="8.5" dy="3.5">1</tspan><tspan dy="-3.5">&#8203;</tspan>, <tspan font-style="italic">y</tspan>)</text>
  <rect x="260.4" y="129.9" width="39.5" height="14.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="262.9" y="140.1" fill="var(--academic-text)" font-size="11.5" text-anchor="start">(<tspan font-style="italic">x</tspan>, <tspan font-style="italic">y</tspan>)</text>
  <text x="144.7" y="154.7" fill="var(--color-practice)" font-size="13" text-anchor="end" font-weight="600"><tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">1</tspan><tspan dy="-3.5">&#8203;</tspan></text>
  <text x="240.3" y="154.1" fill="var(--color-base)" font-size="13" text-anchor="middle" font-weight="600"><tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">2</tspan><tspan dy="-3.5">&#8203;</tspan></text>
  <text x="201.2" y="32.0" fill="var(--academic-text)" font-size="11.5" text-anchor="middle" font-weight="600">(a)  yatay son parça</text>
  <g stroke="var(--academic-text)" stroke-width="1.1" opacity="0.5" fill="var(--academic-text)">
  <line x1="394.4" y1="269.4" x2="724.8" y2="269.4"/>
  <line x1="417.0" y1="292.0" x2="417.0" y2="36.0"/>
  <polygon points="724.8,269.4 716.8,265.9 716.8,272.9" stroke="none"/>
  <polygon points="417.0,36.0 413.5,44.0 420.5,44.0" stroke="none"/>
  </g>
  <g fill="var(--academic-text)" font-size="11" opacity="0.7">
  </g>
  <g fill="var(--academic-text)" font-size="11.5" font-style="italic" opacity="0.85">
  <text x="722.8" y="284.4" text-anchor="end"><tspan font-style="italic">x</tspan></text>
  <text x="424.0" y="45.0"><tspan font-style="italic">y</tspan></text>
  </g>
  <polygon points="709.5,160.9 708.2,158.2 706.8,155.6 705.2,153.1 703.5,150.6 701.6,148.1 699.5,145.8 697.4,143.5 695.2,141.3 692.9,139.1 690.6,137.0 688.2,135.0 685.8,133.0 683.4,131.1 681.1,129.2 678.7,127.4 676.4,125.6 674.2,123.8 671.9,122.1 669.8,120.3 667.7,118.6 665.7,116.9 663.7,115.1 661.8,113.4 659.9,111.6 658.1,109.8 656.3,108.0 654.5,106.2 652.8,104.3 651.0,102.4 649.2,100.5 647.4,98.6 645.6,96.7 643.6,94.8 641.7,92.9 639.6,91.0 637.5,89.1 635.2,87.3 632.9,85.5 630.5,83.7 627.9,82.1 625.3,80.5 622.5,79.0 619.7,77.6 616.7,76.3 613.6,75.1 610.5,74.0 607.3,73.1 604.0,72.3 600.6,71.6 597.2,71.0 593.8,70.6 590.3,70.3 586.8,70.1 583.3,70.1 579.8,70.1 576.4,70.2 572.9,70.5 569.5,70.8 566.1,71.2 562.7,71.6 559.4,72.2 556.1,72.7 552.8,73.3 549.6,73.9 546.4,74.6 543.3,75.2 540.1,75.9 537.0,76.6 533.9,77.2 530.8,77.9 527.7,78.5 524.6,79.2 521.5,79.8 518.4,80.4 515.3,81.1 512.2,81.7 509.0,82.4 505.8,83.0 502.6,83.7 499.4,84.4 496.2,85.2 492.9,86.0 489.7,86.8 486.5,87.7 483.2,88.7 480.0,89.7 476.9,90.8 473.7,92.0 470.6,93.2 467.6,94.6 464.7,96.0 461.8,97.5 459.0,99.1 456.3,100.8 453.7,102.5 451.2,104.4 448.8,106.3 446.5,108.2 444.3,110.3 442.3,112.4 440.3,114.5 438.5,116.7 436.7,119.0 435.1,121.3 433.5,123.6 432.1,125.9 430.7,128.3 429.4,130.7 428.2,133.1 427.1,135.5 426.0,138.0 424.9,140.5 423.9,143.0 423.0,145.5 422.1,148.0 421.2,150.5 420.4,153.1 419.7,155.7 419.0,158.3 418.3,160.9 417.8,163.5 417.3,166.2 416.9,168.9 416.6,171.6 416.4,174.3 416.3,177.1 416.4,179.8 416.6,182.6 417.0,185.3 417.5,188.0 418.3,190.7 419.2,193.4 420.3,196.1 421.6,198.7 423.2,201.2 424.9,203.7 426.9,206.1 429.0,208.4 431.4,210.6 434.0,212.7 436.8,214.7 439.7,216.6 442.8,218.4 446.1,220.0 449.5,221.5 453.1,222.8 456.7,224.1 460.4,225.1 464.2,226.1 468.1,226.9 471.9,227.6 475.8,228.2 479.7,228.7 483.5,229.1 487.3,229.5 491.0,229.7 494.7,229.9 498.3,230.1 501.8,230.2 505.3,230.3 508.6,230.4 511.9,230.5 515.0,230.7 518.1,230.8 521.1,231.0 524.0,231.3 526.8,231.6 529.6,232.0 532.3,232.4 535.1,232.9 537.7,233.4 540.4,234.1 543.1,234.7 545.8,235.5 548.5,236.2 551.2,237.1 554.0,237.9 556.9,238.8 559.7,239.6 562.7,240.5 565.7,241.4 568.8,242.2 572.0,243.0 575.2,243.8 578.5,244.4 581.8,245.1 585.2,245.6 588.6,246.1 592.1,246.4 595.7,246.7 599.2,246.9 602.8,246.9 606.3,246.9 609.9,246.7 613.5,246.5 617.1,246.1 620.6,245.6 624.1,245.0 627.6,244.3 631.1,243.5 634.5,242.6 637.9,241.7 641.2,240.6 644.5,239.5 647.8,238.2 651.0,237.0 654.2,235.6 657.3,234.2 660.4,232.7 663.5,231.2 666.5,229.6 669.5,228.0 672.4,226.3 675.3,224.5 678.2,222.7 681.0,220.9 683.7,218.9 686.4,217.0 689.0,214.9 691.6,212.8 694.0,210.6 696.4,208.4 698.6,206.1 700.7,203.8 702.7,201.4 704.5,198.9 706.2,196.3 707.7,193.8 709.0,191.1 710.1,188.5 711.0,185.7 711.8,183.0 712.2,180.2 712.5,177.5 712.6,174.7 712.4,171.9 712.0,169.1 711.4,166.3 710.5,163.6" fill="var(--color-theory)" fill-opacity="0.1" stroke="var(--color-theory)" stroke-width="1.5"/>
  <polygon points="650.7,136.1 650.6,133.4 650.4,130.8 649.9,128.1 649.3,125.5 648.4,123.0 647.4,120.5 646.2,118.1 644.9,115.7 643.4,113.5 641.7,111.4 640.0,109.4 638.0,107.5 636.0,105.8 633.8,104.2 631.5,102.8 629.2,101.6 626.7,100.5 624.2,99.5 621.6,98.8 619.0,98.2 616.3,97.9 613.6,97.7 611.0,97.7 608.3,97.9 605.6,98.2 603.0,98.8 600.4,99.5 597.9,100.5 595.4,101.6 593.1,102.8 590.8,104.2 588.6,105.8 586.6,107.5 584.6,109.4 582.9,111.4 581.2,113.5 579.7,115.7 578.4,118.1 577.2,120.5 576.2,123.0 575.3,125.5 574.7,128.1 574.2,130.8 574.0,133.4 573.9,136.1 574.0,138.8 574.2,141.4 574.7,144.1 575.3,146.7 576.2,149.2 577.2,151.7 578.4,154.1 579.7,156.5 581.2,158.7 582.9,160.8 584.6,162.8 586.6,164.7 588.6,166.4 590.8,168.0 593.1,169.4 595.4,170.6 597.9,171.7 600.4,172.7 603.0,173.4 605.6,174.0 608.3,174.3 611.0,174.5 613.6,174.5 616.3,174.3 619.0,174.0 621.6,173.4 624.2,172.7 626.7,171.7 629.2,170.6 631.5,169.4 633.8,168.0 636.0,166.4 638.0,164.7 640.0,162.8 641.7,160.8 643.4,158.7 644.9,156.5 646.2,154.1 647.4,151.7 648.4,149.2 649.3,146.7 649.9,144.1 650.4,141.4 650.6,138.8" fill="var(--color-base)" fill-opacity="0.16" stroke="var(--color-base)" stroke-width="1.0"/>
  <path d="M475.9,222.9 L476.7,222.6 L477.6,222.3 L478.6,222.0 L479.7,221.7 L480.9,221.4 L482.1,221.0 L483.4,220.6 L484.7,220.2 L486.1,219.8 L487.6,219.3 L489.1,218.9 L490.7,218.4 L492.3,217.9 L494.0,217.4 L495.7,216.9 L497.4,216.4 L499.1,215.8 L500.9,215.2 L502.7,214.7 L504.5,214.1 L506.3,213.4 L508.1,212.8 L509.9,212.2 L511.8,211.5 L513.6,210.9 L515.4,210.2 L517.2,209.5 L518.9,208.8 L520.7,208.1 L522.4,207.4 L524.1,206.7 L525.9,205.9 L527.7,205.1 L529.5,204.2 L531.4,203.3 L533.3,202.4 L535.2,201.5 L537.2,200.5 L539.1,199.6 L541.1,198.6 L543.1,197.6 L545.1,196.5 L547.1,195.5 L549.1,194.5 L551.1,193.4 L553.1,192.4 L555.0,191.4 L557.0,190.4 L558.9,189.3 L560.9,188.3 L562.8,187.3 L564.6,186.4 L566.5,185.4 L568.3,184.5 L570.0,183.6 L571.8,182.7 L573.5,181.8 L575.1,181.0 L576.7,180.2 L578.2,179.5 L579.7,178.8 L581.2,178.1 L582.6,177.4 L584.1,176.7 L585.5,176.0 L587.0,175.4 L588.4,174.7 L589.7,174.1 L591.1,173.5 L592.4,172.8 L593.8,172.2 L595.0,171.7 L596.3,171.1 L597.5,170.5 L598.7,170.0 L599.9,169.5 L601.1,169.0 L602.2,168.5 L603.2,168.0 L604.3,167.6 L605.3,167.1 L606.2,166.7 L607.1,166.3 L608.0,165.9 L608.8,165.5 L609.6,165.2 L610.4,164.9 L611.1,164.6 L611.7,164.3 L612.3,164.0" fill="none" stroke="var(--color-practice)" stroke-width="2.0" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="555.0" y1="191.4" x2="557.1" y2="190.3" stroke="var(--color-practice)" stroke-width="2.0" opacity="1.0" stroke-linecap="round"/>
  <polygon points="562.8,187.3 557.2,194.0 554.1,188.1" fill="var(--color-practice)" opacity="1.0"/>
  <line x1="612.3" y1="164.0" x2="612.3" y2="142.5" stroke="var(--color-base)" stroke-width="2.4" opacity="1.0" stroke-linecap="round"/>
  <polygon points="612.3,136.1 615.7,144.1 608.9,144.1" fill="var(--color-base)" opacity="1.0"/>
  <circle cx="475.9" cy="222.9" r="3.6" fill="var(--academic-text)"/>
  <circle cx="612.3" cy="164.0" r="3.6" fill="var(--academic-text)"/>
  <circle cx="612.3" cy="136.1" r="3.6" fill="var(--academic-text)"/>
  <text x="479.9" y="237.9" fill="var(--academic-text)" font-size="11.5" text-anchor="start">(<tspan font-style="italic">a</tspan>, <tspan font-style="italic">b</tspan>)</text>
  <text x="460.4" y="98.9" fill="var(--color-theory)" font-size="14" text-anchor="middle" font-weight="600"><tspan font-style="italic">D</tspan></text>
  <rect x="617.8" y="163.8" width="43.8" height="14.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="620.3" y="174.0" fill="var(--academic-text)" font-size="11.5" text-anchor="start">(<tspan font-style="italic">x</tspan>, <tspan font-style="italic">y</tspan><tspan font-size="8.5" dy="3.5">1</tspan><tspan dy="-3.5">&#8203;</tspan>)</text>
  <rect x="618.8" y="121.9" width="39.5" height="14.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="621.3" y="132.1" fill="var(--academic-text)" font-size="11.5" text-anchor="start">(<tspan font-style="italic">x</tspan>, <tspan font-style="italic">y</tspan>)</text>
  <text x="545.0" y="209.9" fill="var(--color-practice)" font-size="13" text-anchor="middle" font-weight="600"><tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">1</tspan><tspan dy="-3.5">&#8203;</tspan></text>
  <text x="604.3" y="153.7" fill="var(--color-base)" font-size="13" text-anchor="end" font-weight="600"><tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">2</tspan><tspan dy="-3.5">&#8203;</tspan></text>
  <text x="559.6" y="32.0" fill="var(--academic-text)" font-size="11.5" text-anchor="middle" font-weight="600">(b)  düşey son parça</text>
</svg>
<figcaption><em>f</em>(<em>x</em>, <em>y</em>) değerini veren yol, (<em>x</em>, <em>y</em>) merkezli ve <em>D</em>'de kalan diskin içinde bir doğru parçasıyla biter. (a) Yatay <em>C</em><sub>2</sub> parçasında <em>dy</em> = 0 olduğundan yalnız <em>P</em> katkı verir ve <em>f<sub>x</sub></em> = <em>P</em> bulunur. (b) Düşey parçada <em>dx</em> = 0'dır ve <em>f<sub>y</sub></em> = <em>Q</em> bulunur.</figcaption>
</figure>
```

**$x$'e göre türev.** $D$ açık olduğundan merkezi $(x, y)$ olan ve $D$'de kalan bir disk vardır. Bu diskte $x_1 < x$ olan bir $(x_1, y)$ noktası seçelim. $(a, b)$'den $(x_1, y)$'ye giden bir $C_1$ yolunu ve ardından $(x_1, y)$'den $(x, y)$'ye giden yatay $C_2$ doğru parçasını izleyelim (şeklin (a) paneli). Yoldan bağımsızlık gereği

$$f(x, y) = \int_{(a, b)}^{(x_1, y)} \mathbf{F} \cdot d\mathbf{r} + \int_{C_2} \mathbf{F} \cdot d\mathbf{r}$$

olur. $x$ değişirken $(x_1, y)$ noktası sabit kalır, bu yüzden ilk integral $x$'e bağlı değildir. $C_2$'yi $\mathbf{r}(t) = \langle t, y \rangle$, $x_1 \le t \le x$ diye yazalım. Bu doğru parçasında $\mathbf{r}'(t) = \mathbf{i}$ ve $\mathbf{F}(\mathbf{r}(t)) \cdot \mathbf{r}'(t) = P(t, y)$ olduğundan

$$\int_{C_2} \mathbf{F} \cdot d\mathbf{r} = \int_{x_1}^{x} P(t, y)\,dt$$

bulunur. $t \mapsto P(t, y)$ sürekli olduğundan, integralin üst sınırına göre türevi integrandın o noktadaki değeridir (bkz. [Analiz 2](../analiz-2/analizin-temel-teoremleri.html#thm-temel-teorem-ikinci)):

$$\frac{\partial f}{\partial x}(x, y) = 0 + \frac{\partial}{\partial x} \int_{x_1}^{x} P(t, y)\,dt = P(x, y).$$

**$y$'ye göre türev.** Aynı diskte $y_1 < y$ olan bir $(x, y_1)$ noktası seçip yolu bu kez $(x, y_1)$'den $(x, y)$'ye giden düşey bir doğru parçasıyla bitirelim (şeklin (b) paneli). Bu doğru parçası $\mathbf{r}(t) = \langle x, t \rangle$, $y_1 \le t \le y$ diye yazılır; $\mathbf{r}'(t) = \mathbf{j}$ olduğundan aynı akıl yürütme

$$\frac{\partial f}{\partial y}(x, y) = 0 + \frac{\partial}{\partial y} \int_{y_1}^{y} Q(x, t)\,dt = Q(x, y)$$

verir. Böylece $\nabla f = f_x\,\mathbf{i} + f_y\,\mathbf{j} = P\,\mathbf{i} + Q\,\mathbf{j} = \mathbf{F}$ bulunur, yani $\mathbf{F}$ konservatiftir. [$\blacksquare$]{.qed}
:::
::::

Şimdiye kadarki sonuçları tek bir ifadede toplayabiliriz.

:::: {#cor-tte-denk-kosullar name="Konservatiflik için Denk Koşullar"}
$\mathbf{F}$, açık ve bağlantılı bir $D$ bölgesinde sürekli bir vektör alanı olsun. Aşağıdaki üç koşul denktir:

(i\) $\mathbf{F}$, $D$'de konservatiftir.

(ii\) $\int_C \mathbf{F} \cdot d\mathbf{r}$ integrali $D$'de yoldan bağımsızdır.

(iii\) $D$ içindeki her kapalı $C$ yolu için $\int_C \mathbf{F} \cdot d\mathbf{r} = 0$'dır.

::: {.ispat}
(i) koşulundan (ii) koşulu @cor-tte-gradyan-yoldan-bagimsiz ile, (ii) koşulundan (i) koşulu @thm-tte-konservatif ile çıkar. (ii) ile (iii) koşullarının denkliğini @thm-tte-yoldan-bagimsizlik verir. [$\blacksquare$]{.qed}
:::
::::

## Konservatiflik Ölçütü

Denk koşulların hiçbiri pratikte kolay denetlenmez, çünkü bütün yolları ya da bütün kapalı yolları tek tek deneyemeyiz. Bu başlıkta $P$ ile $Q$'nun kısmi türevlerine bakan kullanışlı bir ölçüt kuracağız. Önce konservatif bir alanın sağlaması gereken bir koşulu bulalım.

:::: {#thm-tte-gerekli-kosul name="Konservatif Alan için Gerekli Koşul"}
$\mathbf{F}(x, y) = P(x, y)\,\mathbf{i} + Q(x, y)\,\mathbf{j}$, açık bir $D$ kümesinde konservatif olsun ve $P$ ile $Q$'nun birinci mertebeden kısmi türevleri $D$'de sürekli olsun. Bu durumda $D$'nin her noktasında

$$\frac{\partial P}{\partial y} = \frac{\partial Q}{\partial x}$$

olur.

::: {.ispat}
$\mathbf{F}$ konservatif olduğundan $D$'de $\nabla f = \mathbf{F}$ olan bir $f$ vardır, yani $P = f_x$ ve $Q = f_y$'dir. Buradan $P_y = (f_x)_y = f_{xy}$ ve $Q_x = (f_y)_x = f_{yx}$ olur ve varsayım gereği bu iki karışık türev $D$'de süreklidir. Clairaut teoremine göre (bkz. [Analiz 4](../analiz-4/yuksek-mertebeden-kismi-turevler.html#thm-yuk-clairaut)) sürekli karışık türevler eşittir:

$$\frac{\partial P}{\partial y} = f_{xy} = f_{yx} = \frac{\partial Q}{\partial x}.$$

[$\blacksquare$]{.qed}
:::
::::

Yani $\partial P / \partial y \ne \partial Q / \partial x$ olan tek bir nokta bile alanın konservatif olmadığını gösterir. Tersi ise ancak özel bölgelerde doğrudur. Bu bölgeleri tanımlamak için önce basit eğrilere ihtiyacımız var.

::: {#def-tte-basit-egri name="Basit Eğri"}
Kendisini kesmeyen eğriye **basit eğri** (simple curve) denir. $C$, $\mathbf{r}(t)$, $a \le t \le b$ ile verilmişse bu, $a \le t_1 < t_2 \le b$ için ($t_1 = a$, $t_2 = b$ durumu dışında) $\mathbf{r}(t_1) \ne \mathbf{r}(t_2)$ demektir. Hem basit hem kapalı olan eğriye **basit kapalı eğri** denir.
:::

Yani basit bir eğri üzerinde ilerleyen nokta aynı yerden iki kez geçmez; yalnız kapalı bir eğride, en sonda başladığı yere döner. Çember ve elips basit kapalı eğrilerdir; 8 rakamı biçimindeki bir eğri kapalıdır ama basit değildir.

```{=html}
<figure class="ders-grafik ders-grafik-genis">
<svg viewBox="24.5 15.5 674.0 158.5" role="img" aria-label="Four curves: a simple non-closed S shaped curve, a non-closed curve with a loop that crosses itself, a simple closed potato shaped curve and a closed figure eight">
  <path d="M42.5,148.5 L43.2,146.8 L43.9,144.6 L44.8,142.1 L45.7,139.3 L46.6,136.2 L47.7,132.8 L48.8,129.2 L49.9,125.4 L51.1,121.5 L52.4,117.5 L53.7,113.4 L55.0,109.3 L56.4,105.2 L57.8,101.1 L59.2,97.1 L60.7,93.3 L62.1,89.5 L63.6,86.0 L65.0,82.6 L66.5,79.6 L68.0,76.8 L69.4,74.3 L70.8,72.2 L72.2,70.5 L73.6,69.3 L75.0,68.5 L76.4,68.2 L77.7,68.5 L79.1,69.2 L80.6,70.3 L82.0,71.8 L83.5,73.6 L84.9,75.8 L86.4,78.2 L87.9,80.8 L89.4,83.6 L90.9,86.5 L92.4,89.6 L93.9,92.7 L95.4,95.9 L96.9,99.0 L98.4,102.1 L99.9,105.0 L101.4,107.9 L102.8,110.5 L104.3,113.0 L105.7,115.2 L107.1,117.1 L108.5,118.7 L109.8,119.9 L111.2,120.7 L112.5,121.0 L113.8,120.9 L115.1,120.3 L116.3,119.4 L117.6,118.1 L118.8,116.5 L120.0,114.6 L121.2,112.5 L122.4,110.2 L123.6,107.6 L124.8,105.0 L126.0,102.3 L127.1,99.5 L128.3,96.6 L129.4,93.8 L130.5,91.0 L131.7,88.3 L132.8,85.7 L133.9,83.3 L135.0,81.0 L136.1,79.0 L137.2,77.2 L138.2,75.8 L139.3,74.6 L140.4,73.8 L141.4,73.4 L142.5,73.5 L143.6,74.0 L144.7,74.9 L145.8,76.1 L146.9,77.7 L148.0,79.6 L149.1,81.7 L150.3,84.1 L151.4,86.7 L152.5,89.4 L153.6,92.4 L154.7,95.4 L155.8,98.6 L156.9,101.8 L157.9,105.0 L158.9,108.3 L159.9,111.5 L160.9,114.7 L161.8,117.8 L162.7,120.8 L163.5,123.6 L164.3,126.3 L165.1,128.7 L165.8,131.0 L166.4,132.9 L167.0,134.6 L167.5,136.0" fill="none" stroke="var(--color-practice)" stroke-width="2.0" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="42.5" cy="148.5" r="3.6" fill="var(--academic-text)"/>
  <circle cx="167.5" cy="136.0" r="3.6" fill="var(--academic-text)"/>
  <text x="105.0" y="38.0" fill="var(--academic-text)" font-size="11" text-anchor="middle" font-weight="600">basit, kapalı değil</text>
  <path d="M212.0,156.0 L213.0,155.0 L214.2,153.8 L215.6,152.4 L217.0,151.0 L218.6,149.4 L220.3,147.7 L222.1,145.9 L223.9,144.1 L225.9,142.1 L227.9,140.1 L230.0,138.0 L232.2,135.8 L234.3,133.7 L236.6,131.4 L238.8,129.2 L241.0,127.0 L243.3,124.7 L245.5,122.5 L247.8,120.2 L249.9,118.1 L252.1,115.9 L254.2,113.8 L256.3,111.7 L258.3,109.7 L260.2,107.8 L262.0,106.0 L263.8,104.2 L265.6,102.3 L267.4,100.3 L269.2,98.2 L271.0,96.2 L272.8,94.0 L274.6,91.9 L276.4,89.7 L278.1,87.6 L279.9,85.5 L281.7,83.4 L283.4,81.3 L285.1,79.3 L286.8,77.3 L288.5,75.5 L290.1,73.7 L291.7,72.0 L293.3,70.4 L294.9,69.0 L296.4,67.7 L297.9,66.5 L299.3,65.6 L300.7,64.7 L302.0,64.1 L303.3,63.7 L304.5,63.5 L305.7,63.5 L306.9,63.8 L308.1,64.3 L309.3,65.0 L310.5,65.9 L311.7,67.0 L312.9,68.2 L314.0,69.6 L315.1,71.1 L316.2,72.8 L317.3,74.5 L318.2,76.3 L319.2,78.2 L320.1,80.1 L320.9,82.1 L321.7,84.0 L322.3,86.0 L323.0,87.9 L323.5,89.9 L323.9,91.7 L324.3,93.5 L324.5,95.3 L324.7,96.9 L324.7,98.4 L324.7,99.8 L324.5,101.0 L324.2,102.2 L323.7,103.4 L323.1,104.6 L322.3,105.9 L321.4,107.2 L320.4,108.5 L319.3,109.8 L318.1,111.1 L316.8,112.3 L315.5,113.6 L314.1,114.8 L312.6,116.0 L311.1,117.1 L309.5,118.2 L307.9,119.2 L306.3,120.1 L304.8,120.9 L303.2,121.7 L301.6,122.3 L300.1,122.9 L298.6,123.3 L297.1,123.6 L295.7,123.8 L294.4,123.9 L293.2,123.8 L292.0,123.5 L290.9,123.1 L289.7,122.4 L288.5,121.6 L287.3,120.6 L286.0,119.5 L284.8,118.2 L283.5,116.8 L282.3,115.2 L281.0,113.6 L279.8,111.9 L278.6,110.1 L277.4,108.2 L276.2,106.3 L275.1,104.4 L274.0,102.4 L273.0,100.5 L272.0,98.5 L271.1,96.6 L270.3,94.7 L269.5,92.8 L268.9,91.0 L268.3,89.3 L267.8,87.7 L267.4,86.2 L267.2,84.8 L267.0,83.5 L266.9,82.3 L267.0,81.1 L267.1,80.0 L267.2,78.8 L267.5,77.7 L267.8,76.5 L268.2,75.5 L268.7,74.4 L269.2,73.3 L269.8,72.3 L270.5,71.3 L271.2,70.4 L272.0,69.4 L272.8,68.5 L273.8,67.7 L274.7,66.9 L275.7,66.1 L276.8,65.3 L277.9,64.6 L279.1,64.0 L280.3,63.3 L281.5,62.8 L282.8,62.3 L284.2,61.8 L285.6,61.4 L287.0,61.0 L288.5,60.7 L290.2,60.5 L292.1,60.4 L294.1,60.3 L296.2,60.3 L298.4,60.4 L300.7,60.5 L303.1,60.7 L305.6,60.9 L308.1,61.1 L310.6,61.4 L313.2,61.8 L315.8,62.1 L318.3,62.4 L320.8,62.8 L323.3,63.2 L325.7,63.6 L328.0,63.9 L330.2,64.3 L332.3,64.6 L334.4,64.9 L336.2,65.2 L337.9,65.5 L339.5,65.7 L340.8,65.9 L342.0,66.0" fill="none" stroke="var(--color-practice)" stroke-width="2.0" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <circle cx="212.0" cy="156.0" r="3.6" fill="var(--academic-text)"/>
  <circle cx="342.0" cy="66.0" r="3.6" fill="var(--academic-text)"/>
  <text x="277.0" y="38.0" fill="var(--academic-text)" font-size="11" text-anchor="middle" font-weight="600">basit değil, kapalı değil</text>
  <path d="M515.3,111.0 L514.7,109.1 L513.9,107.2 L513.0,105.4 L511.9,103.6 L510.7,101.9 L509.3,100.3 L507.8,98.7 L506.2,97.3 L504.5,95.9 L502.7,94.5 L500.9,93.3 L499.0,92.2 L497.1,91.1 L495.2,90.1 L493.2,89.1 L491.3,88.3 L489.4,87.5 L487.5,86.7 L485.6,86.0 L483.8,85.3 L482.0,84.6 L480.2,84.0 L478.5,83.3 L476.8,82.7 L475.1,82.1 L473.5,81.4 L471.9,80.8 L470.3,80.1 L468.7,79.4 L467.1,78.7 L465.5,78.0 L463.8,77.3 L462.2,76.5 L460.4,75.8 L458.7,75.0 L456.9,74.3 L455.0,73.5 L453.1,72.8 L451.1,72.1 L449.0,71.5 L446.9,70.9 L444.7,70.3 L442.4,69.8 L440.1,69.4 L437.7,69.1 L435.3,68.9 L432.9,68.7 L430.4,68.7 L427.9,68.8 L425.4,69.0 L423.0,69.3 L420.5,69.7 L418.1,70.3 L415.8,70.9 L413.5,71.7 L411.2,72.6 L409.1,73.6 L407.1,74.7 L405.1,75.9 L403.3,77.2 L401.5,78.6 L399.9,80.0 L398.5,81.5 L397.1,83.1 L395.9,84.8 L394.8,86.4 L393.8,88.1 L392.9,89.9 L392.2,91.6 L391.6,93.4 L391.1,95.2 L390.7,97.0 L390.4,98.8 L390.2,100.6 L390.0,102.3 L390.0,104.1 L390.1,105.8 L390.2,107.6 L390.4,109.3 L390.6,111.0 L391.0,112.7 L391.4,114.4 L391.8,116.0 L392.3,117.6 L392.9,119.2 L393.5,120.8 L394.2,122.4 L395.0,124.0 L395.8,125.5 L396.7,127.0 L397.6,128.5 L398.7,130.0 L399.8,131.4 L400.9,132.8 L402.2,134.1 L403.5,135.4 L404.9,136.7 L406.3,137.9 L407.9,139.1 L409.5,140.2 L411.1,141.3 L412.9,142.3 L414.7,143.2 L416.5,144.1 L418.4,144.9 L420.3,145.6 L422.3,146.3 L424.3,146.9 L426.3,147.4 L428.4,147.8 L430.4,148.2 L432.5,148.6 L434.6,148.8 L436.6,149.0 L438.7,149.2 L440.8,149.3 L442.9,149.4 L444.9,149.4 L447.0,149.4 L449.0,149.4 L451.0,149.3 L453.1,149.2 L455.1,149.1 L457.1,148.9 L459.2,148.8 L461.2,148.6 L463.3,148.4 L465.3,148.2 L467.4,147.9 L469.5,147.6 L471.7,147.3 L473.8,147.0 L476.0,146.6 L478.2,146.2 L480.4,145.7 L482.6,145.2 L484.9,144.6 L487.1,144.0 L489.4,143.3 L491.6,142.5 L493.8,141.6 L496.0,140.6 L498.1,139.6 L500.2,138.5 L502.2,137.3 L504.1,135.9 L505.9,134.5 L507.6,133.1 L509.1,131.5 L510.6,129.9 L511.9,128.1 L513.0,126.4 L513.9,124.5 L514.7,122.7 L515.3,120.7 L515.6,118.8 L515.8,116.8 L515.8,114.9 L515.6,112.9 L515.3,111.0" fill="none" stroke="var(--color-practice)" stroke-width="2.0" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <text x="449.0" y="38.0" fill="var(--academic-text)" font-size="11" text-anchor="middle" font-weight="600">basit, kapalı</text>
  <path d="M621.0,111.0 L623.0,108.9 L624.9,106.7 L626.9,104.6 L628.8,102.5 L630.8,100.5 L632.7,98.5 L634.6,96.5 L636.5,94.6 L638.4,92.8 L640.3,91.0 L642.2,89.3 L644.0,87.7 L645.8,86.2 L647.6,84.8 L649.4,83.5 L651.1,82.3 L652.8,81.2 L654.5,80.2 L656.1,79.4 L657.7,78.7 L659.3,78.1 L660.8,77.6 L662.3,77.3 L663.8,77.1 L665.2,77.0 L666.6,77.1 L667.9,77.3 L669.2,77.6 L670.4,78.1 L671.6,78.7 L672.7,79.4 L673.8,80.2 L674.8,81.2 L675.8,82.3 L676.7,83.5 L677.6,84.8 L678.4,86.2 L679.1,87.7 L679.8,89.3 L680.4,91.0 L681.0,92.8 L681.5,94.6 L682.0,96.5 L682.4,98.5 L682.7,100.5 L683.0,102.5 L683.2,104.6 L683.4,106.7 L683.5,108.9 L683.5,111.0 L683.5,113.1 L683.4,115.3 L683.2,117.4 L683.0,119.5 L682.7,121.5 L682.4,123.5 L682.0,125.5 L681.5,127.4 L681.0,129.2 L680.4,131.0 L679.8,132.7 L679.1,134.3 L678.4,135.8 L677.6,137.2 L676.7,138.5 L675.8,139.7 L674.8,140.8 L673.8,141.8 L672.7,142.6 L671.6,143.3 L670.4,143.9 L669.2,144.4 L667.9,144.7 L666.6,144.9 L665.2,145.0 L663.8,144.9 L662.3,144.7 L660.8,144.4 L659.3,143.9 L657.7,143.3 L656.1,142.6 L654.5,141.8 L652.8,140.8 L651.1,139.7 L649.4,138.5 L647.6,137.2 L645.8,135.8 L644.0,134.3 L642.2,132.7 L640.3,131.0 L638.4,129.2 L636.5,127.4 L634.6,125.5 L632.7,123.5 L630.8,121.5 L628.8,119.5 L626.9,117.4 L624.9,115.3 L623.0,113.1 L621.0,111.0 L619.0,108.9 L617.1,106.7 L615.1,104.6 L613.2,102.5 L611.2,100.5 L609.3,98.5 L607.4,96.5 L605.5,94.6 L603.6,92.8 L601.7,91.0 L599.8,89.3 L598.0,87.7 L596.2,86.2 L594.4,84.8 L592.6,83.5 L590.9,82.3 L589.2,81.2 L587.5,80.2 L585.9,79.4 L584.3,78.7 L582.7,78.1 L581.2,77.6 L579.7,77.3 L578.2,77.1 L576.8,77.0 L575.4,77.1 L574.1,77.3 L572.8,77.6 L571.6,78.1 L570.4,78.7 L569.3,79.4 L568.2,80.2 L567.2,81.2 L566.2,82.3 L565.3,83.5 L564.4,84.8 L563.6,86.2 L562.9,87.7 L562.2,89.3 L561.6,91.0 L561.0,92.8 L560.5,94.6 L560.0,96.5 L559.6,98.5 L559.3,100.5 L559.0,102.5 L558.8,104.6 L558.6,106.7 L558.5,108.9 L558.5,111.0 L558.5,113.1 L558.6,115.3 L558.8,117.4 L559.0,119.5 L559.3,121.5 L559.6,123.5 L560.0,125.5 L560.5,127.4 L561.0,129.2 L561.6,131.0 L562.2,132.7 L562.9,134.3 L563.6,135.8 L564.4,137.2 L565.3,138.5 L566.2,139.7 L567.2,140.8 L568.2,141.8 L569.3,142.6 L570.4,143.3 L571.6,143.9 L572.8,144.4 L574.1,144.7 L575.4,144.9 L576.8,145.0 L578.2,144.9 L579.7,144.7 L581.2,144.4 L582.7,143.9 L584.3,143.3 L585.9,142.6 L587.5,141.8 L589.2,140.8 L590.9,139.7 L592.6,138.5 L594.4,137.2 L596.2,135.8 L598.0,134.3 L599.8,132.7 L601.7,131.0 L603.6,129.2 L605.5,127.4 L607.4,125.5 L609.3,123.5 L611.2,121.5 L613.2,119.5 L615.1,117.4 L617.1,115.3 L619.0,113.1 L621.0,111.0" fill="none" stroke="var(--color-practice)" stroke-width="2.0" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <text x="621.0" y="38.0" fill="var(--academic-text)" font-size="11" text-anchor="middle" font-weight="600">basit değil, kapalı</text>
</svg>
<figcaption>Eğri türleri. Kapalı olmayan eğrilerde uç noktalar işaretlidir. İkinci eğri kendisini bir kez keser; dördüncü eğri (8 biçimi) başladığı yere döner ama ortadaki noktadan iki kez geçer.</figcaption>
</figure>
```

::: {#def-tte-basit-baglantili name="Basit Bağlantılı Bölge"}
Düzlemde bağlantılı bir $D$ kümesi verilsin. $D$ içindeki her basit kapalı eğrinin çevrelediği bütün noktalar da $D$'ye aitse $D$'ye **basit bağlantılı** (simply-connected) denir.
:::

Yani basit bağlantılı bir bölgede delik yoktur: bir delik olsaydı, deliğin çevresinde dolaşan basit kapalı bir eğri $D$'de olmayan noktaları çevrelerdi. Bölge bağlantılı olduğundan iki ayrı parçadan da oluşamaz. Disk, dikdörtgen, üst yarı düzlem ve bütün düzlem basit bağlantılıdır; halka ve bir noktası çıkarılmış düzlem basit bağlantılı değildir.

```{=html}
<figure class="ders-grafik ders-grafik-genis">
<svg viewBox="21.5 15.5 676.0 180.0" role="img" aria-label="Three shaded sets: a region without holes containing a dashed simple closed curve, the same region with a hole and a dashed curve around the hole, and a set made of two separate pieces">
  <path d="M226.0,124.3 L225.2,122.1 L224.2,120.0 L223.2,117.9 L222.1,115.9 L220.9,113.9 L219.6,112.0 L218.2,110.1 L216.7,108.3 L215.2,106.5 L213.7,104.7 L212.1,103.0 L210.5,101.4 L208.8,99.8 L207.1,98.2 L205.4,96.7 L203.7,95.2 L201.9,93.8 L200.2,92.3 L198.4,91.0 L196.6,89.6 L194.8,88.3 L193.0,87.0 L191.2,85.7 L189.4,84.4 L187.5,83.2 L185.7,82.0 L183.8,80.8 L181.9,79.6 L180.0,78.4 L178.1,77.3 L176.1,76.2 L174.1,75.1 L172.0,74.0 L170.0,73.0 L167.9,72.0 L165.7,71.0 L163.5,70.0 L161.3,69.1 L159.0,68.2 L156.7,67.4 L154.3,66.6 L151.9,65.9 L149.5,65.2 L147.0,64.6 L144.5,64.1 L142.0,63.6 L139.4,63.1 L136.8,62.8 L134.1,62.5 L131.5,62.3 L128.8,62.1 L126.2,62.1 L123.5,62.1 L120.8,62.1 L118.1,62.3 L115.4,62.5 L112.8,62.8 L110.1,63.2 L107.5,63.6 L104.9,64.2 L102.3,64.8 L99.7,65.4 L97.2,66.1 L94.7,66.9 L92.2,67.7 L89.8,68.6 L87.4,69.6 L85.0,70.6 L82.7,71.7 L80.5,72.8 L78.2,73.9 L76.0,75.1 L73.9,76.4 L71.8,77.7 L69.7,79.0 L67.7,80.4 L65.7,81.8 L63.8,83.2 L61.9,84.7 L60.1,86.2 L58.3,87.8 L56.5,89.4 L54.8,91.0 L53.1,92.7 L51.5,94.4 L50.0,96.2 L48.5,98.0 L47.1,99.8 L45.8,101.7 L44.5,103.6 L43.3,105.5 L42.2,107.5 L41.1,109.5 L40.2,111.5 L39.3,113.6 L38.6,115.7 L37.9,117.8 L37.4,120.0 L37.0,122.1 L36.7,124.3 L36.5,126.5 L36.5,128.7 L36.6,130.9 L36.8,133.1 L37.2,135.3 L37.7,137.4 L38.3,139.6 L39.1,141.7 L40.1,143.8 L41.1,145.8 L42.3,147.8 L43.6,149.8 L45.1,151.7 L46.7,153.6 L48.4,155.4 L50.2,157.1 L52.1,158.7 L54.1,160.3 L56.2,161.8 L58.4,163.2 L60.7,164.6 L63.1,165.8 L65.5,167.0 L67.9,168.1 L70.4,169.1 L72.9,170.0 L75.5,170.9 L78.1,171.7 L80.6,172.4 L83.2,173.0 L85.8,173.6 L88.4,174.1 L90.9,174.6 L93.5,175.0 L96.0,175.4 L98.5,175.7 L101.0,176.0 L103.4,176.3 L105.9,176.5 L108.3,176.7 L110.6,176.9 L113.0,177.1 L115.3,177.3 L117.7,177.5 L120.0,177.7 L122.3,177.9 L124.6,178.1 L126.9,178.3 L129.2,178.5 L131.5,178.7 L133.8,178.9 L136.2,179.1 L138.6,179.3 L141.0,179.5 L143.5,179.7 L145.9,179.8 L148.5,180.0 L151.1,180.1 L153.7,180.3 L156.3,180.3 L159.0,180.4 L161.8,180.4 L164.5,180.3 L167.3,180.2 L170.2,180.0 L173.1,179.7 L175.9,179.4 L178.8,179.0 L181.7,178.5 L184.6,177.9 L187.5,177.2 L190.3,176.5 L193.2,175.6 L195.9,174.6 L198.7,173.5 L201.3,172.4 L203.9,171.1 L206.4,169.7 L208.8,168.3 L211.1,166.7 L213.2,165.0 L215.3,163.3 L217.2,161.5 L219.0,159.6 L220.6,157.6 L222.1,155.6 L223.4,153.5 L224.5,151.3 L225.5,149.1 L226.4,146.9 L227.0,144.7 L227.5,142.4 L227.9,140.1 L228.1,137.8 L228.1,135.5 L227.9,133.2 L227.7,131.0 L227.2,128.7 L226.7,126.5 Z" fill="var(--color-theory)" fill-opacity="0.16" fill-rule="evenodd" stroke="var(--color-theory)" stroke-width="1.6" stroke-linejoin="round"/>
  <path d="M184.5,124.3 L184.0,122.7 L183.4,121.2 L182.7,119.6 L181.9,118.2 L181.0,116.7 L180.1,115.3 L179.1,113.9 L178.0,112.6 L176.9,111.2 L175.7,109.9 L174.5,108.7 L173.2,107.4 L171.9,106.2 L170.5,105.0 L169.0,103.8 L167.4,102.6 L165.8,101.5 L164.1,100.4 L162.4,99.3 L160.5,98.3 L158.6,97.3 L156.6,96.3 L154.4,95.4 L152.2,94.6 L149.9,93.8 L147.6,93.1 L145.1,92.4 L142.6,91.9 L140.0,91.4 L137.3,91.1 L134.6,90.8 L131.8,90.7 L129.1,90.7 L126.3,90.8 L123.5,91.0 L120.7,91.3 L118.0,91.8 L115.3,92.4 L112.7,93.1 L110.2,93.9 L107.8,94.9 L105.4,95.9 L103.2,97.1 L101.2,98.3 L99.3,99.7 L97.5,101.1 L95.9,102.6 L94.5,104.2 L93.2,105.8 L92.1,107.4 L91.2,109.1 L90.5,110.8 L89.9,112.5 L89.5,114.2 L89.2,116.0 L89.1,117.7 L89.2,119.4 L89.3,121.0 L89.6,122.7 L90.1,124.3 L90.6,125.9 L91.2,127.4 L91.9,129.0 L92.7,130.4 L93.6,131.9 L94.5,133.3 L95.5,134.7 L96.6,136.0 L97.7,137.4 L98.9,138.7 L100.1,139.9 L101.4,141.2 L102.7,142.4 L104.1,143.6 L105.6,144.8 L107.2,146.0 L108.8,147.1 L110.5,148.2 L112.2,149.3 L114.1,150.3 L116.0,151.3 L118.0,152.3 L120.2,153.2 L122.4,154.0 L124.7,154.8 L127.0,155.5 L129.5,156.2 L132.0,156.7 L134.6,157.2 L137.3,157.5 L140.0,157.8 L142.8,157.9 L145.5,157.9 L148.3,157.8 L151.1,157.6 L153.9,157.3 L156.6,156.8 L159.3,156.2 L161.9,155.5 L164.4,154.7 L166.8,153.7 L169.2,152.7 L171.4,151.5 L173.4,150.3 L175.3,148.9 L177.1,147.5 L178.7,146.0 L180.1,144.4 L181.4,142.8 L182.5,141.2 L183.4,139.5 L184.1,137.8 L184.7,136.1 L185.1,134.4 L185.4,132.6 L185.5,130.9 L185.4,129.2 L185.3,127.6 L185.0,125.9 L184.5,124.3" fill="none" stroke="var(--color-practice)" stroke-width="1.6" stroke-dasharray="5 3" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <text x="131.5" y="38.0" fill="var(--academic-text)" font-size="11" text-anchor="middle" font-weight="600">basit bağlantılı</text>
  <path d="M455.0,124.3 L454.2,122.1 L453.2,120.0 L452.2,117.9 L451.1,115.9 L449.9,113.9 L448.6,112.0 L447.2,110.1 L445.7,108.3 L444.2,106.5 L442.7,104.7 L441.1,103.0 L439.5,101.4 L437.8,99.8 L436.1,98.2 L434.4,96.7 L432.7,95.2 L430.9,93.8 L429.2,92.3 L427.4,91.0 L425.6,89.6 L423.8,88.3 L422.0,87.0 L420.2,85.7 L418.4,84.4 L416.5,83.2 L414.7,82.0 L412.8,80.8 L410.9,79.6 L409.0,78.4 L407.1,77.3 L405.1,76.2 L403.1,75.1 L401.0,74.0 L399.0,73.0 L396.9,72.0 L394.7,71.0 L392.5,70.0 L390.3,69.1 L388.0,68.2 L385.7,67.4 L383.3,66.6 L380.9,65.9 L378.5,65.2 L376.0,64.6 L373.5,64.1 L371.0,63.6 L368.4,63.1 L365.8,62.8 L363.1,62.5 L360.5,62.3 L357.8,62.1 L355.2,62.1 L352.5,62.1 L349.8,62.1 L347.1,62.3 L344.4,62.5 L341.8,62.8 L339.1,63.2 L336.5,63.6 L333.9,64.2 L331.3,64.8 L328.7,65.4 L326.2,66.1 L323.7,66.9 L321.2,67.7 L318.8,68.6 L316.4,69.6 L314.0,70.6 L311.7,71.7 L309.5,72.8 L307.2,73.9 L305.0,75.1 L302.9,76.4 L300.8,77.7 L298.7,79.0 L296.7,80.4 L294.7,81.8 L292.8,83.2 L290.9,84.7 L289.1,86.2 L287.3,87.8 L285.5,89.4 L283.8,91.0 L282.1,92.7 L280.5,94.4 L279.0,96.2 L277.5,98.0 L276.1,99.8 L274.8,101.7 L273.5,103.6 L272.3,105.5 L271.2,107.5 L270.1,109.5 L269.2,111.5 L268.3,113.6 L267.6,115.7 L266.9,117.8 L266.4,120.0 L266.0,122.1 L265.7,124.3 L265.5,126.5 L265.5,128.7 L265.6,130.9 L265.8,133.1 L266.2,135.3 L266.7,137.4 L267.3,139.6 L268.1,141.7 L269.1,143.8 L270.1,145.8 L271.3,147.8 L272.6,149.8 L274.1,151.7 L275.7,153.6 L277.4,155.4 L279.2,157.1 L281.1,158.7 L283.1,160.3 L285.2,161.8 L287.4,163.2 L289.7,164.6 L292.1,165.8 L294.5,167.0 L296.9,168.1 L299.4,169.1 L301.9,170.0 L304.5,170.9 L307.1,171.7 L309.6,172.4 L312.2,173.0 L314.8,173.6 L317.4,174.1 L319.9,174.6 L322.5,175.0 L325.0,175.4 L327.5,175.7 L330.0,176.0 L332.4,176.3 L334.9,176.5 L337.3,176.7 L339.6,176.9 L342.0,177.1 L344.3,177.3 L346.7,177.5 L349.0,177.7 L351.3,177.9 L353.6,178.1 L355.9,178.3 L358.2,178.5 L360.5,178.7 L362.8,178.9 L365.2,179.1 L367.6,179.3 L370.0,179.5 L372.5,179.7 L374.9,179.8 L377.5,180.0 L380.1,180.1 L382.7,180.3 L385.3,180.3 L388.0,180.4 L390.8,180.4 L393.5,180.3 L396.3,180.2 L399.2,180.0 L402.1,179.7 L404.9,179.4 L407.8,179.0 L410.7,178.5 L413.6,177.9 L416.5,177.2 L419.3,176.5 L422.2,175.6 L424.9,174.6 L427.7,173.5 L430.3,172.4 L432.9,171.1 L435.4,169.7 L437.8,168.3 L440.1,166.7 L442.2,165.0 L444.3,163.3 L446.2,161.5 L448.0,159.6 L449.6,157.6 L451.1,155.6 L452.4,153.5 L453.5,151.3 L454.5,149.1 L455.4,146.9 L456.0,144.7 L456.5,142.4 L456.9,140.1 L457.1,137.8 L457.1,135.5 L456.9,133.2 L456.7,131.0 L456.2,128.7 L455.7,126.5 Z M395.4,122.7 L395.3,123.9 L395.0,125.2 L394.7,126.4 L394.2,127.6 L393.5,128.7 L392.8,129.9 L392.0,130.9 L391.0,131.9 L389.9,132.9 L388.8,133.8 L387.6,134.6 L386.3,135.3 L385.0,135.9 L383.6,136.5 L382.2,137.0 L380.8,137.4 L379.3,137.8 L377.9,138.1 L376.4,138.3 L375.0,138.5 L373.5,138.6 L372.1,138.6 L370.6,138.6 L369.2,138.6 L367.8,138.5 L366.4,138.4 L365.0,138.2 L363.6,137.9 L362.3,137.7 L360.9,137.4 L359.6,137.0 L358.2,136.6 L356.9,136.1 L355.6,135.6 L354.4,135.1 L353.1,134.4 L351.9,133.8 L350.7,133.0 L349.6,132.2 L348.6,131.4 L347.6,130.5 L346.7,129.5 L345.8,128.5 L345.1,127.4 L344.4,126.2 L343.9,125.1 L343.5,123.9 L343.2,122.6 L343.0,121.4 L343.0,120.1 L343.1,118.9 L343.4,117.6 L343.7,116.4 L344.2,115.2 L344.9,114.1 L345.6,112.9 L346.4,111.9 L347.4,110.9 L348.5,109.9 L349.6,109.0 L350.8,108.2 L352.1,107.5 L353.4,106.9 L354.8,106.3 L356.2,105.8 L357.6,105.4 L359.1,105.0 L360.5,104.7 L362.0,104.5 L363.4,104.3 L364.9,104.2 L366.3,104.2 L367.8,104.2 L369.2,104.2 L370.6,104.3 L372.0,104.4 L373.4,104.6 L374.8,104.9 L376.1,105.1 L377.5,105.4 L378.8,105.8 L380.2,106.2 L381.5,106.7 L382.8,107.2 L384.0,107.7 L385.3,108.4 L386.5,109.0 L387.7,109.8 L388.8,110.6 L389.8,111.4 L390.8,112.3 L391.7,113.3 L392.6,114.3 L393.3,115.4 L394.0,116.6 L394.5,117.7 L394.9,118.9 L395.2,120.2 L395.4,121.4 Z" fill="var(--color-theory)" fill-opacity="0.16" fill-rule="evenodd" stroke="var(--color-theory)" stroke-width="1.6" stroke-linejoin="round"/>
  <path d="M426.1,121.4 L425.7,119.2 L425.2,116.9 L424.5,114.8 L423.6,112.6 L422.6,110.6 L421.4,108.5 L420.1,106.6 L418.7,104.7 L417.2,102.9 L415.6,101.1 L413.9,99.4 L412.1,97.8 L410.2,96.2 L408.2,94.8 L406.2,93.4 L404.1,92.0 L401.9,90.8 L399.7,89.6 L397.4,88.5 L395.1,87.4 L392.7,86.4 L390.3,85.5 L387.8,84.7 L385.3,83.9 L382.7,83.2 L380.1,82.6 L377.4,82.1 L374.7,81.6 L372.0,81.3 L369.2,81.0 L366.4,80.8 L363.6,80.7 L360.7,80.8 L357.8,80.9 L355.0,81.2 L352.1,81.5 L349.3,82.0 L346.4,82.6 L343.6,83.4 L340.9,84.2 L338.2,85.2 L335.6,86.3 L333.0,87.6 L330.6,88.9 L328.3,90.4 L326.1,92.0 L324.0,93.6 L322.0,95.4 L320.2,97.3 L318.6,99.3 L317.2,101.3 L315.9,103.4 L314.8,105.6 L313.9,107.8 L313.1,110.0 L312.6,112.3 L312.3,114.6 L312.1,116.9 L312.1,119.1 L312.3,121.4 L312.7,123.6 L313.2,125.9 L313.9,128.0 L314.8,130.2 L315.8,132.2 L317.0,134.3 L318.3,136.2 L319.7,138.1 L321.2,139.9 L322.8,141.7 L324.5,143.4 L326.3,145.0 L328.2,146.6 L330.2,148.0 L332.2,149.4 L334.3,150.8 L336.5,152.0 L338.7,153.2 L341.0,154.3 L343.3,155.4 L345.7,156.4 L348.1,157.3 L350.6,158.1 L353.1,158.9 L355.7,159.6 L358.3,160.2 L361.0,160.7 L363.7,161.2 L366.4,161.5 L369.2,161.8 L372.0,162.0 L374.8,162.1 L377.7,162.0 L380.6,161.9 L383.4,161.6 L386.3,161.3 L389.1,160.8 L392.0,160.2 L394.8,159.4 L397.5,158.6 L400.2,157.6 L402.8,156.5 L405.4,155.2 L407.8,153.9 L410.1,152.4 L412.3,150.8 L414.4,149.2 L416.4,147.4 L418.2,145.5 L419.8,143.5 L421.2,141.5 L422.5,139.4 L423.6,137.2 L424.5,135.0 L425.3,132.8 L425.8,130.5 L426.1,128.2 L426.3,125.9 L426.3,123.7 L426.1,121.4" fill="none" stroke="var(--color-practice)" stroke-width="1.6" stroke-dasharray="5 3" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <text x="360.5" y="38.0" fill="var(--academic-text)" font-size="11" text-anchor="middle" font-weight="600">delikli</text>
  <path d="M585.2,115.6 L585.0,113.2 L584.7,110.9 L584.4,108.5 L583.9,106.2 L583.3,104.0 L582.6,101.8 L581.8,99.6 L580.9,97.5 L580.0,95.5 L578.9,93.6 L577.8,91.7 L576.6,89.9 L575.3,88.2 L574.0,86.6 L572.7,85.0 L571.2,83.6 L569.8,82.2 L568.3,80.9 L566.7,79.7 L565.2,78.6 L563.6,77.6 L562.0,76.6 L560.4,75.7 L558.8,74.9 L557.1,74.1 L555.5,73.4 L553.8,72.8 L552.1,72.3 L550.4,71.8 L548.8,71.3 L547.1,71.0 L545.4,70.7 L543.6,70.4 L541.9,70.2 L540.2,70.1 L538.5,70.0 L536.7,70.0 L535.0,70.0 L533.2,70.2 L531.5,70.4 L529.7,70.6 L527.9,71.0 L526.1,71.4 L524.4,71.9 L522.6,72.5 L520.9,73.2 L519.1,73.9 L517.4,74.8 L515.7,75.8 L514.0,76.8 L512.4,78.0 L510.8,79.2 L509.2,80.6 L507.7,82.1 L506.2,83.6 L504.9,85.3 L503.5,87.0 L502.3,88.9 L501.2,90.8 L500.1,92.8 L499.1,94.9 L498.2,97.0 L497.5,99.2 L496.8,101.5 L496.3,103.8 L495.8,106.1 L495.5,108.5 L495.3,110.8 L495.2,113.2 L495.2,115.6 L495.4,118.0 L495.7,120.3 L496.0,122.7 L496.5,125.0 L497.1,127.2 L497.8,129.4 L498.6,131.6 L499.5,133.7 L500.4,135.7 L501.5,137.6 L502.6,139.5 L503.8,141.3 L505.1,143.0 L506.4,144.6 L507.7,146.2 L509.2,147.6 L510.6,149.0 L512.1,150.3 L513.7,151.5 L515.2,152.6 L516.8,153.6 L518.4,154.6 L520.0,155.5 L521.6,156.3 L523.3,157.1 L524.9,157.8 L526.6,158.4 L528.3,158.9 L530.0,159.4 L531.6,159.9 L533.3,160.2 L535.0,160.5 L536.8,160.8 L538.5,161.0 L540.2,161.1 L541.9,161.2 L543.7,161.2 L545.4,161.2 L547.2,161.0 L548.9,160.8 L550.7,160.6 L552.5,160.2 L554.3,159.8 L556.0,159.3 L557.8,158.7 L559.5,158.0 L561.3,157.3 L563.0,156.4 L564.7,155.4 L566.4,154.4 L568.0,153.2 L569.6,152.0 L571.2,150.6 L572.7,149.1 L574.2,147.6 L575.5,145.9 L576.9,144.2 L578.1,142.3 L579.2,140.4 L580.3,138.4 L581.3,136.3 L582.2,134.2 L582.9,132.0 L583.6,129.7 L584.1,127.4 L584.6,125.1 L584.9,122.7 L585.1,120.4 L585.2,118.0 Z" fill="var(--color-theory)" fill-opacity="0.16" fill-rule="evenodd" stroke="var(--color-theory)" stroke-width="1.6" stroke-linejoin="round"/>
  <path d="M682.1,133.0 L681.7,131.1 L681.3,129.2 L680.7,127.3 L680.1,125.5 L679.4,123.8 L678.6,122.1 L677.8,120.5 L677.0,118.9 L676.1,117.4 L675.2,115.9 L674.3,114.5 L673.3,113.1 L672.4,111.7 L671.4,110.4 L670.5,109.0 L669.5,107.7 L668.5,106.4 L667.5,105.1 L666.5,103.9 L665.5,102.6 L664.4,101.3 L663.3,100.0 L662.2,98.8 L661.0,97.6 L659.8,96.4 L658.5,95.2 L657.2,94.1 L655.8,93.1 L654.3,92.1 L652.8,91.2 L651.2,90.4 L649.6,89.8 L648.0,89.2 L646.3,88.7 L644.6,88.4 L642.9,88.3 L641.1,88.2 L639.4,88.4 L637.7,88.6 L636.0,89.0 L634.3,89.6 L632.7,90.3 L631.1,91.2 L629.6,92.1 L628.1,93.2 L626.7,94.4 L625.4,95.7 L624.2,97.1 L623.0,98.5 L622.0,100.0 L621.0,101.6 L620.0,103.2 L619.2,104.8 L618.4,106.4 L617.7,108.1 L617.0,109.7 L616.3,111.3 L615.7,113.0 L615.2,114.6 L614.6,116.2 L614.1,117.9 L613.6,119.5 L613.1,121.1 L612.7,122.8 L612.2,124.4 L611.8,126.1 L611.3,127.8 L610.9,129.5 L610.5,131.2 L610.2,133.0 L609.9,134.8 L609.6,136.7 L609.4,138.5 L609.3,140.4 L609.3,142.4 L609.3,144.3 L609.4,146.3 L609.6,148.2 L610.0,150.2 L610.4,152.1 L610.9,154.0 L611.6,155.9 L612.4,157.7 L613.3,159.4 L614.3,161.1 L615.4,162.7 L616.6,164.1 L617.8,165.5 L619.2,166.7 L620.7,167.9 L622.2,168.9 L623.7,169.8 L625.3,170.5 L626.9,171.1 L628.6,171.6 L630.2,172.0 L631.9,172.3 L633.5,172.5 L635.2,172.6 L636.8,172.7 L638.4,172.6 L640.0,172.5 L641.5,172.4 L643.1,172.2 L644.6,171.9 L646.1,171.7 L647.6,171.4 L649.0,171.1 L650.5,170.8 L652.0,170.5 L653.4,170.1 L654.9,169.8 L656.4,169.4 L657.8,168.9 L659.3,168.5 L660.8,168.0 L662.3,167.4 L663.8,166.8 L665.3,166.1 L666.8,165.3 L668.3,164.5 L669.7,163.5 L671.2,162.5 L672.6,161.4 L673.9,160.1 L675.2,158.8 L676.4,157.4 L677.5,155.8 L678.5,154.2 L679.4,152.5 L680.3,150.7 L681.0,148.8 L681.5,146.9 L682.0,145.0 L682.3,143.0 L682.5,141.0 L682.6,139.0 L682.5,137.0 L682.4,135.0 Z" fill="var(--color-theory)" fill-opacity="0.16" fill-rule="evenodd" stroke="var(--color-theory)" stroke-width="1.6" stroke-linejoin="round"/>
  <text x="589.5" y="38.0" fill="var(--academic-text)" font-size="11" text-anchor="middle" font-weight="600">iki parçalı</text>
</svg>
<figcaption>Soldaki bölge basit bağlantılıdır: içindeki her basit kapalı eğri (kesikli) yalnız bölgenin noktalarını çevreler. Ortadaki bölgede deliği dolanan kesikli eğri, bölgede olmayan noktaları çevreler; sağdaki küme ise bağlantılı bile değildir. Bu iki küme basit bağlantılı değildir.</figcaption>
</figure>
```

Artık gerekli koşulun (@thm-tte-gerekli-kosul) kısmi tersini ifade edebiliriz. Bu ölçüt, düzlemde bir alanın konservatif olup olmadığını anlamanın en pratik yoludur.

:::: {#thm-tte-konservatif-test name="Konservatiflik Ölçütü"}
$\mathbf{F} = P\,\mathbf{i} + Q\,\mathbf{j}$, açık ve basit bağlantılı bir $D$ bölgesinde tanımlı bir vektör alanı olsun. $P$ ile $Q$'nun birinci mertebeden kısmi türevleri $D$'de sürekli ve $D$'nin her noktasında

$$\frac{\partial P}{\partial y} = \frac{\partial Q}{\partial x}$$

ise $\mathbf{F}$, $D$'de konservatiftir.

::: {.ispat baslik="Disk ve dikdörtgen için ispat"}
$D$, merkezi $(a, b)$ olan açık bir disk ya da $(a, b)$ noktasını içeren ve kenarları eksenlere paralel olan açık bir dikdörtgen olsun.

**L biçimli yol.** Bir $(x, y) \in D$ için $(a, b)$'den yatay olarak $(x, b)$'ye, oradan düşey olarak $(x, y)$'ye giden yol $D$'de kalır. Dikdörtgende bu açıktır, çünkü yolun her noktasının birinci koordinatı $a$ ile $x$ arasında, ikinci koordinatı $b$ ile $y$ arasındadır. Diskte de öyledir: yolun bir $(u, s)$ noktası için $|u - a| \le |x - a|$ ve $|s - b| \le |y - b|$ olduğundan bu noktanın merkeze uzaklığı $(x, y)$'nin merkeze uzaklığını aşmaz. Bu yol boyunca $\mathbf{F}$'nin integralini alalım: yatay parçada $dy = 0$, düşey parçada $dx = 0$'dır ve

$$f(x, y) = \int_a^x P(t, b)\,dt + \int_b^y Q(x, s)\,ds$$

olur.

**$y$'ye göre türev.** İlk terim $y$'ye bağlı değildir. İkinci terim, üst sınırı $y$ olan bir integraldir ve $s \mapsto Q(x, s)$ sürekli olduğundan türevi $Q(x, y)$'dir (bkz. [Analiz 2](../analiz-2/analizin-temel-teoremleri.html#thm-temel-teorem-ikinci)). Demek ki $f_y = Q$.

**$x$'e göre türev.** İlk terimin $x$'e göre türevi aynı nedenle $P(x, b)$'dir. İkinci terimde $x$ integralin içindedir. Türevi integral işaretinin altına geçirebilmek için düşey doğru parçasını içine alan ve $D$'de kalan kapalı bir dikdörtgen gerekir. Küçük bir $\delta > 0$ için $[x - \delta, x + \delta] \times [b, y]$ dikdörtgeni ($y < b$ ise $[y, b]$) böyledir. $D = (\alpha_1, \alpha_2) \times (\beta_1, \beta_2)$ bir dikdörtgense $b$ ile $y$, $(\beta_1, \beta_2)$ aralığındadır; $\delta$'yı $x - \alpha_1$ ve $\alpha_2 - x$ sayılarından küçük seçmek yeter. $D$, yarıçapı $\rho$ olan bir diskse dikdörtgenin her $(u, s)$ noktası için $|u - a| \le |x - a| + \delta$ ve $|s - b| \le |y - b|$ olduğundan

$$(u - a)^2 + (s - b)^2 \le \big( |x - a| + \delta \big)^2 + (y - b)^2$$

olur. $\delta \to 0$ iken sağ taraf $(x - a)^2 + (y - b)^2 < \rho^2$ sayısına yaklaştığından küçük $\delta$ için o da $\rho^2$'den küçüktür.

Bu dikdörtgende $Q$ ve $Q_x$ sürekli olduğundan türev integral işaretinin altına geçer (bkz. [Analiz 3](../analiz-3/parametreye-bagli-integraller.html#thm-par-turev)). Sonra $Q_x = P_y$ varsayımını ve $s$ değişkenine göre (1) eşitliğini kullanırız:

$$
\begin{aligned}
\frac{\partial}{\partial x} \int_b^y Q(x, s)\,ds &= \int_b^y \frac{\partial Q}{\partial x}(x, s)\,ds = \int_b^y \frac{\partial P}{\partial y}(x, s)\,ds \\[1mm]
&= P(x, y) - P(x, b).
\end{aligned}
$$

İki terimi toplarsak

$$f_x = P(x, b) + P(x, y) - P(x, b) = P(x, y)$$

bulunur. Demek ki $\nabla f = \mathbf{F}$ ve $\mathbf{F}$ konservatiftir. [$\blacksquare$]{.qed}
:::

::: {.ispat baslik="Genel bölge için ispatın fikri"}
Genel bir basit bağlantılı bölgede L biçimli yollar $D$'den çıkabilir; bu yüzden başka bir yol izlenir. $C$, $D$ içinde basit kapalı bir yol ve $R$, $C$'nin çevrelediği bölge olsun. $D$ basit bağlantılı olduğundan $R$ de $D$'nin içindedir, yani $P_y = Q_x$ eşitliği $R$'nin her noktasında geçerlidir. Bir sonraki bölümde göreceğimiz Green teoremi (@thm-grn-green), kapalı bir eğri boyunca eğrisel integrali eğrinin çevrelediği bölge üzerinde bir iki katlı integrale çevirir:

$$\int_C P\,dx + Q\,dy = \pm \iint_R \left( \frac{\partial Q}{\partial x} - \frac{\partial P}{\partial y} \right) dA = 0.$$

İşaret, $C$'nin dolaşılma yönüne bağlıdır. Demek ki her basit kapalı yolda integral sıfırdır. Kendisini kesen kapalı yollar basit kapalı parçalara ayrılarak aynı sonuca ulaşılır; ardından @thm-tte-yoldan-bagimsizlik integralin yoldan bağımsız olduğunu, @thm-tte-konservatif de $\mathbf{F}$'nin konservatif olduğunu verir. Green teoreminin rastgele bir basit kapalı eğri için ispatı ve kendisini sonsuz kez kesebilen yolların bu biçimde ele alınması ileri analiz gerektirir.
:::
::::

Ölçütü iki alanda deneyelim.

:::: {#exm-tte-konservatif-degil name="Konservatif Olmayan Bir Alan"}
$\mathbf{F}(x, y) = (x - y)\,\mathbf{i} + (x - 2)\,\mathbf{j}$ alanının konservatif olup olmadığını belirleyiniz.

::: {.cozum}
$P(x, y) = x - y$ ve $Q(x, y) = x - 2$'dir. Buradan

$$\frac{\partial P}{\partial y} = -1, \qquad \frac{\partial Q}{\partial x} = 1$$

olur. Kısmi türevler her yerde sürekli ama hiçbir noktada eşit değildir. @thm-tte-gerekli-kosul gereği $\mathbf{F}$ konservatif değildir.

Aynı sonucu bir kapalı yolla da görebiliriz. Merkezi $(2, 2)$, yarıçapı $2$ olan $C$ çemberini

$$\mathbf{r}(t) = \langle 2 + 2\cos t,\ 2 + 2\sin t \rangle, \qquad 0 \le t \le 2\pi$$

diye saat yönünün tersine dolaşalım. Bu çember üzerinde $x - y = 2\cos t - 2\sin t$ ve $x - 2 = 2\cos t$'dir; $\mathbf{r}'(t) = \langle -2\sin t,\ 2\cos t \rangle$ olduğundan

$$
\begin{aligned}
\mathbf{F}(\mathbf{r}(t)) \cdot \mathbf{r}'(t) &= -4\sin t \cos t + 4\sin^2 t + 4\cos^2 t \\[1mm]
&= 4 - 2\sin 2t
\end{aligned}
$$

ve

$$\int_C \mathbf{F} \cdot d\mathbf{r} = \int_0^{2\pi} (4 - 2\sin 2t)\,dt = 8\pi$$

bulunur. Kapalı bir yolda integral sıfırdan farklı olduğundan, @cor-tte-denk-kosullar gereği $\mathbf{F}$ konservatif olamaz. [$\blacksquare$]{.qed}
:::
::::

:::: {#exm-tte-konservatif name="Konservatif Bir Alan"}
$$\mathbf{F}(x, y) = (3 + 2xy)\,\mathbf{i} + (x^2 - 3y^2)\,\mathbf{j}$$

alanının konservatif olup olmadığını belirleyiniz.

::: {.cozum}
$P(x, y) = 3 + 2xy$ ve $Q(x, y) = x^2 - 3y^2$'dir. Buradan

$$\frac{\partial P}{\partial y} = 2x = \frac{\partial Q}{\partial x}$$

olur. $\mathbf{F}$'nin tanım kümesi bütün düzlemdir; düzlem açık ve basit bağlantılıdır, kısmi türevler de her yerde süreklidir. @thm-tte-konservatif-test gereği $\mathbf{F}$ konservatiftir. [$\blacksquare$]{.qed}
:::
::::

Ölçütün ne söylediğini bu iki alanın resimlerinden de sezebiliriz. İlk alanda $(2, 2)$ çevresindeki çember boyunca oklar hep çemberin dolaşılma yönünü gösterir: $\mathbf{F} \cdot \mathbf{T}$ her yerde pozitiftir, bu yüzden kapalı yol boyunca integral pozitif olmak zorundadır. İkinci alanda kapalı bir eğrinin bazı yerlerinde oklar eğrinin yönünü, bazı yerlerinde ters yönü gösterir; katkılar birbirini götürebilir ve gerçekten de her kapalı yolda toplam sıfırdır.

```{=html}
<figure class="ders-grafik ders-grafik-genis">
<svg viewBox="14.0 8.0 693.5 364.5" role="img" aria-label="Two arrow plots: the field (x - y, x - 2) on the square from -1 to 5 with the circle of radius 2 about (2, 2), along which every arrow points counterclockwise; the field (3 + 2xy, x^2 - 3y^2) on the square from -2 to 2 with a circle of radius 1.2 along which the arrows point partly along and partly against the curve">
  <rect x="40.0" y="40.0" width="301.5" height="301.5" rx="7" fill="none" stroke="var(--academic-text)" stroke-width="1.1" opacity="0.35"/>
  <path d="M62.5,319.0L62.5,324.1M62.5,293.3L61.5,298.5M62.5,267.7L60.4,272.8M62.5,242.0L59.3,247.5M62.5,216.4L57.9,222.1M62.5,190.7L56.4,196.8M62.5,165.1L54.9,171.5M62.5,139.4L53.2,146.1M62.5,113.8L51.5,120.6M62.5,88.1L49.8,95.2M62.5,62.5L48.1,69.7M88.2,319.0L89.2,323.1M88.2,293.3L88.2,297.5M88.2,267.7L87.1,271.8M88.2,242.0L86.1,246.2M88.2,216.4L85.1,220.5M88.2,190.7L83.9,195.0M88.2,165.1L82.4,169.7M88.2,139.4L80.8,144.4M88.2,113.8L79.1,119.0M88.2,88.1L77.4,93.5M88.2,62.5L75.7,68.1M113.8,319.0L115.9,322.1M113.8,293.3L114.8,296.4M113.8,267.7L113.8,270.8M113.8,242.0L112.8,245.1M113.8,216.4L111.7,219.5M113.8,190.7L110.7,193.8M113.8,165.1L109.7,168.2M113.8,139.4L108.4,142.7M113.8,113.8L106.7,117.3M113.8,88.1L105.0,91.9M113.8,62.5L103.2,66.5M139.4,319.0L142.5,321.1M139.4,293.3L141.5,295.4M139.4,267.7L140.5,269.8M139.4,242.0L139.4,244.1M139.4,216.4L138.4,218.5M139.4,190.7L137.4,192.8M139.4,165.1L136.4,167.2M139.4,139.4L135.3,141.5M139.4,113.8L134.3,115.9M139.4,88.1L132.6,90.4M139.4,62.5L130.8,65.0M165.1,319.0L169.2,320.0M165.1,293.3L168.2,294.4M165.1,267.7L167.2,268.7M165.1,242.0L166.1,243.1M165.1,216.4L165.1,217.4M165.1,190.7L164.1,191.8M165.1,165.1L163.0,166.1M165.1,139.4L162.0,140.5M165.1,113.8L161.0,114.8M165.1,88.1L160.0,89.2M165.1,62.5L158.4,63.6M190.7,319.0L195.9,319.0M190.7,293.3L194.9,293.3M190.7,267.7L193.8,267.7M190.7,242.0L192.8,242.0M190.7,216.4L191.8,216.4M190.7,165.1L189.7,165.1M190.7,139.4L188.7,139.4M190.7,113.8L187.7,113.8M190.7,88.1L186.6,88.1M190.7,62.5L185.6,62.5M216.4,319.0L223.1,317.9M216.4,293.3L221.5,292.3M216.4,267.7L220.5,266.7M216.4,242.0L219.5,241.0M216.4,216.4L218.5,215.4M216.4,190.7L217.4,189.7M216.4,165.1L216.4,164.1M216.4,139.4L215.4,138.4M216.4,113.8L214.3,112.8M216.4,88.1L213.3,87.1M216.4,62.5L212.3,61.5M242.0,319.0L250.7,316.5M242.0,293.3L248.9,291.1M242.0,267.7L247.2,265.6M242.0,242.0L246.2,240.0M242.0,216.4L245.1,214.3M242.0,190.7L244.1,188.7M242.0,165.1L243.1,163.0M242.0,139.4L242.0,137.4M242.0,113.8L241.0,111.7M242.0,88.1L240.0,86.1M242.0,62.5L239.0,60.4M267.7,319.0L278.3,315.0M267.7,293.3L276.5,289.6M267.7,267.7L274.8,264.2M267.7,242.0L273.1,238.8M267.7,216.4L271.8,213.3M267.7,190.7L270.8,187.7M267.7,165.1L269.8,162.0M267.7,139.4L268.7,136.4M267.7,113.8L267.7,110.7M267.7,88.1L266.7,85.1M267.7,62.5L265.6,59.4M293.4,319.0L305.8,313.4M293.4,293.3L304.1,288.0M293.4,267.7L302.4,262.5M293.4,242.0L300.7,237.1M293.4,216.4L299.1,211.8M293.4,190.7L297.6,186.5M293.4,165.1L296.4,161.0M293.4,139.4L295.4,135.3M293.4,113.8L294.4,109.7M293.4,88.1L293.4,84.0M293.4,62.5L292.3,58.4M319.0,319.0L333.4,311.8M319.0,293.3L331.7,286.3M319.0,267.7L330.0,260.9M319.0,242.0L328.3,235.4M319.0,216.4L326.6,210.0M319.0,190.7L325.1,184.7M319.0,165.1L323.6,159.4M319.0,139.4L322.2,134.0M319.0,113.8L321.1,108.7M319.0,88.1L320.0,83.0M319.0,62.5L319.0,57.4" fill="none" stroke="var(--color-theory)" stroke-width="1.1" stroke-linecap="round" opacity="0.8"/>
  <path d="M62.5,328.2L60.4,323.1L64.6,323.1ZM60.7,302.5L59.6,297.1L63.8,297.9ZM58.8,276.9L58.7,271.0L63.0,272.7ZM57.0,251.2L57.8,245.3L61.8,247.7ZM55.2,225.6L56.8,219.8L60.4,222.7ZM53.3,199.9L55.6,194.4L58.8,197.7ZM51.5,174.3L54.2,169.0L57.2,172.5ZM49.7,148.6L52.8,143.6L55.5,147.3ZM47.8,123.0L51.3,118.1L53.7,122.0ZM46.0,97.3L49.7,92.6L51.9,96.7ZM44.1,71.7L48.0,67.2L50.1,71.3ZM90.0,326.3L87.3,322.7L90.7,321.9ZM88.2,300.7L86.5,296.7L89.8,296.7ZM86.3,275.0L85.6,270.6L89.0,271.4ZM84.5,249.4L84.8,244.5L88.2,246.2ZM82.6,223.7L84.0,218.4L87.4,221.0ZM80.8,198.1L83.1,192.6L86.3,195.8ZM79.0,172.4L81.8,167.2L84.7,170.8ZM77.1,146.8L80.4,141.8L83.0,145.7ZM75.3,121.1L78.9,116.4L81.2,120.4ZM73.5,95.5L77.4,91.0L79.4,95.1ZM71.6,69.8L75.7,65.5L77.6,69.7ZM117.5,324.5L114.2,322.3L116.7,320.6ZM115.6,298.9L113.4,296.3L115.9,295.4ZM113.8,273.2L112.5,270.2L115.1,270.2ZM112.0,247.6L111.7,244.1L114.2,245.0ZM110.1,221.9L110.9,218.0L113.4,219.7ZM108.3,196.3L110.1,192.0L112.6,194.5ZM106.5,170.6L109.2,165.9L111.8,169.3ZM104.6,145.0L108.2,140.1L110.5,144.1ZM102.8,119.3L106.7,114.8L108.7,118.9ZM101.0,93.7L105.1,89.4L106.9,93.6ZM99.1,68.0L103.5,63.9L105.1,68.2ZM145.0,322.7L141.1,321.9L142.8,319.4ZM143.1,297.0L140.3,295.8L141.9,294.2ZM141.3,271.4L139.4,269.8L141.1,268.9ZM139.4,245.7L138.6,243.7L140.3,243.7ZM137.6,220.1L137.8,217.6L139.5,218.5ZM135.8,194.4L137.0,191.6L138.6,193.2ZM133.9,168.8L136.1,165.5L137.8,168.0ZM132.1,143.1L135.3,139.4L137.0,142.8ZM130.3,117.5L134.5,113.3L136.2,117.6ZM128.4,91.8L132.9,87.9L134.4,92.3ZM126.6,66.2L131.3,62.4L132.5,66.9ZM172.4,320.8L168.0,321.5L168.8,318.1ZM170.6,295.2L167.2,295.4L168.0,292.9ZM168.8,269.5L166.3,269.4L167.2,267.7ZM166.9,243.9L165.5,243.3L166.3,242.5ZM165.1,218.2L164.7,217.2L165.5,217.2ZM163.3,192.6L163.9,191.2L164.7,192.0ZM161.4,166.9L163.0,165.1L163.9,166.8ZM159.6,141.3L162.2,139.0L163.0,141.5ZM157.8,115.6L161.4,112.9L162.2,116.3ZM155.9,90.0L160.5,86.9L161.4,91.1ZM154.1,64.3L159.1,61.2L159.9,65.7ZM199.9,319.0L194.9,321.1L194.9,316.9ZM198.1,293.3L194.1,295.0L194.1,291.7ZM196.3,267.7L193.2,269.0L193.2,266.4ZM194.4,242.0L192.4,242.9L192.4,241.2ZM192.6,216.4L191.6,216.8L191.6,216.0ZM188.9,165.1L189.9,164.7L189.9,165.5ZM187.1,139.4L189.1,138.6L189.1,140.3ZM185.2,113.8L188.3,112.5L188.3,115.1ZM183.4,88.1L187.4,86.5L187.4,89.8ZM181.6,62.5L186.6,60.4L186.6,64.6ZM227.4,317.2L222.4,320.3L221.6,315.8ZM225.6,291.5L221.0,294.6L220.1,290.4ZM223.7,265.9L220.1,268.6L219.3,265.2ZM221.9,240.2L219.3,242.5L218.5,240.0ZM220.1,214.6L218.5,216.4L217.6,214.7ZM218.2,188.9L217.6,190.3L216.8,189.5ZM216.4,163.3L216.8,164.3L216.0,164.3ZM214.6,137.6L216.0,138.2L215.2,139.0ZM212.7,112.0L215.2,112.1L214.3,113.8ZM210.9,86.3L214.3,86.1L213.5,88.6ZM209.1,60.7L213.5,60.0L212.7,63.4ZM254.9,315.3L250.2,319.1L249.0,314.6ZM253.1,289.7L248.6,293.6L247.1,289.2ZM251.2,264.0L247.0,268.2L245.3,263.9ZM249.4,238.4L246.2,242.1L244.5,238.7ZM247.6,212.7L245.4,216.0L243.7,213.5ZM245.7,187.1L244.5,189.9L242.9,188.3ZM243.9,161.4L243.7,163.9L242.0,163.0ZM242.0,135.8L242.9,137.8L241.2,137.8ZM240.2,110.1L242.1,111.7L240.4,112.6ZM238.4,84.5L241.2,85.7L239.6,87.3ZM236.5,58.8L240.4,59.6L238.7,62.1ZM282.4,313.5L278.0,317.6L276.4,313.3ZM280.5,287.8L276.4,292.1L274.6,287.9ZM278.7,262.2L274.8,266.7L272.8,262.6ZM276.9,236.5L273.3,241.4L271.0,237.4ZM275.0,210.9L272.3,215.6L269.7,212.2ZM273.2,185.2L271.4,189.5L268.9,187.0ZM271.4,159.6L270.6,163.5L268.1,161.8ZM269.5,133.9L269.8,137.4L267.3,136.5ZM267.7,108.3L269.0,111.3L266.4,111.3ZM265.9,82.6L268.1,85.2L265.6,86.1ZM264.0,57.0L267.3,59.2L264.8,60.9ZM309.9,311.7L305.8,316.0L303.9,311.8ZM308.0,286.0L304.1,290.5L302.1,286.4ZM306.2,260.4L302.6,265.1L300.3,261.1ZM304.4,234.7L301.1,239.7L298.5,235.8ZM302.5,209.1L299.7,214.3L296.8,210.7ZM300.7,183.4L298.4,188.9L295.2,185.7ZM298.9,157.8L297.5,163.1L294.1,160.5ZM297.0,132.1L296.7,137.0L293.3,135.3ZM295.2,106.5L295.9,110.9L292.5,110.1ZM293.4,80.8L295.0,84.8L291.7,84.8ZM291.5,55.2L294.2,58.8L290.8,59.6ZM337.4,309.8L333.5,314.3L331.4,310.2ZM335.5,284.2L331.8,288.9L329.6,284.8ZM333.7,258.5L330.2,263.4L327.8,259.5ZM331.8,232.9L328.7,237.9L326.0,234.2ZM330.0,207.2L327.3,212.5L324.3,209.0ZM328.2,181.6L325.9,187.1L322.7,183.8ZM326.3,155.9L324.7,161.7L321.1,158.8ZM324.5,130.3L323.7,136.2L319.7,133.8ZM322.7,104.6L322.8,110.5L318.5,108.8ZM320.8,79.0L321.9,84.4L317.7,83.6ZM319.0,53.3L321.1,58.4L316.9,58.4Z" fill="var(--color-theory)" stroke="none" opacity="0.8"/>
  <circle cx="190.7" cy="190.7" r="1.3" fill="var(--color-theory)"/>
  <path d="M280.8,190.7 L280.6,186.0 L280.3,181.3 L279.6,176.7 L278.8,172.0 L277.7,167.5 L276.3,162.9 L274.8,158.5 L273.0,154.1 L270.9,149.9 L268.7,145.7 L266.2,141.7 L263.6,137.8 L260.7,134.1 L257.6,130.5 L254.4,127.1 L251.0,123.9 L247.4,120.8 L243.7,117.9 L239.8,115.3 L235.7,112.8 L231.6,110.6 L227.4,108.5 L223.0,106.7 L218.6,105.2 L214.0,103.8 L209.5,102.7 L204.8,101.9 L200.2,101.2 L195.5,100.9 L190.8,100.7 L186.0,100.9 L181.3,101.2 L176.7,101.9 L172.0,102.7 L167.5,103.8 L162.9,105.2 L158.5,106.7 L154.1,108.5 L149.9,110.6 L145.8,112.8 L141.7,115.3 L137.8,117.9 L134.1,120.8 L130.5,123.9 L127.1,127.1 L123.9,130.5 L120.8,134.1 L117.9,137.8 L115.3,141.7 L112.8,145.7 L110.6,149.9 L108.5,154.1 L106.7,158.5 L105.2,162.9 L103.8,167.5 L102.7,172.0 L101.9,176.7 L101.2,181.3 L100.9,186.0 L100.8,190.7 L100.9,195.5 L101.2,200.2 L101.9,204.8 L102.7,209.5 L103.8,214.0 L105.2,218.6 L106.7,223.0 L108.5,227.4 L110.6,231.6 L112.8,235.7 L115.3,239.8 L117.9,243.7 L120.8,247.4 L123.9,251.0 L127.1,254.4 L130.5,257.6 L134.1,260.7 L137.8,263.6 L141.7,266.2 L145.7,268.7 L149.9,270.9 L154.1,273.0 L158.5,274.8 L162.9,276.3 L167.5,277.7 L172.0,278.8 L176.7,279.6 L181.3,280.3 L186.0,280.6 L190.7,280.7 L195.5,280.6 L200.2,280.3 L204.8,279.6 L209.5,278.8 L214.0,277.7 L218.6,276.3 L223.0,274.8 L227.4,273.0 L231.6,270.9 L235.7,268.7 L239.8,266.2 L243.7,263.6 L247.4,260.7 L251.0,257.6 L254.4,254.4 L257.6,251.0 L260.7,247.4 L263.6,243.7 L266.2,239.8 L268.7,235.8 L270.9,231.6 L273.0,227.4 L274.8,223.0 L276.3,218.6 L277.7,214.0 L278.8,209.5 L279.6,204.8 L280.3,200.2 L280.6,195.5 L280.8,190.7" fill="none" stroke="var(--color-practice)" stroke-width="2.2" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="265.4" y1="140.4" x2="257.9" y2="131.5" stroke="var(--color-practice)" stroke-width="2.2" opacity="1.0" stroke-linecap="round"/>
  <polygon points="253.3,126.0 261.9,130.5 256.2,135.3" fill="var(--color-practice)" opacity="1.0"/>
  <line x1="109.9" y1="151.3" x2="105.9" y2="162.2" stroke="var(--color-practice)" stroke-width="2.2" opacity="1.0" stroke-linecap="round"/>
  <polygon points="103.4,169.0 102.9,159.2 110.1,161.8" fill="var(--color-practice)" opacity="1.0"/>
  <line x1="197.0" y1="280.5" x2="208.5" y2="278.5" stroke="var(--color-practice)" stroke-width="2.2" opacity="1.0" stroke-linecap="round"/>
  <polygon points="215.6,277.3 207.4,282.5 206.0,275.1" fill="var(--color-practice)" opacity="1.0"/>
  <circle cx="190.8" cy="190.7" r="3.2" fill="var(--academic-text)"/>
  <text x="100.8" y="356.5" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">0</text>
  <text x="34.0" y="284.7" fill="var(--academic-text)" font-size="10.5" text-anchor="end">0</text>
  <text x="190.8" y="356.5" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">2</text>
  <text x="34.0" y="194.7" fill="var(--academic-text)" font-size="10.5" text-anchor="end">2</text>
  <text x="280.8" y="356.5" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">4</text>
  <text x="34.0" y="104.7" fill="var(--academic-text)" font-size="10.5" text-anchor="end">4</text>
  <rect x="172.5" y="198.3" width="36.5" height="13.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="190.8" y="207.7" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">(2, 2)</text>
  <rect x="267.2" y="249.2" width="11.5" height="16.0" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="269.7" y="260.6" fill="var(--color-practice)" font-size="13" text-anchor="start" font-weight="600"><tspan font-style="italic">C</tspan></text>
  <text x="190.7" y="32.0" fill="var(--academic-text)" font-size="11.5" text-anchor="middle" font-weight="600">(a)  <tspan font-style="italic">P</tspan> = <tspan font-style="italic">x</tspan> &#8722; <tspan font-style="italic">y</tspan>,  <tspan font-style="italic">Q</tspan> = <tspan font-style="italic">x</tspan> &#8722; 2</text>
  <rect x="391.5" y="40.0" width="301.4" height="301.4" rx="7" fill="none" stroke="var(--academic-text)" stroke-width="1.1" opacity="0.35"/>
  <path d="M418.9,314.0L434.5,324.7M418.9,286.6L431.0,290.6M418.9,259.2L427.9,258.9M418.9,231.8L425.3,229.1M418.9,204.4L423.1,200.9M418.9,177.0L421.5,173.5M418.9,149.6L419.9,147.1M418.9,94.8L416.6,97.8M418.9,67.4L413.9,76.7M446.3,314.0L459.4,326.7M446.3,286.6L456.5,292.4M446.3,259.2L453.7,260.5M446.3,231.8L451.6,230.8M446.3,204.4L450.3,202.3M446.3,177.0L449.1,174.9M446.3,149.6L447.8,148.6M446.3,122.2L446.5,123.4M446.3,94.8L445.3,99.3M446.3,67.4L443.3,78.9M473.7,314.0L484.4,328.2M473.7,286.6L482.1,293.7M473.7,259.2L479.8,261.6M473.7,231.8L478.5,231.9M473.7,204.4L477.6,203.4M473.7,177.0L476.7,176.0M473.7,149.6L475.7,149.7M473.7,122.2L474.8,124.5M473.7,94.8L473.9,100.3M473.7,67.4L472.8,80.7M501.1,314.0L509.4,329.1M501.1,286.6L507.7,294.4M501.1,259.2L505.9,262.2M501.1,231.8L505.3,232.6M501.1,204.4L504.8,204.1M501.1,177.0L504.2,176.7M501.1,149.6L503.7,150.4M501.1,122.2L503.1,125.2M501.1,94.8L502.8,101.7M501.1,67.4L502.4,82.0M528.5,314.0L534.5,329.5M528.5,286.6L533.4,294.7M528.5,259.2L532.4,262.6M528.5,231.8L532.2,233.0M528.5,204.4L532.0,204.5M528.5,177.0L531.8,177.1M528.5,149.6L531.6,150.8M528.5,122.2L531.5,125.6M528.5,94.8L531.8,102.6M528.5,67.4L532.1,82.8M555.9,314.0L559.5,329.4M555.9,286.6L559.2,294.4M555.9,259.2L558.9,262.6M555.9,231.8L559.0,233.0M555.9,204.4L559.2,204.5M555.9,177.0L559.4,177.1M555.9,149.6L559.6,150.8M555.9,122.2L559.8,125.6M555.9,94.8L560.8,102.9M555.9,67.4L561.9,82.9M583.3,314.0L584.6,328.6M583.3,286.6L585.0,293.5M583.3,259.2L585.3,262.2M583.3,231.8L585.9,232.6M583.3,204.4L586.4,204.1M583.3,177.0L587.0,176.7M583.3,149.6L587.5,150.4M583.3,122.2L588.1,125.2M583.3,94.8L589.9,102.6M583.3,67.4L591.6,82.5M610.7,314.0L609.8,327.3M610.7,286.6L610.9,292.1M610.7,259.2L611.8,261.5M610.7,231.8L612.7,231.9M610.7,204.4L613.7,203.4M610.7,177.0L614.6,176.0M610.7,149.6L615.5,149.7M610.7,122.2L616.8,124.6M610.7,94.8L619.1,101.9M610.7,67.4L621.4,81.6M638.1,314.0L635.1,325.5M638.1,286.6L637.1,291.1M638.1,259.2L638.3,260.4M638.1,231.8L639.6,230.8M638.1,204.4L640.9,202.3M638.1,177.0L642.1,174.9M638.1,149.6L643.4,148.6M638.1,122.2L645.5,123.5M638.1,94.8L648.3,100.6M638.1,67.4L651.2,80.1M665.5,314.0L660.5,323.3M665.5,286.6L663.2,289.6M665.5,231.8L666.5,229.3M665.5,204.4L668.1,200.9M665.5,177.0L669.7,173.5M665.5,149.6L671.9,146.9M665.5,122.2L674.5,121.9M665.5,94.8L677.6,98.8M665.5,67.4L681.1,78.1" fill="none" stroke="var(--color-theory)" stroke-width="1.1" stroke-linecap="round" opacity="0.8"/>
  <path d="M438.1,327.1L432.3,325.9L434.9,322.1ZM435.2,292.0L429.3,292.4L430.7,288.0ZM432.3,258.7L426.9,261.2L426.7,256.6ZM429.4,227.4L425.2,231.7L423.4,227.4ZM426.4,198.1L423.8,203.3L420.8,199.8ZM423.5,170.7L422.4,175.2L419.5,173.1ZM420.6,145.2L420.7,148.0L418.7,147.2ZM414.8,100.2L415.8,96.3L418.3,98.2ZM411.8,80.5L412.4,74.6L416.5,76.8ZM462.6,329.7L457.0,327.6L460.3,324.3ZM460.3,294.6L454.4,293.8L456.7,289.8ZM458.1,261.3L452.2,262.6L453.1,258.1ZM455.8,230.0L451.0,233.2L450.2,228.8ZM453.5,200.7L450.4,204.4L448.7,201.1ZM451.2,173.3L449.4,176.5L447.7,174.2ZM449.0,147.8L447.9,149.4L447.1,148.2ZM446.7,124.3L446.0,123.2L447.0,123.1ZM444.4,102.8L443.6,97.9L447.3,98.8ZM442.2,83.1L441.3,77.2L445.8,78.4ZM487.1,331.7L481.9,328.7L485.6,325.9ZM485.5,296.5L479.8,294.7L482.7,291.2ZM483.8,263.3L477.9,263.4L479.6,259.1ZM482.2,232.0L477.5,233.8L477.6,229.9ZM480.6,202.6L477.2,205.2L476.4,202.0ZM479.0,175.2L476.5,177.4L475.7,175.0ZM477.4,149.8L475.3,150.5L475.4,148.8ZM475.7,126.3L473.7,124.5L475.5,123.6ZM474.1,104.7L471.6,99.3L476.2,99.2ZM472.5,85.1L470.6,79.4L475.2,79.8ZM511.6,333.0L506.9,329.3L510.9,327.1ZM510.6,297.8L505.3,295.1L508.8,292.1ZM509.6,264.6L503.7,263.6L506.2,259.7ZM508.6,233.3L504.2,234.2L504.8,230.7ZM507.7,203.9L504.2,205.7L503.9,202.7ZM506.7,176.5L503.7,178.1L503.5,175.5ZM505.7,151.1L502.8,151.3L503.5,149.2ZM504.8,127.6L501.5,125.5L504.0,123.8ZM503.8,106.0L500.3,101.2L504.7,100.1ZM502.8,86.4L500.0,81.1L504.6,80.7ZM536.0,333.6L531.9,329.3L536.2,327.7ZM535.7,298.4L530.9,295.0L534.8,292.5ZM535.4,265.2L530.2,263.5L533.0,260.3ZM535.1,233.9L531.0,234.3L531.9,231.2ZM534.7,204.6L531.3,205.9L531.3,203.0ZM534.4,177.2L531.1,178.4L531.2,175.7ZM534.1,151.7L530.5,151.8L531.5,149.3ZM533.8,128.2L529.5,126.1L532.3,123.7ZM533.4,106.6L529.2,102.5L533.5,100.7ZM533.1,87.0L529.6,82.2L534.1,81.1ZM560.5,333.6L557.0,328.8L561.5,327.7ZM560.8,298.4L556.6,294.3L560.9,292.5ZM561.2,265.2L556.9,263.1L559.7,260.7ZM561.5,233.9L557.9,234.0L558.9,231.5ZM561.8,204.6L558.5,205.8L558.6,203.1ZM562.1,177.2L558.7,178.5L558.7,175.6ZM562.5,151.7L558.4,152.1L559.3,149.0ZM562.8,128.2L557.6,126.5L560.4,123.3ZM563.1,106.6L558.3,103.2L562.2,100.7ZM563.4,87.0L559.3,82.7L563.6,81.1ZM585.0,333.0L582.2,327.7L586.8,327.3ZM586.0,297.8L582.5,293.0L586.9,291.9ZM587.0,264.6L583.7,262.5L586.2,260.8ZM587.9,233.3L585.0,233.5L585.7,231.4ZM588.9,203.9L585.9,205.5L585.7,202.9ZM589.9,176.5L586.4,178.3L586.1,175.3ZM590.8,151.1L586.4,152.0L587.0,148.5ZM591.8,127.6L585.9,126.6L588.4,122.7ZM592.8,106.0L587.5,103.3L591.0,100.3ZM593.8,86.4L589.1,82.7L593.1,80.5ZM609.5,331.7L607.6,326.0L612.2,326.4ZM611.1,296.5L608.6,291.1L613.2,291.0ZM612.7,263.3L610.7,261.5L612.5,260.6ZM614.4,232.0L612.3,232.7L612.4,231.0ZM616.0,202.6L613.5,204.8L612.7,202.4ZM617.6,175.2L614.2,177.8L613.4,174.6ZM619.2,149.8L614.5,151.6L614.6,147.7ZM620.8,126.3L614.9,126.4L616.6,122.1ZM622.5,104.7L616.8,102.9L619.7,99.4ZM624.1,85.1L618.9,82.1L622.6,79.3ZM634.0,329.7L633.1,323.8L637.6,325.0ZM636.2,294.6L635.4,289.7L639.1,290.6ZM638.5,261.3L637.8,260.2L638.8,260.1ZM640.8,230.0L639.7,231.6L638.9,230.4ZM643.0,200.7L641.2,203.9L639.5,201.6ZM645.3,173.3L642.2,177.0L640.5,173.7ZM647.6,147.8L642.8,151.0L642.0,146.6ZM649.9,124.3L644.0,125.6L644.9,121.1ZM652.1,102.8L646.2,102.0L648.5,98.0ZM654.4,83.1L648.8,81.0L652.1,77.7ZM658.4,327.1L659.0,321.2L663.1,323.4ZM661.4,292.0L662.4,288.1L664.9,290.0ZM667.2,227.4L667.3,230.2L665.3,229.4ZM670.1,198.1L669.0,202.6L666.1,200.5ZM673.0,170.7L670.4,175.9L667.4,172.4ZM676.0,145.2L671.8,149.5L670.0,145.2ZM678.9,121.7L673.5,124.2L673.3,119.6ZM681.8,100.2L675.9,100.6L677.3,96.2ZM684.7,80.5L678.9,79.3L681.5,75.5Z" fill="var(--color-theory)" stroke="none" opacity="0.8"/>
  <circle cx="418.9" cy="122.2" r="1.3" fill="var(--color-theory)"/>
  <circle cx="665.5" cy="259.2" r="1.3" fill="var(--color-theory)"/>
  <path d="M624.4,190.7 L624.3,186.4 L623.9,182.1 L623.4,177.8 L622.6,173.6 L621.6,169.4 L620.4,165.3 L618.9,161.2 L617.3,157.3 L615.4,153.4 L613.4,149.6 L611.1,145.9 L608.7,142.4 L606.1,139.0 L603.3,135.7 L600.3,132.6 L597.2,129.6 L593.9,126.8 L590.5,124.2 L587.0,121.8 L583.3,119.5 L579.5,117.5 L575.6,115.6 L571.7,114.0 L567.6,112.5 L563.5,111.3 L559.3,110.3 L555.1,109.5 L550.8,109.0 L546.5,108.6 L542.2,108.5 L537.9,108.6 L533.6,109.0 L529.3,109.5 L525.1,110.3 L520.9,111.3 L516.8,112.5 L512.7,114.0 L508.8,115.6 L504.9,117.5 L501.1,119.5 L497.4,121.8 L493.9,124.2 L490.5,126.8 L487.2,129.6 L484.1,132.6 L481.1,135.7 L478.3,139.0 L475.7,142.4 L473.3,145.9 L471.0,149.6 L469.0,153.4 L467.1,157.3 L465.5,161.2 L464.0,165.3 L462.8,169.4 L461.8,173.6 L461.0,177.8 L460.5,182.1 L460.1,186.4 L460.0,190.7 L460.1,195.0 L460.5,199.3 L461.0,203.6 L461.8,207.8 L462.8,212.0 L464.0,216.1 L465.5,220.2 L467.1,224.1 L469.0,228.0 L471.0,231.8 L473.3,235.5 L475.7,239.0 L478.3,242.4 L481.1,245.7 L484.1,248.8 L487.2,251.8 L490.5,254.6 L493.9,257.2 L497.4,259.6 L501.1,261.9 L504.9,263.9 L508.8,265.8 L512.7,267.4 L516.8,268.9 L520.9,270.1 L525.1,271.1 L529.3,271.9 L533.6,272.4 L537.9,272.8 L542.2,272.9 L546.5,272.8 L550.8,272.4 L555.1,271.9 L559.3,271.1 L563.5,270.1 L567.6,268.9 L571.7,267.4 L575.6,265.8 L579.5,263.9 L583.3,261.9 L587.0,259.6 L590.5,257.2 L593.9,254.6 L597.2,251.8 L600.3,248.8 L603.3,245.7 L606.1,242.4 L608.7,239.0 L611.1,235.5 L613.4,231.8 L615.4,228.0 L617.3,224.1 L618.9,220.2 L620.4,216.1 L621.6,212.0 L622.6,207.8 L623.4,203.6 L623.9,199.3 L624.3,195.0 L624.4,190.7" fill="none" stroke="var(--color-practice)" stroke-width="2.2" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="617.9" y1="158.6" x2="611.4" y2="147.5" stroke="var(--color-practice)" stroke-width="2.2" opacity="1.0" stroke-linecap="round"/>
  <polygon points="607.8,141.2 615.6,147.1 609.1,150.9" fill="var(--color-practice)" opacity="1.0"/>
  <line x1="476.6" y1="141.2" x2="470.1" y2="152.3" stroke="var(--color-practice)" stroke-width="2.2" opacity="1.0" stroke-linecap="round"/>
  <polygon points="466.5,158.6 467.8,148.9 474.3,152.7" fill="var(--color-practice)" opacity="1.0"/>
  <line x1="532.2" y1="272.3" x2="545.0" y2="272.3" stroke="var(--color-practice)" stroke-width="2.2" opacity="1.0" stroke-linecap="round"/>
  <polygon points="552.2,272.3 543.2,276.1 543.2,268.5" fill="var(--color-practice)" opacity="1.0"/>
  <text x="405.2" y="356.4" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">&#8722;2</text>
  <text x="385.5" y="331.7" fill="var(--academic-text)" font-size="10.5" text-anchor="end">&#8722;2</text>
  <text x="542.2" y="356.4" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">0</text>
  <text x="385.5" y="194.7" fill="var(--academic-text)" font-size="10.5" text-anchor="end">0</text>
  <text x="679.2" y="356.4" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">2</text>
  <text x="385.5" y="57.7" fill="var(--academic-text)" font-size="10.5" text-anchor="end">2</text>
  <rect x="607.8" y="249.4" width="11.5" height="16.0" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="610.3" y="260.8" fill="var(--color-practice)" font-size="13" text-anchor="start" font-weight="600"><tspan font-style="italic">C</tspan></text>
  <text x="542.2" y="32.0" fill="var(--academic-text)" font-size="11.5" text-anchor="middle" font-weight="600">(b)  <tspan font-style="italic">P</tspan> = 3 + 2<tspan font-style="italic">xy</tspan>,  <tspan font-style="italic">Q</tspan> = <tspan font-style="italic">x</tspan><tspan font-size="8.5" dy="-5">2</tspan><tspan dy="5">&#8203;</tspan> &#8722; 3<tspan font-style="italic">y</tspan><tspan font-size="8.5" dy="-5">2</tspan><tspan dy="5">&#8203;</tspan></text>
</svg>
<figcaption>Konservatiflik ölçütünün iki örneğindeki alanlar; okların hepsi aynı oranda kısaltılmıştır. (a) Merkezi (2, 2), yarıçapı 2 olan <em>C</em> çemberi boyunca oklar hep dolaşılma yönüne bakar ve integral 8<em>π</em> çıkar. (b) Konservatif alanda <em>C</em> çemberinin bazı yerlerinde oklar dolaşılma yönüne, bazı yerlerinde ters yöne bakar; katkılar birbirini götürür ve integral 0'dır.</figcaption>
</figure>
```

::: {.callout-warning title="Basit bağlantılılık koşulu atlanamaz"}
@thm-tte-gerekli-kosul her açık kümede geçerlidir, ama onun kısmi tersi olan @thm-tte-konservatif-test bölgenin basit bağlantılı olmasını ister. Delikli bir bölgede $\partial P / \partial y = \partial Q / \partial x$ eşitliği her noktada sağlandığı hâlde alan konservatif olmayabilir. Sıradaki örnek bunu gösterir.
:::

:::: {#exm-tte-delikli-alan name="Delikli Düzlemde Konservatif Olmayan Alan"}
Orijin dışında tanımlı

$$\mathbf{F}(x, y) = \frac{-y\,\mathbf{i} + x\,\mathbf{j}}{x^2 + y^2}$$

alanı için her noktada $\partial P / \partial y = \partial Q / \partial x$ olduğu hâlde $\int_C \mathbf{F} \cdot d\mathbf{r}$ integralinin yoldan bağımsız olmadığını gösteriniz.

::: {.cozum}
**Kısmi türevler.** $P = -y/(x^2 + y^2)$ ve $Q = x/(x^2 + y^2)$'dir. Bölüm kuralıyla

$$
\begin{aligned}
\frac{\partial P}{\partial y} &= \frac{-(x^2 + y^2) + y \cdot 2y}{(x^2 + y^2)^2} = \frac{y^2 - x^2}{(x^2 + y^2)^2}, \\[1mm]
\frac{\partial Q}{\partial x} &= \frac{(x^2 + y^2) - x \cdot 2x}{(x^2 + y^2)^2} = \frac{y^2 - x^2}{(x^2 + y^2)^2}
\end{aligned}
$$

bulunur; iki türev orijin dışındaki her noktada eşit ve süreklidir.

**İki yol.** $(1, 0)$'dan $(-1, 0)$'a birim çemberin üst ve alt yarısı boyunca gidelim. Birim çember üzerinde $x^2 + y^2 = 1$ olduğundan alan $-y\,\mathbf{i} + x\,\mathbf{j}$'ye eşittir. Bölümün başındaki hesap aynen geçerlidir: üst yarı boyunca integral $\pi$, alt yarı boyunca $-\pi$'dir. Uç noktaları aynı iki yolda integraller farklı olduğundan integral yoldan bağımsız değildir ve @cor-tte-denk-kosullar gereği $\mathbf{F}$ konservatif değildir.

**Neden çelişki yok?** $\mathbf{F}$'nin tanım kümesi $D = \{(x, y) \mid (x, y) \ne (0, 0)\}$'dır. Birim çember $D$'nin içinde bir basit kapalı eğridir ama $D$'de olmayan orijini çevreler; yani $D$ basit bağlantılı değildir. Konservatiflik ölçütünün (@thm-tte-konservatif-test) varsayımı sağlanmadığından sonucu da beklenemez. [$\blacksquare$]{.qed}
:::
::::

## Potansiyel Fonksiyonun Bulunması

Ölçüt alanın konservatif olduğunu söyler ama potansiyel fonksiyonu vermez. $f$'yi **kısmi integrasyon** denilen yöntemle buluruz: bir değişkene göre integral alırken integral sabitinin yerine öteki değişkenlerin bir fonksiyonunu koyarız.

::: {.callout-tip title="Potansiyel fonksiyon dört adımda"}
1. Alanın konservatif olduğunu denetle: düzlemde @thm-tte-konservatif-test ölçütüyle, uzayda @thm-rot-konservatif ile.
2. $f_x = P$ eşitliğini $x$'e göre integre et; integral sabiti yerine $g(y)$ (uzayda $g(y, z)$) yaz.
3. Bulduğun $f$'nin $y$'ye göre türevini $Q$'ya eşitle ve $g$'nin türevini bul; bu türev $x$ içermemelidir. İntegre et. Uzayda aynı işi $z$ ve $R$ için tekrarla.
4. Sonucun gradyanını alıp $\mathbf{F}$'yi verdiğini kontrol et.
:::

:::: {#exm-tte-potansiyel name="Düzlemde Potansiyel Fonksiyon"}
$$\mathbf{F}(x, y) = (3 + 2xy)\,\mathbf{i} + (x^2 - 3y^2)\,\mathbf{j}$$

alanı için $\nabla f = \mathbf{F}$ olan bir $f$ fonksiyonu bulunuz.

::: {.cozum}
Bu alanın konservatif olduğunu gördük (@exm-tte-konservatif). Aradığımız $f$ fonksiyonu

$$f_x(x, y) = 3 + 2xy \tag{2}$$

$$f_y(x, y) = x^2 - 3y^2 \tag{3}$$

eşitliklerini sağlar. (2) eşitliğini $x$'e göre integre edelim. Bu integralde $y$ sabit sayıldığından integral sabiti $y$'nin bir fonksiyonu olabilir; ona $g(y)$ diyelim:

$$f(x, y) = 3x + x^2 y + g(y) \tag{4}$$

(4) eşitliğinin $y$'ye göre türevi $f_y(x, y) = x^2 + g'(y)$'dir. Bunu (3) ile karşılaştırırsak

$$x^2 + g'(y) = x^2 - 3y^2, \qquad g'(y) = -3y^2$$

bulunur. $y$'ye göre integral alarak $g(y) = -y^3 + K$ elde ederiz; $K$ bir sabittir. Bunu (4)'te yerine koyarsak

$$f(x, y) = 3x + x^2 y - y^3 + K$$

potansiyel fonksiyonu bulunur. Kontrol: $f_x = 3 + 2xy$ ve $f_y = x^2 - 3y^2$.

Konservatiflik ölçütünün ispatındaki formül de aynı sonucu verir: $(a, b) = (0, 0)$ için

$$\int_0^x 3\,dt + \int_0^y (x^2 - 3s^2)\,ds = 3x + x^2 y - y^3.$$

[$\blacksquare$]{.qed}
:::
::::

Potansiyel fonksiyon elimizdeyse eğrisel integral birkaç satırda biter.

::: {.callout-tip title="Temel teoremle eğrisel integral üç adımda"}
1. Alanın $C$'yi içeren bir $D$ bölgesinde konservatif olduğunu göster ve bir potansiyel fonksiyon $f$ bul.
2. Eğrinin başlangıç noktası $A = \mathbf{r}(a)$ ile bitiş noktası $B = \mathbf{r}(b)$'yi hesapla.
3. $\int_C \mathbf{F} \cdot d\mathbf{r} = f(B) - f(A)$ yaz. Ya da integral $D$'de yoldan bağımsız olduğundan $C$ yerine $A$'dan $B$'ye giden ve $D$'den çıkmayan daha basit bir yol, örneğin $D$ içinde kalıyorsa doğru parçası kullan.
:::

:::: {#exm-tte-ustel-egri name="Temel Teoremle Bir Eğrisel İntegral"}
$$\mathbf{F}(x, y) = (3 + 2xy)\,\mathbf{i} + (x^2 - 3y^2)\,\mathbf{j}$$

ve $C$,

$$\mathbf{r}(t) = e^t \sin t\,\mathbf{i} + e^t \cos t\,\mathbf{j}, \qquad 0 \le t \le \pi$$

eğrisi olsun. $\int_C \mathbf{F} \cdot d\mathbf{r}$ integralini hesaplayınız.

```{=html}
<figure class="ders-grafik ders-grafik-dar">
<svg viewBox="42.0 12.0 336.0 396.0" role="img" aria-label="The curve e^t (sin t, cos t) for t from 0 to pi, starting at (0, 1), bulging to the right up to x about 7.5 and ending at (0, -e^pi), together with the vertical segment C1 on the y axis between the same two points">
  <g stroke="var(--academic-text)" stroke-width="1.1" opacity="0.5" fill="var(--academic-text)">
  <line x1="56.0" y1="73.4" x2="364.0" y2="73.4"/>
  <line x1="132.7" y1="394.0" x2="132.7" y2="26.0"/>
  <polygon points="364.0,73.4 356.0,69.9 356.0,76.9" stroke="none"/>
  <polygon points="132.7,26.0 129.2,34.0 136.2,34.0" stroke="none"/>
  </g>
  <g fill="var(--academic-text)" font-size="11" opacity="0.7">
  </g>
  <g fill="var(--academic-text)" font-size="11.5" font-style="italic" opacity="0.85">
  <text x="362.0" y="88.4" text-anchor="end"><tspan font-style="italic">x</tspan></text>
  <text x="139.7" y="35.0"><tspan font-style="italic">y</tspan></text>
  </g>
  <line x1="246.4" y1="70.4" x2="246.4" y2="76.4" stroke="var(--academic-text)" stroke-width="1" opacity="0.7"/>
  <text x="242.4" y="88.4" fill="var(--academic-text)" font-size="10.5" text-anchor="middle">5</text>
  <line x1="129.7" y1="197.6" x2="135.7" y2="197.6" stroke="var(--academic-text)" stroke-width="1" opacity="0.7"/>
  <text x="125.7" y="201.6" fill="var(--academic-text)" font-size="10.5" text-anchor="end">&#8722;10</text>
  <line x1="129.7" y1="321.7" x2="135.7" y2="321.7" stroke="var(--academic-text)" stroke-width="1" opacity="0.7"/>
  <text x="125.7" y="325.7" fill="var(--academic-text)" font-size="10.5" text-anchor="end">&#8722;20</text>
  <path d="M132.7,61.0 L133.0,60.9 L133.2,60.8 L133.5,60.6 L133.7,60.5 L134.0,60.4 L134.2,60.3 L134.5,60.1 L134.8,60.0 L135.1,59.9 L135.4,59.7 L135.7,59.6 L136.0,59.5 L136.3,59.4 L136.6,59.2 L136.9,59.1 L137.2,59.0 L137.5,58.9 L137.9,58.7 L138.2,58.6 L138.6,58.5 L138.9,58.4 L139.3,58.2 L139.6,58.1 L140.0,58.0 L140.4,57.9 L140.8,57.8 L141.1,57.6 L141.5,57.5 L141.9,57.4 L142.3,57.3 L142.8,57.2 L143.2,57.1 L143.6,56.9 L144.0,56.8 L144.5,56.7 L144.9,56.6 L145.4,56.5 L145.8,56.4 L146.3,56.3 L146.8,56.2 L147.3,56.1 L147.7,56.0 L148.2,55.9 L148.7,55.8 L149.3,55.7 L149.8,55.6 L150.3,55.6 L150.8,55.5 L151.4,55.4 L151.9,55.3 L152.5,55.2 L153.0,55.1 L153.6,55.1 L154.2,55.0 L154.7,54.9 L155.3,54.9 L155.9,54.8 L156.5,54.7 L157.1,54.7 L157.8,54.6 L158.4,54.6 L159.0,54.5 L159.7,54.5 L160.3,54.4 L161.0,54.4 L161.6,54.4 L162.3,54.3 L163.0,54.3 L163.7,54.3 L164.4,54.2 L165.1,54.2 L165.8,54.2 L166.5,54.2 L167.2,54.2 L168.0,54.2 L168.7,54.2 L169.5,54.2 L170.2,54.2 L171.0,54.2 L171.8,54.3 L172.5,54.3 L173.3,54.3 L174.1,54.3 L174.9,54.4 L175.7,54.4 L176.6,54.5 L177.4,54.5 L178.2,54.6 L179.1,54.7 L179.9,54.7 L180.8,54.8 L181.6,54.9 L182.5,55.0 L183.4,55.1 L184.3,55.2 L185.2,55.3 L186.1,55.4 L187.0,55.5 L187.9,55.6 L188.8,55.8 L189.7,55.9 L190.7,56.0 L191.6,56.2 L192.6,56.4 L193.5,56.5 L194.5,56.7 L195.5,56.9 L196.4,57.1 L197.4,57.3 L198.4,57.5 L199.4,57.7 L200.4,57.9 L201.4,58.1 L202.5,58.4 L203.5,58.6 L204.5,58.9 L205.5,59.1 L206.6,59.4 L207.6,59.7 L208.7,60.0 L209.7,60.3 L210.8,60.6 L211.9,60.9 L212.9,61.2 L214.0,61.6 L215.1,61.9 L216.2,62.3 L217.3,62.6 L218.4,63.0 L219.5,63.4 L220.6,63.8 L221.7,64.2 L222.8,64.6 L223.9,65.0 L225.0,65.5 L226.1,65.9 L227.3,66.4 L228.4,66.8 L229.5,67.3 L230.6,67.8 L231.8,68.3 L232.9,68.9 L234.1,69.4 L235.2,69.9 L236.3,70.5 L237.5,71.1 L238.6,71.6 L239.8,72.2 L240.9,72.8 L242.1,73.4 L243.2,74.1 L244.3,74.7 L245.5,75.4 L246.6,76.1 L247.8,76.7 L248.9,77.4 L250.1,78.2 L251.2,78.9 L252.3,79.6 L253.5,80.4 L254.6,81.1 L255.7,81.9 L256.8,82.7 L258.0,83.5 L259.1,84.4 L260.2,85.2 L261.3,86.1 L262.4,87.0 L263.5,87.9 L264.6,88.8 L265.7,89.7 L266.7,90.6 L267.8,91.6 L268.9,92.5 L269.9,93.5 L271.0,94.5 L272.0,95.6 L273.1,96.6 L274.1,97.6 L275.1,98.7 L276.1,99.8 L277.1,100.9 L278.1,102.0 L279.0,103.2 L280.0,104.3 L280.9,105.5 L281.9,106.7 L282.8,107.9 L283.7,109.1 L284.6,110.4 L285.4,111.6 L286.3,112.9 L287.1,114.2 L288.0,115.5 L288.8,116.9 L289.6,118.2 L290.3,119.6 L291.1,121.0 L291.8,122.4 L292.6,123.9 L293.3,125.3 L293.9,126.8 L294.6,128.3 L295.2,129.8 L295.8,131.3 L296.4,132.9 L297.0,134.4 L297.5,136.0 L298.0,137.6 L298.5,139.2 L299.0,140.9 L299.4,142.6 L299.8,144.2 L300.2,146.0 L300.6,147.7 L300.9,149.4 L301.2,151.2 L301.4,153.0 L301.6,154.8 L301.8,156.6 L302.0,158.5 L302.1,160.3 L302.2,162.2 L302.3,164.1 L302.3,166.1 L302.3,168.0 L302.2,170.0 L302.1,172.0 L302.0,174.0 L301.8,176.0 L301.6,178.1 L301.3,180.1 L301.0,182.2 L300.7,184.3 L300.3,186.5 L299.9,188.6 L299.4,190.8 L298.8,193.0 L298.3,195.2 L297.6,197.4 L297.0,199.7 L296.2,202.0 L295.5,204.2 L294.6,206.6 L293.8,208.9 L292.8,211.2 L291.8,213.6 L290.8,216.0 L289.7,218.4 L288.5,220.8 L287.3,223.3 L286.0,225.7 L284.6,228.2 L283.2,230.7 L281.8,233.2 L280.2,235.8 L278.6,238.3 L277.0,240.9 L275.2,243.5 L273.4,246.1 L271.6,248.7 L269.6,251.3 L267.6,254.0 L265.5,256.7 L263.4,259.3 L261.1,262.0 L258.8,264.8 L256.4,267.5 L254.0,270.2 L251.4,273.0 L248.8,275.8 L246.1,278.6 L243.3,281.4 L240.4,284.2 L237.5,287.0 L234.5,289.9 L231.3,292.7 L228.1,295.6 L224.8,298.5 L221.4,301.3 L217.9,304.2 L214.3,307.1 L210.7,310.1 L206.9,313.0 L203.0,315.9 L199.1,318.9 L195.0,321.8 L190.9,324.8 L186.6,327.8 L182.2,330.7 L177.8,333.7 L173.2,336.7 L168.5,339.7 L163.7,342.7 L158.8,345.7 L153.8,348.7 L148.7,351.7 L143.5,354.7 L138.2,357.7 L132.7,360.7" fill="none" stroke="var(--color-practice)" stroke-width="2.2" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="302.3" y1="168.0" x2="302.2" y2="168.8" stroke="var(--color-practice)" stroke-width="2.2" opacity="1.0" stroke-linecap="round"/>
  <polygon points="301.8,176.0 298.5,166.8 306.1,167.2" fill="var(--color-practice)" opacity="1.0"/>
  <path d="M132.7,61.0 L132.7,360.7" fill="none" stroke="var(--color-base)" stroke-width="2.6" opacity="1.0" stroke-linejoin="round" stroke-linecap="round"/>
  <line x1="132.7" y1="185.2" x2="132.7" y2="209.0" stroke="var(--color-base)" stroke-width="2.6" opacity="1.0" stroke-linecap="round"/>
  <polygon points="132.7,216.2 128.9,207.2 136.5,207.2" fill="var(--color-base)" opacity="1.0"/>
  <circle cx="132.7" cy="61.0" r="4.0" fill="var(--academic-text)"/>
  <circle cx="132.7" cy="360.7" r="4.0" fill="var(--academic-text)"/>
  <rect x="87.7" y="44.8" width="39.5" height="14.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="124.7" y="55.0" fill="var(--academic-text)" font-size="11.5" text-anchor="end">(0, 1)</text>
  <rect x="77.7" y="355.5" width="49.5" height="14.5" rx="3" fill="var(--academic-bg)" opacity="0.88"/>
  <text x="124.7" y="365.7" fill="var(--academic-text)" font-size="11.5" text-anchor="end">(0, &#8722;<tspan font-style="italic">e</tspan><tspan font-size="8.5" dy="-5"><tspan font-style="italic">π</tspan></tspan><tspan dy="5">&#8203;</tspan>)</text>
  <text x="295.4" y="115.6" fill="var(--color-practice)" font-size="14" text-anchor="start" font-weight="600"><tspan font-style="italic">C</tspan></text>
  <text x="123.7" y="139.5" fill="var(--color-base)" font-size="14" text-anchor="end" font-weight="600"><tspan font-style="italic">C</tspan><tspan font-size="8.5" dy="3.5">1</tspan><tspan dy="-3.5">&#8203;</tspan></text>
</svg>
<figcaption><em>C</em> eğrisi <strong>r</strong>(<em>t</em>) = <em>e<sup>t</sup></em> sin <em>t</em> <strong>i</strong> + <em>e<sup>t</sup></em> cos <em>t</em> <strong>j</strong>, 0 ≤ <em>t</em> ≤ <em>π</em>, (0, 1) noktasından sağa doğru açılıp (0, &#8722;<em>e<sup>π</sup></em>) ≈ (0; &#8722;23,1) noktasına iner. <em>C</em><sub>1</sub>, aynı iki noktayı birleştiren düşey doğru parçasıdır. Eksenlerdeki ölçekler farklıdır.</figcaption>
</figure>
```

::: {.cozum}
Tanımdan hesap uzun olurdu: $\mathbf{F}(\mathbf{r}(t)) \cdot \mathbf{r}'(t)$ ifadesinde $e^{3t}$ ile sinüs ve kosinüs kuvvetlerinin çarpımları belirir. Alan konservatif olduğundan iki kısa yol vardır.

**Birinci yol: temel teorem.** Bir önceki örnekte (@exm-tte-potansiyel) bulduğumuz potansiyeli $K = 0$ alarak kullanalım: $f(x, y) = 3x + x^2 y - y^3$. Uç noktalar

$$\mathbf{r}(0) = (0,\ 1), \qquad \mathbf{r}(\pi) = (e^{\pi} \sin \pi,\ e^{\pi} \cos \pi) = (0,\ -e^{\pi})$$

olur. $f(0, -e^{\pi}) = -(-e^{\pi})^3 = e^{3\pi}$ ve $f(0, 1) = -1$ olduğundan @thm-tte-temel-teorem gereği

$$\int_C \mathbf{F} \cdot d\mathbf{r} = f(0, -e^{\pi}) - f(0, 1) = e^{3\pi} - (-1) = e^{3\pi} + 1$$

bulunur.

**İkinci yol: daha basit bir yol.** İntegral yoldan bağımsız olduğundan $C$ yerine $(0, 1)$'den $(0, -e^{\pi})$'ye giden $C_1$ doğru parçasını kullanabiliriz. $C_1$, $y$ ekseni üzerinde aşağı doğru iner ve

$$\mathbf{r}(t) = -t\,\mathbf{j}, \qquad -1 \le t \le e^{\pi}$$

diye yazılır: $t = -1$'de $(0, 1)$, $t = e^{\pi}$'de $(0, -e^{\pi})$ noktasındayız. Bu yol üzerinde $x = 0$ ve $y = -t$ olduğundan $\mathbf{F}(\mathbf{r}(t)) = 3\,\mathbf{i} - 3t^2\,\mathbf{j}$ ve $\mathbf{r}'(t) = -\mathbf{j}$'dir. Buradan

$$
\begin{aligned}
\int_C \mathbf{F} \cdot d\mathbf{r} &= \int_{C_1} \mathbf{F} \cdot d\mathbf{r} = \int_{-1}^{e^{\pi}} (3\,\mathbf{i} - 3t^2\,\mathbf{j}) \cdot (-\mathbf{j})\,dt \\[1mm]
&= \int_{-1}^{e^{\pi}} 3t^2\,dt = \Big[ t^3 \Big]_{-1}^{e^{\pi}} = e^{3\pi} + 1
\end{aligned}
$$

bulunur. İki yol aynı sonucu verir. [$\blacksquare$]{.qed}
:::
::::

Uzaydaki alanlar için konservatiflik ölçütünü [Rotasyonel ve Diverjans](rotasyonel-ve-diverjans.qmd) bölümünde kuracağız (@thm-rot-konservatif). Potansiyel fonksiyonu bulma yöntemi ise uzayda da aynen işler.

:::: {#exm-tte-potansiyel-uzay name="Uzayda Potansiyel Fonksiyon"}
$$\mathbf{F}(x, y, z) = y^2\,\mathbf{i} + (2xy + e^{3z})\,\mathbf{j} + 3y e^{3z}\,\mathbf{k}$$

alanı için $\nabla f = \mathbf{F}$ olan bir $f$ fonksiyonu bulunuz.

::: {.cozum}
Böyle bir $f$ varsa

$$f_x(x, y, z) = y^2 \tag{5}$$

$$f_y(x, y, z) = 2xy + e^{3z} \tag{6}$$

$$f_z(x, y, z) = 3y e^{3z} \tag{7}$$

olmalıdır. (5) eşitliğini $x$'e göre integre edelim. Bu kez integral sabiti $x$'e göre sabittir, yani $y$ ile $z$'nin bir fonksiyonudur:

$$f(x, y, z) = xy^2 + g(y, z) \tag{8}$$

(8) eşitliğinin $y$'ye göre türevini (6) ile karşılaştıralım:

$$2xy + g_y(y, z) = 2xy + e^{3z}, \qquad g_y(y, z) = e^{3z}.$$

Bunu $y$'ye göre integre edersek $g(y, z) = y e^{3z} + h(z)$ bulunur ve (8) eşitliği

$$f(x, y, z) = xy^2 + y e^{3z} + h(z)$$

biçimini alır. Son olarak $z$'ye göre türevi (7) ile karşılaştıralım: $3y e^{3z} + h'(z) = 3y e^{3z}$, yani $h'(z) = 0$ ve $h(z) = K$ sabittir. Aranan fonksiyon

$$f(x, y, z) = xy^2 + y e^{3z} + K$$

olur. Kontrol: $\nabla f = \langle y^2,\ 2xy + e^{3z},\ 3y e^{3z} \rangle = \mathbf{F}$. [$\blacksquare$]{.qed}
:::
::::

## Enerjinin Korunumu

Bu bölümün fikirlerini fizikteki kuvvet alanlarına uygulayalım; "konservatif" adının nereden geldiği de böylece ortaya çıkacak.

Sürekli bir $\mathbf{F}$ kuvvet alanı, $m$ kütleli bir cismi $\mathbf{r}(t)$, $a \le t \le b$ ile verilen bir $C$ yolu boyunca hareket ettirsin. $\mathbf{r}$ iki kez türevlenebilir ve $\mathbf{r}''$ sürekli olsun; ayrıca cisim hiç durmasın, yani her $t$ için $\mathbf{r}'(t) \ne \mathbf{0}$ olsun. Böylece $C$ düzgün bir eğridir. Başlangıç noktası $A = \mathbf{r}(a)$, bitiş noktası $B = \mathbf{r}(b)$'dir. Cismin hızı $\mathbf{v}(t) = \mathbf{r}'(t)$, ivmesi $\mathbf{r}''(t)$'dir ve Newton'un ikinci hareket yasası

$$\mathbf{F}(\mathbf{r}(t)) = m\,\mathbf{r}''(t)$$

der. Cismin durmaması koşulu yalnız $C$'nin düzgün olması, yani $\int_C$ gösteriminin [Eğrisel İntegraller](egrisel-integraller.qmd) bölümündeki tanıma uyması içindir; ne temel teoremin ne de aşağıdaki ispatların hesapları onu kullanır. Bu yüzden iş $\int_a^b \mathbf{F}(\mathbf{r}(t)) \cdot \mathbf{r}'(t)\,dt$ integraliyle tanımlandığında sonuçlar, düşey olarak yukarı atılıp tepede bir an durduktan sonra geri düşen bir top gibi cisimler için de geçerlidir.

::: {#def-tte-kinetik-enerji name="Kinetik Enerji"}
$m$ kütleli ve $\mathbf{v}(t)$ hızıyla hareket eden bir cismin $t$ anındaki **kinetik enerjisi**

$$K = \frac{1}{2} m\,|\mathbf{v}(t)|^2$$

sayısıdır. Cisim bir $A$ noktasındayken kinetik enerjisini $K(A)$ ile gösteririz.
:::

Yani kinetik enerji, kütle ile süratin karesinin çarpımının yarısıdır; cisim hızlandıkça artar, yavaşladıkça azalır.

:::: {#thm-tte-is-enerji name="İş ve Kinetik Enerji"}
Yukarıdaki koşullarda $\mathbf{F}$ kuvvet alanının $C$ yolu boyunca yaptığı iş, cismin kinetik enerjisindeki değişime eşittir:

$$W = \int_C \mathbf{F} \cdot d\mathbf{r} = K(B) - K(A).$$

::: {.ispat}
İç çarpımın türevi için çarpım kuralı

$$\frac{d}{dt} \big[ \mathbf{r}'(t) \cdot \mathbf{r}'(t) \big] = \mathbf{r}''(t) \cdot \mathbf{r}'(t) + \mathbf{r}'(t) \cdot \mathbf{r}''(t) = 2\,\mathbf{r}''(t) \cdot \mathbf{r}'(t)$$

verir. Newton yasasını eğrisel integralin tanımına koyup bu eşitliği kullanalım:

$$
\begin{aligned}
W &= \int_a^b \mathbf{F}(\mathbf{r}(t)) \cdot \mathbf{r}'(t)\,dt = \int_a^b m\,\mathbf{r}''(t) \cdot \mathbf{r}'(t)\,dt \\[1mm]
&= \frac{m}{2} \int_a^b \frac{d}{dt} \big[ \mathbf{r}'(t) \cdot \mathbf{r}'(t) \big]\,dt = \frac{m}{2} \int_a^b \frac{d}{dt} |\mathbf{r}'(t)|^2\,dt.
\end{aligned}
$$

Türevi sürekli olan $|\mathbf{r}'(t)|^2$ fonksiyonuna (1) eşitliğini uygularsak

$$
\begin{aligned}
W &= \frac{m}{2} \big( |\mathbf{r}'(b)|^2 - |\mathbf{r}'(a)|^2 \big) \\[1mm]
&= \frac{1}{2} m\,|\mathbf{v}(b)|^2 - \frac{1}{2} m\,|\mathbf{v}(a)|^2 = K(B) - K(A)
\end{aligned}
$$

bulunur. [$\blacksquare$]{.qed}
:::
::::

Yani kuvvetin yaptığı iş cismin hızlanmasına harcanır. Kuvvet alanı konservatifse işi bir de potansiyel fonksiyon cinsinden yazabiliriz.

::: {#def-tte-potansiyel-enerji name="Potansiyel Enerji"}
$\mathbf{F} = \nabla f$ konservatif bir kuvvet alanı olsun. Bir cismin $(x, y, z)$ noktasındaki **potansiyel enerjisi**

$$V(x, y, z) = -f(x, y, z)$$

ile tanımlanır. Böylece $\mathbf{F} = -\nabla V$ olur.
:::

Yani potansiyel enerji, potansiyel fonksiyonun ters işaretlisidir; kuvvet, potansiyel enerjinin en hızlı azaldığı yönü gösterir. Kütle çekim alanında cisim yere yaklaştıkça potansiyel enerjisi azalır.

:::: {#thm-tte-enerjinin-korunumu name="Enerjinin Korunumu Yasası"}
Yukarıdaki koşullarda bir cisim konservatif bir $\mathbf{F}$ kuvvet alanının etkisiyle $A$ noktasından $B$ noktasına hareket ederse potansiyel ve kinetik enerjilerinin toplamı değişmez:

$$V(A) + K(A) = V(B) + K(B).$$

::: {.ispat}
$\mathbf{F} = -\nabla V$ olduğundan @thm-tte-temel-teorem, $V$ fonksiyonuna uygulanınca

$$W = \int_C \mathbf{F} \cdot d\mathbf{r} = -\int_C \nabla V \cdot d\mathbf{r} = -\big( V(B) - V(A) \big) = V(A) - V(B)$$

verir. @thm-tte-is-enerji gereği aynı iş $K(B) - K(A)$'ya eşittir. İki ifadeyi eşitlersek $V(A) - V(B) = K(B) - K(A)$, yani $V(A) + K(A) = V(B) + K(B)$ bulunur. [$\blacksquare$]{.qed}
:::
::::

Yani konservatif bir kuvvet alanında hareket eden cisim potansiyel enerjiyi kinetik enerjiye ya da kinetik enerjiyi potansiyel enerjiye dönüştürür, ama toplam enerji korunur. Bu vektör alanlarına "konservatif" (korunumlu) denmesinin nedeni budur.

## Alıştırmalar

Aşağıdaki alıştırmalar bölümün yöntemlerini kolaydan zora dolaşıyor.

:::: {#exr-tte-tablo name="Değer Tablosundan Eğrisel İntegral"}
Gradyanı sürekli olan bir $f$ fonksiyonunun bazı değerleri aşağıdaki tabloda verilmiştir. $C$, $x = t^2 + 1$, $y = t^3 + t$, $0 \le t \le 1$ parametrik denklemleriyle verilen eğri olduğuna göre $\int_C \nabla f \cdot d\mathbf{r}$ integralini bulunuz.

| $f(x, y)$ | $y = 0$ | $y = 1$ | $y = 2$ |
|:---:|:---:|:---:|:---:|
| $x = 0$ | $1$ | $6$ | $4$ |
| $x = 1$ | $3$ | $5$ | $7$ |
| $x = 2$ | $8$ | $2$ | $9$ |

::: {.cozum}
**Eğrinin düzgünlüğü.** $\mathbf{r}'(t) = \langle 2t,\ 3t^2 + 1 \rangle$ süreklidir ve ikinci bileşeni en az $1$ olduğundan hiç sıfır olmaz; $C$ düzgündür.

**Uç noktalar.** $t = 0$ için $(x, y) = (1, 0)$, $t = 1$ için $(x, y) = (2, 2)$'dir.

**Sonuç.** @thm-tte-temel-teorem gereği

$$\int_C \nabla f \cdot d\mathbf{r} = f(2, 2) - f(1, 0) = 9 - 3 = 6$$

olur. Tablonun öteki değerlerine ve eğrinin biçimine hiç gerek kalmadı. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-tte-ustel-alan name="Üstel Çarpanlı Bir Alanın Potansiyeli"}
$\mathbf{F}(x, y) = y^2 e^{xy}\,\mathbf{i} + (1 + xy) e^{xy}\,\mathbf{j}$ alanının konservatif olup olmadığını belirleyiniz; konservatifse $\nabla f = \mathbf{F}$ olan bir $f$ bulunuz.

::: {.cozum}
**Ölçüt.** Çarpım kuralıyla

$$
\begin{aligned}
\frac{\partial P}{\partial y} &= 2y e^{xy} + xy^2 e^{xy} = y(2 + xy) e^{xy}, \\[1mm]
\frac{\partial Q}{\partial x} &= y e^{xy} + (1 + xy) y e^{xy} = y(2 + xy) e^{xy}
\end{aligned}
$$

bulunur. İki türev eşit ve her yerde süreklidir; tanım kümesi olan düzlem açık ve basit bağlantılıdır. @thm-tte-konservatif-test gereği $\mathbf{F}$ konservatiftir.

**Potansiyel.** $f_x = y^2 e^{xy}$ eşitliğini $x$'e göre integre edelim; $y$ sabit sayıldığından $\int y^2 e^{xy}\,dx = y e^{xy}$ olur:

$$f(x, y) = y e^{xy} + g(y).$$

$y$'ye göre türev

$$f_y = e^{xy} + xy e^{xy} + g'(y) = (1 + xy) e^{xy} + g'(y)$$

olur. Bunu $Q = (1 + xy) e^{xy}$'ye eşitlersek $g'(y) = 0$, yani $g(y) = K$ bulunur. Sonuç olarak

$$f(x, y) = y e^{xy} + K$$

olur. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-tte-uzay-egrisi name="Gradyanın Bir Uzay Eğrisi Boyunca İntegrali"}
$f(x, y, z) = xy^2 z + x^2$ ve $C$,

$$x = t^2, \qquad y = e^{t^2 - 1}, \qquad z = t^2 + t, \qquad -1 \le t \le 1$$

eğrisi olduğuna göre $\int_C \nabla f \cdot d\mathbf{r}$ integralini hesaplayınız.

::: {.cozum}
**Varsayımlar.** $\nabla f = \langle y^2 z + 2x,\ 2xyz,\ xy^2 \rangle$ her yerde süreklidir. $\mathbf{r}'(t) = \langle 2t,\ 2t e^{t^2 - 1},\ 2t + 1 \rangle$ süreklidir ve sıfır olamaz: ilk bileşen yalnız $t = 0$'da sıfırdır, orada üçüncü bileşen $1$'dir. $C$ düzgündür.

**Uç noktalar.** $t = -1$ için $(1, e^0, 1 - 1) = (1, 1, 0)$, $t = 1$ için $(1, e^0, 1 + 1) = (1, 1, 2)$ noktası bulunur.

**Sonuç.** $f(1, 1, 2) = 1 \cdot 1 \cdot 2 + 1 = 3$ ve $f(1, 1, 0) = 0 + 1 = 1$ olduğundan

$$\int_C \nabla f \cdot d\mathbf{r} = f(1, 1, 2) - f(1, 1, 0) = 3 - 1 = 2$$

olur. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-tte-hiperbol name="Hiperbol Yayı Boyunca İntegral"}
$\mathbf{F}(x, y) = (3 + 2xy^2)\,\mathbf{i} + 2x^2 y\,\mathbf{j}$ ve $C$, $y = 1/x$ hiperbolünün $(1, 1)$ noktasından $(4, \tfrac{1}{4})$ noktasına giden yayı olsun. Bir potansiyel fonksiyon bularak $\int_C \mathbf{F} \cdot d\mathbf{r}$ integralini hesaplayınız.

::: {.cozum}
**Ölçüt.** $P_y = 4xy = Q_x$ ve kısmi türevler düzlemde süreklidir; @thm-tte-konservatif-test gereği $\mathbf{F}$ konservatiftir.

**Potansiyel.** $f_x = 3 + 2xy^2$ eşitliğini $x$'e göre integre edersek $f = 3x + x^2 y^2 + g(y)$ bulunur. $f_y = 2x^2 y + g'(y)$ ifadesini $Q = 2x^2 y$'ye eşitlersek $g'(y) = 0$ olur; $K = 0$ alarak

$$f(x, y) = 3x + x^2 y^2$$

seçebiliriz.

**İntegral.** @thm-tte-temel-teorem gereği

$$
\begin{aligned}
\int_C \mathbf{F} \cdot d\mathbf{r} &= f\big(4, \tfrac{1}{4}\big) - f(1, 1) = \Big( 12 + 16 \cdot \tfrac{1}{16} \Big) - (3 + 1) \\[1mm]
&= 13 - 4 = 9
\end{aligned}
$$

olur. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-tte-uc-boyut name="Üç Boyutta Potansiyel ve Eğrisel İntegral"}
$$\mathbf{F}(x, y, z) = \sin y\,\mathbf{i} + (x \cos y + \cos z)\,\mathbf{j} - y \sin z\,\mathbf{k}$$

ve $C$,

$$\mathbf{r}(t) = \sin t\,\mathbf{i} + t\,\mathbf{j} + 2t\,\mathbf{k}, \qquad 0 \le t \le \pi/2$$

eğrisi olsun. $\nabla f = \mathbf{F}$ olan bir $f$ bularak $\int_C \mathbf{F} \cdot d\mathbf{r}$ integralini hesaplayınız.

::: {.cozum}
**Potansiyel.** $f_x = \sin y$ eşitliğini $x$'e göre integre edersek

$$f(x, y, z) = x \sin y + g(y, z)$$

bulunur. $f_y = x \cos y + g_y$ ifadesini $x \cos y + \cos z$'ye eşitlersek $g_y = \cos z$ olur; $y$'ye göre integralle $g(y, z) = y \cos z + h(z)$ bulunur. Böylece $f = x \sin y + y \cos z + h(z)$'dir. $f_z = -y \sin z + h'(z)$ ifadesini $-y \sin z$'ye eşitlersek $h'(z) = 0$ çıkar. $h = 0$ alarak

$$f(x, y, z) = x \sin y + y \cos z$$

seçelim. Kontrol:

$$\nabla f = \langle \sin y,\ x \cos y + \cos z,\ -y \sin z \rangle = \mathbf{F}.$$

**Uç noktalar.** $\mathbf{r}(0) = (0, 0, 0)$ ve $\mathbf{r}(\pi/2) = (1, \pi/2, \pi)$'dir.

**İntegral.** $f(0, 0, 0) = 0$ olduğundan

$$
\begin{aligned}
\int_C \mathbf{F} \cdot d\mathbf{r} &= f\big(1, \tfrac{\pi}{2}, \pi\big) - f(0, 0, 0) \\[1mm]
&= 1 \cdot \sin \tfrac{\pi}{2} + \tfrac{\pi}{2} \cos \pi - 0 = 1 - \frac{\pi}{2}
\end{aligned}
$$

bulunur. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-tte-yoldan-bagimsiz name="Yoldan Bağımsızlığın Gösterilmesi"}
$$\int_C 2x e^{-y}\,dx + (2y - x^2 e^{-y})\,dy$$

integralinin yoldan bağımsız olduğunu gösteriniz ve $C$, $(1, 0)$ noktasından $(2, 1)$ noktasına giden herhangi bir yol olduğunda değerini bulunuz.

::: {.cozum}
**Yoldan bağımsızlık.** İntegral, $\mathbf{F} = P\,\mathbf{i} + Q\,\mathbf{j}$ alanının eğrisel integralidir; burada $P = 2x e^{-y}$ ve $Q = 2y - x^2 e^{-y}$'dir.

$$\frac{\partial P}{\partial y} = -2x e^{-y} = \frac{\partial Q}{\partial x}$$

olur ve kısmi türevler bütün düzlemde süreklidir. @thm-tte-konservatif-test gereği $\mathbf{F}$ konservatiftir, @cor-tte-gradyan-yoldan-bagimsiz gereği de integral yoldan bağımsızdır.

**Potansiyel.** $f_x = 2x e^{-y}$ eşitliğinden $f = x^2 e^{-y} + g(y)$ bulunur. $f_y = -x^2 e^{-y} + g'(y)$ ifadesini $Q$'ya eşitlersek $g'(y) = 2y$, yani $g(y) = y^2$ olur ($K = 0$). Böylece

$$f(x, y) = x^2 e^{-y} + y^2.$$

**Değer.** Hangi yol seçilirse seçilsin

$$\int_C \mathbf{F} \cdot d\mathbf{r} = f(2, 1) - f(1, 0) = \big( 4e^{-1} + 1 \big) - (1 + 0) = \frac{4}{e}$$

olur. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-tte-is-deneyi name="İki Farklı İş Ölçümü"}
Bir deneyde, bir $\mathbf{F}$ kuvvet alanının bir parçacığı $(1, 2)$ noktasından $(5, -3)$ noktasına bir $C_1$ eğrisi boyunca götürürken $1{,}2$ J, aynı iki nokta arasındaki başka bir $C_2$ eğrisi boyunca götürürken $1{,}4$ J iş yaptığı ölçülüyor. $\mathbf{F}$ hakkında ne söylenebilir?

::: {.cozum}
$\mathbf{F}$ konservatif olsaydı @cor-tte-gradyan-yoldan-bagimsiz gereği eğrisel integrali yoldan bağımsız olurdu; uç noktaları aynı olan $C_1$ ve $C_2$ boyunca yapılan işler eşit çıkardı. Ölçülen işler farklı olduğundan ($1{,}2 \ne 1{,}4$), $\mathbf{F}$ konservatif değildir.

Aynı sonucu kapalı bir yolla da okuyabiliriz: $C_1$ ile ardından $-C_2$'nin oluşturduğu kapalı yolda yapılan iş

$$\int_{C_1} \mathbf{F} \cdot d\mathbf{r} - \int_{C_2} \mathbf{F} \cdot d\mathbf{r} = 1{,}2 - 1{,}4 = -0{,}2 \ \text{J}$$

olur. Bu sıfırdan farklıdır; @thm-tte-yoldan-bagimsizlik gereği integral yoldan bağımsız olamaz. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-tte-gerekli-kosul-uzay name="Üç Boyutta Gerekli Koşul"}
$\mathbf{F} = P\,\mathbf{i} + Q\,\mathbf{j} + R\,\mathbf{k}$ vektör alanı açık bir kümede konservatif ve $P$, $Q$, $R$'nin birinci mertebeden kısmi türevleri bu kümede sürekli olsun. Bu durumda

$$\frac{\partial P}{\partial y} = \frac{\partial Q}{\partial x}, \qquad \frac{\partial P}{\partial z} = \frac{\partial R}{\partial x}, \qquad \frac{\partial Q}{\partial z} = \frac{\partial R}{\partial y}$$

olduğunu gösteriniz.

::: {.cozum}
$\mathbf{F}$ konservatif olduğundan $\nabla f = \mathbf{F}$ olan bir $f$ vardır: $P = f_x$, $Q = f_y$, $R = f_z$. Buradan

$$
\begin{aligned}
P_y &= f_{xy}, & Q_x &= f_{yx}, \\[1mm]
P_z &= f_{xz}, & R_x &= f_{zx}, \\[1mm]
Q_z &= f_{yz}, & R_y &= f_{zy}
\end{aligned}
$$

olur. Varsayım gereği bu altı karışık türev süreklidir. Clairaut teoreminin çok değişkenli biçimine göre (bkz. [Analiz 4](../analiz-4/yuksek-mertebeden-kismi-turevler.html#cor-yuk-n-degisken)) sürekli karışık türevlerde türev alma sırası önemli değildir: $f_{xy} = f_{yx}$, $f_{xz} = f_{zx}$, $f_{yz} = f_{zy}$. Bu üç eşitlik istenen üç eşitliğin ta kendisidir. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-tte-xyz name="Yoldan Bağımsız Olmayan Bir İntegral"}
Bir önceki alıştırmayı (@exr-tte-gerekli-kosul-uzay) kullanarak

$$\int_C y\,dx + x\,dy + xyz\,dz$$

integralinin yoldan bağımsız olmadığını gösteriniz.

::: {.cozum}
**Gerekli koşul bozuluyor.** İntegral, $\mathbf{F} = y\,\mathbf{i} + x\,\mathbf{j} + xyz\,\mathbf{k}$ alanının eğrisel integralidir: $P = y$, $Q = x$, $R = xyz$. İlk koşul sağlanır ($P_y = 1 = Q_x$), ama

$$\frac{\partial P}{\partial z} = 0, \qquad \frac{\partial R}{\partial x} = yz$$

olduğundan $yz \ne 0$ olan noktalarda, örneğin $(0, 1, 1)$'de ikinci koşul bozulur. Kısmi türevler her yerde sürekli olduğundan @exr-tte-gerekli-kosul-uzay gereği $\mathbf{F}$, $\mathbb{R}^3$'te konservatif değildir.

**Sonuç.** $\mathbb{R}^3$ açık ve bağlantılıdır. İntegral yoldan bağımsız olsaydı, yoldan bağımsız alanların konservatif olduğunu söyleyen teoremin (@thm-tte-konservatif) uzaydaki biçimi $\mathbf{F}$'yi konservatif yapardı. Demek ki integral yoldan bağımsız değildir.

**Somut kontrol.** $(0, 0, 0)$'dan $(1, 1, 1)$'e iki yol deneyelim. Doğru parçası $x = y = z = t$, $0 \le t \le 1$ boyunca

$$\int_0^1 (t + t + t^3)\,dt = 1 + \frac{1}{4} = \frac{5}{4}$$

bulunur. Önce $z$ ekseni boyunca $(0, 0, 1)$'e çıkıp sonra $x = y = t$, $z = 1$ doğru parçasıyla $(1, 1, 1)$'e gidersek, ilk parçada $x = y = 0$ olduğundan integrand sıfırdır; ikinci parçada $dz = 0$'dır ve

$$0 + \int_0^1 (t + t)\,dt = 1$$

bulunur. $5/4 \ne 1$ olduğundan integral gerçekten yoldan bağımsız değildir. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-tte-yarim-halka name="Kapalı Yarım Halka"}
$$D = \{(x, y) \mid 1 \le x^2 + y^2 \le 4,\ y \ge 0\}$$

kümesinin açık, bağlantılı ve basit bağlantılı olup olmadığını belirleyiniz.

::: {.cozum}
**Açık değil.** $(1, 0)$ noktası $D$'dedir. Merkezi $(1, 0)$ olan her disk, $y < 0$ olan noktalar içerir (örneğin yeterince küçük bir $\varepsilon > 0$ için $(1, -\varepsilon)$); bu noktalar $D$'de değildir. Demek ki $(1, 0)$ çevresinde $D$'de kalan bir disk yoktur.

**Bağlantılı.** Kutupsal koordinatlarla $D$, $1 \le r \le 2$ ve $0 \le \theta \le \pi$ koşullarıyla verilir. İki noktası $(r_1, \theta_1)$ ve $(r_2, \theta_2)$ olsun. Birinci noktadan $r = r_1$ yayı boyunca $(r_1, \theta_2)$'ye, oradan $\theta = \theta_2$ ışını boyunca $(r_2, \theta_2)$'ye giden yol $D$'den çıkmaz.

**Basit bağlantılı.** Basit kapalı bir eğri çevrelediği noktaları "hapseder": çevrelenen bir noktadan istediğimiz kadar uzağa giden her yol eğriyi keser. $D$'nin dışındaki her noktadan ise $D$'ye hiç değmeden istediğimiz kadar uzağa gidebiliriz:

- $y < 0$ olan bir noktadan düz aşağı ineriz.
- İç diskte ($x^2 + y^2 < 1$, $y \ge 0$) bulunan bir noktadan da düz aşağı ineriz: $x$ eksenine kadar $|y|$ küçüldüğünden iç diskte kalırız, ekseni geçince $y < 0$ bölgesine gireriz.
- Dış bölgedeki ($x^2 + y^2 > 4$) bir noktadan orijinden uzaklaşan ışın boyunca gideriz.

Bu yollar $D$'ye, dolayısıyla $D$ içindeki bir eğriye değmez. Demek ki $D$ içindeki hiçbir basit kapalı eğri $D$'nin dışında bir nokta çevrelemez ve $D$ basit bağlantılıdır. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-tte-delikli-duzlem name="Bir Noktası Çıkarılmış Düzlem"}
$D = \{(x, y) \mid (x, y) \ne (2, 3)\}$ kümesinin açık, bağlantılı ve basit bağlantılı olup olmadığını belirleyiniz.

::: {.cozum}
**Açık.** $P \in D$ ise $P$ ile $(2, 3)$ arasındaki uzaklık $\delta > 0$'dır. Merkezi $P$, yarıçapı $\delta$ olan disk $(2, 3)$ noktasını içermez, yani tamamen $D$'dedir.

**Bağlantılı.** $D$'nin iki noktasını birleştiren doğru parçası $(2, 3)$'ten geçmiyorsa doğrudan onu kullanırız. Geçiyorsa bu doğrunun dışında bir $Q$ noktası seçip iki noktayı $Q$ üzerinden iki doğru parçasıyla birleştiririz; bu iki parça $(2, 3)$'ten geçmez.

**Basit bağlantılı değil.** Merkezi $(2, 3)$, yarıçapı $1$ olan çember $D$'nin içinde bir basit kapalı eğridir ama $D$'ye ait olmayan $(2, 3)$ noktasını çevreler. [$\blacksquare$]{.qed}
:::
::::

:::: {#exr-tte-ters-kare name="Ters Kare Kuvvet Alanında İş"}
$c$ bir sabit ve $\mathbf{r} = x\,\mathbf{i} + y\,\mathbf{j} + z\,\mathbf{k}$ olmak üzere

$$\mathbf{F}(\mathbf{r}) = \frac{c\,\mathbf{r}}{|\mathbf{r}|^3}$$

alanına **ters kare kuvvet alanı** denir. Bir cismi orijinden geçmeyen bir yol boyunca bir $P_1$ noktasından bir $P_2$ noktasına götürürken $\mathbf{F}$'nin yaptığı işi, bu noktaların orijine uzaklıkları $d_1$ ve $d_2$ cinsinden bulunuz.

::: {.cozum}
**Potansiyel.** $f = -c/|\mathbf{r}|$, yani $f = -c\,(x^2 + y^2 + z^2)^{-1/2}$ alalım. Zincir kuralıyla

$$\frac{\partial f}{\partial x} = -c \cdot \left( -\frac{1}{2} \right) (x^2 + y^2 + z^2)^{-3/2} \cdot 2x = \frac{c\,x}{|\mathbf{r}|^3}$$

bulunur; $y$ ve $z$ için de aynı biçimde $c\,y/|\mathbf{r}|^3$ ve $c\,z/|\mathbf{r}|^3$ çıkar. Demek ki orijin dışında $\nabla f = \mathbf{F}$'dir ve $\nabla f$ orada süreklidir.

**İş.** @cor-tte-parcali-duzgun gereği

$$W = f(P_2) - f(P_1) = -\frac{c}{d_2} + \frac{c}{d_1} = c \left( \frac{1}{d_1} - \frac{1}{d_2} \right)$$

olur. Kütle çekim alanında $c = -mMG$'dir ve sonuç $W = mMG \left( \dfrac{1}{d_2} - \dfrac{1}{d_1} \right)$ olur. $d_1 = 13$, $d_2 = 2\sqrt{2}$ için bu, kütle çekim örneğindeki (@exm-tte-kutle-cekimi) sonuçtur. [$\blacksquare$]{.qed}
:::
::::

Bu bölümde gradyan alanlarının eğrisel integralini uç noktalara indirdik ve düzlemde konservatifliği $\partial P / \partial y = \partial Q / \partial x$ ölçütüyle tanıdık. Ölçütün genel ispatı, kapalı bir eğri boyunca integrali eğrinin çevrelediği bölge üzerindeki bir iki katlı integrale bağlayan bir teoreme dayanıyordu. Bir sonraki bölüm bu teoremi kuruyor: [Green Teoremi](green-teoremi.qmd).
