project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Nümerik Analiz"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Temeller"
      chapters:
        - on-bilgiler-ve-taylor-teoremi.qmd
        - hatalar-ve-makine-sayilari.qmd
        - algoritmalar-ve-yakinsama.qmd

    - part: "Kök Bulma Yöntemleri"
      chapters:
        - ikiye-bolme-metodu.qmd
        - sabit-nokta-iterasyonu.qmd
        - newton-raphson-metodu.qmd
        - secant-ve-regula-falsi.qmd

    - part: "İnterpolasyon"
      chapters:
        - lagrange-interpolasyonu.qmd
        - bolunmus-farklar.qmd

    - part: "Nümerik Türev, İntegral ve Eğri Uydurma"
      chapters:
        - numerik-turev.qmd
        - numerik-integrasyon.qmd
        - en-kucuk-kareler-yontemi.qmd
