project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Lineer Cebir"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Cebirsel Yapılar"
      chapters:
        - cebirsel-yapilar/tek-islemli-yapilar.qmd
        - cebirsel-yapilar/iki-islemli-yapilar.qmd

    - part: "Matrisler"
      chapters:
        - matrisler/matrisler-ve-islemler.qmd
        - matrisler/merdiven-matrisler.qmd
        - matrisler/kare-matrisler-ve-ters.qmd
        - matrisler/elemanter-matrisler.qmd

    - part: "Lineer Denklem Sistemleri"
      chapters:
        - denklem-sistemleri/lineer-denklemler.qmd
        - denklem-sistemleri/esdeger-sistemler.qmd
        - denklem-sistemleri/gauss-yontemi.qmd
        - denklem-sistemleri/parametreli-sistemler.qmd

    - part: "Vektör Uzayları"
      chapters:
        - vektor-uzaylari/vektor-uzaylari.qmd
        - vektor-uzaylari/alt-uzaylar.qmd
        - vektor-uzaylari/toplamlar-ve-direkt-toplam.qmd
        - vektor-uzaylari/lineer-kombinezon.qmd
        - vektor-uzaylari/satir-uzayi.qmd
        - vektor-uzaylari/lineer-bagimsizlik.qmd
        - vektor-uzaylari/taban-ve-boyut.qmd
        - vektor-uzaylari/boyut-teoremleri.qmd
        - vektor-uzaylari/rank.qmd

    - part: "Lineer Tasvirler"
      chapters:
        - lineer-tasvirler/lineer-tasvirler.qmd
        - lineer-tasvirler/koordinatlar-ve-izomorfizm.qmd
        - lineer-tasvirler/cekirdek-ve-goruntu.qmd
