project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Sayılar Teorisi"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "İleri Kongrüanslar ve Kök Taşıma"
      chapters:
        - 2/n-kuvvet-rezidu.qmd

    - part: "Kuadratik (İkinci Dereceden) Rezidüler"
      chapters:
        - 2/rezidu-kavrami.qmd
        - 2/legendre-sembolu.qmd
        - 2/gauss-lemmasi.qmd

    - part: "Kuadratik Resiprosite ve Semboller"
      chapters:
        - 2/kuadratik-resiprosite.qmd
        - 2/jacobi-sembolu.qmd

    - part: "Diofant Denklemleri"
      chapters:
        - 2/dogrusal-diofant.qmd
