project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Sayılar Teorisi"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Yüksek Dereceden Kongrüanslar"
      chapters:
        - 2/kongruans-cozumleri.qmd
        - 2/yuksek-dereceden-kongruanslar.qmd
        - 2/kok-yukseltme.qmd
        - 2/asal-moduller.qmd

    - part: "Mertebe, Primitif Kökler ve Kuvvet Kalanları"
      chapters:
        - 2/mertebe-primitif-kokler.qmd

    - part: "Kuadratik (İkinci Dereceden) Rezidüler"
      chapters:
        - 2/rezidu-kavrami.qmd
        - 2/legendre-sembolu.qmd
        - 2/gauss-lemmasi.qmd

    - part: "Kuadratik Resiprosite ve Semboller"
      chapters:
        - 2/kuadratik-resiprosite.qmd
        - 2/jacobi-sembolu.qmd

    - part: "Diofant Denklemleri"
      chapters:
        - 2/dogrusal-diofant.qmd
