project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Diferansiyel Denklemler"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Temeller ve Birinci Mertebe Denklemler"
      chapters:
        - siniflandirma.qmd
        - cozumler.qmd
        - baslangic-sinir-deger-problemleri.qmd
        - keyfi-sabitlerin-yok-edilmesi.qmd
        - degiskenlerine-ayrilabilen-denklemler.qmd
        - homojen-denklemler.qmd
        - tam-diferansiyel-denklemler.qmd
        - integrasyon-carpani.qmd
