project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Diferansiyel Geometri"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Diferansiyel Geometri 1 — Öklid Uzayında Analiz"
      chapters:
        - 1/oklid-uzayi.qmd
        - 1/teget-vektorler.qmd
        - 1/yonlu-turevler.qmd
        - 1/uzayda-egriler.qmd
        - 1/bir-formlar.qmd
        - 1/diferansiyel-formlar.qmd
        - 1/donusumler.qmd
        - 1/ozet.qmd

    - part: "Diferansiyel Geometri 1 — Çatı Alanları"
      chapters:
        - 1/ic-carpim.qmd
        - 1/egriler-yay-uzunlugu.qmd
        - 1/frenet-formulleri.qmd
        - 1/keyfi-hizli-egriler.qmd
        - 1/kovaryant-turev.qmd
        - 1/cati-alanlari.qmd
        - 1/baglanti-formlari.qmd
        - 1/yapi-denklemleri.qmd
        - 1/cati-alanlari-ozeti.qmd
