project:
  type: book

metadata-files:
  - ../../_kitap-ortak.yml

book:
  title: "Kriptografi"
  reader-mode: true
  bread-crumbs: false
  sidebar:
    style: floating
    collapse-level: 1

  chapters:
    - file: index.qmd

    - part: "Kriptografiye Giriş ve Temel Kavramlar"
      chapters:
        - kriptografiye-giris/terminoloji.qmd
        - kriptografiye-giris/kerckhoffs-prensibi.qmd
        - kriptografiye-giris/matematiksel-temeller.qmd

    - part: "Klasik Şifreleme I: Yer Değiştirme (Transpozisyon) Şifreleri"
      chapters:
        - klasik-kriptografi-1/skytale.qmd
        - klasik-kriptografi-1/zigzag-rota.qmd
        - klasik-kriptografi-1/bacon-sifreleme.qmd

    - part: "Klasik Şifreleme II: Yerine Koyma (Substitution) Şifreleri"
      chapters:
        - klasik-kriptografi-2/formal-tanim.qmd
        - klasik-kriptografi-2/sezar-sifreleme.qmd
        - klasik-kriptografi-2/affine-sifreleme.qmd
        - klasik-kriptografi-2/yerine-koyma-sifresi.qmd
        - klasik-kriptografi-2/hill-sifreleme.qmd
        - klasik-kriptografi-2/vigenere-sifreleme.qmd

    - part: "Modern Kriptografiye Geçiş"
      chapters:
        - modern-gecis/binary-xor.qmd
        - modern-gecis/shannon.qmd
        - modern-gecis/one-time-pad.qmd

    - part: "Modern Simetrik Şifreleme I: Akan Şifreler"
      chapters:
        - simetrik/akan-sifreler/akan-sifreler.qmd

    - part: "Modern Simetrik Şifreleme II: Blok Şifreler"
      chapters:
        - simetrik/blok-sifreler/des.qmd
        - simetrik/blok-sifreler/aes.qmd

    - part: "Asimetrik (Açık Anahtarlı) Kriptografi"
      chapters:
        - asimetrik/giris.qmd
        - asimetrik/diffie-hellman.qmd
        - asimetrik/rsa.qmd
        - asimetrik/el-gamal.qmd

    - part: "Bütünlük ve Kimlik Doğrulama"
      chapters:
        - hash/giris.qmd
        - hash/dijital-imza.qmd
